package snaxpot

import (
	"errors"

	shopspring_decimal "github.com/shopspring/decimal"
)

type NumberMode string

const (
	// NumberModeAuto is the selection mode snapshotted onto weekly cutoff
	// allocation rows: tickets use DeriveAutogeneratedTicketNumbers unless a
	// stored per-ticket pick overrides that serial.
	NumberModeAuto NumberMode = "auto"
	// NumberModeSnaxOnly is the selection mode where standard balls come from
	// DeriveAutogeneratedTicketNumbers and the Snax ball comes from the user's
	// current preference at cutoff time.
	NumberModeSnaxOnly NumberMode = "snax_only"
)

var (
	errInvalidNumberMode = errors.New("invalid snaxpot number mode")
)

// ValidateNumberMode reports an error when mode is not a supported choice.
func ValidateNumberMode(
	mode NumberMode,
) error {
	switch mode {
	case NumberModeAuto, NumberModeSnaxOnly:
		return nil
	default:
		return errInvalidNumberMode
	}
}

// ValidSnaxBall reports whether v is a legal Snax ball value.
func ValidSnaxBall(v int) bool {
	return v >= SnaxBallMin && v <= SnaxBallMax
}

// ValidStandardBalls reports whether the balls are in range, unique, and
// strictly sorted ascending.
func ValidStandardBalls(balls []int) bool {
	if len(balls) != standardBallCount {
		return false
	}

	if balls[0] < StandardBallMin || balls[len(balls)-1] > StandardBallMax {
		return false
	}

	for i := 1; i < len(balls); i++ {
		if balls[i-1] >= balls[i] {
			return false
		}
	}

	return true
}

type stakingTier struct {
	minSNX shopspring_decimal.Decimal
	mult   shopspring_decimal.Decimal
}

var stakingTiers = []stakingTier{
	{
		minSNX: shopspring_decimal.RequireFromString("1000000"),
		mult:   shopspring_decimal.RequireFromString("2.00"),
	},
	{
		minSNX: shopspring_decimal.RequireFromString("500000"),
		mult:   shopspring_decimal.RequireFromString("1.80"),
	},
	{
		minSNX: shopspring_decimal.RequireFromString("250000"),
		mult:   shopspring_decimal.RequireFromString("1.65"),
	},
	{
		minSNX: shopspring_decimal.RequireFromString("100000"),
		mult:   shopspring_decimal.RequireFromString("1.50"),
	},
	{
		minSNX: shopspring_decimal.RequireFromString("50000"),
		mult:   shopspring_decimal.RequireFromString("1.40"),
	},
	{
		minSNX: shopspring_decimal.RequireFromString("25000"),
		mult:   shopspring_decimal.RequireFromString("1.30"),
	},
	{
		minSNX: shopspring_decimal.RequireFromString("10000"),
		mult:   shopspring_decimal.RequireFromString("1.20"),
	},
	{
		minSNX: shopspring_decimal.RequireFromString("5000"),
		mult:   shopspring_decimal.RequireFromString("1.10"),
	},
	{
		minSNX: shopspring_decimal.RequireFromString("1000"),
		mult:   shopspring_decimal.RequireFromString("1.05"),
	},
	{
		minSNX: shopspring_decimal.Zero,
		mult:   shopspring_decimal.RequireFromString("1.00"),
	},
}

// BaseTicketsFromGrossFees returns floor(grossFees / c.USDPerTicket), clamped
// at zero.
func (c Config) BaseTicketsFromGrossFees(
	grossFees shopspring_decimal.Decimal,
) int64 {
	if grossFees.Sign() <= 0 {
		return 0
	}

	q := grossFees.Div(c.USDPerTicket).Floor()

	return q.IntPart()
}

// StakingMultiplierForSNX returns the configured multiplier for snxStaked.
func StakingMultiplierForSNX(
	snxStaked shopspring_decimal.Decimal,
) shopspring_decimal.Decimal {
	if snxStaked.Sign() < 0 {
		snxStaked = shopspring_decimal.Zero
	}

	for _, row := range stakingTiers {
		if snxStaked.GreaterThanOrEqual(row.minSNX) {
			return row.mult
		}
	}

	return shopspring_decimal.RequireFromString("1.00")
}

// PurchasedMultiplierForStakingMultiplier returns the reduced multiplier that
// applies to direct sUSD purchases for the epoch. Purchases receive half of the
// uplift above the base 1.00x fee multiplier.
func PurchasedMultiplierForStakingMultiplier(
	stakingMultiplier shopspring_decimal.Decimal,
) shopspring_decimal.Decimal {
	baseMultiplier := shopspring_decimal.RequireFromString("1.00")
	if stakingMultiplier.LessThan(baseMultiplier) {
		return baseMultiplier
	}

	half := shopspring_decimal.RequireFromString("0.5")

	return baseMultiplier.Add(stakingMultiplier.Sub(baseMultiplier).Mul(half))
}

// TicketsAfterMultiplier applies the staking multiplier and floors to a whole
// ticket count.
func TicketsAfterMultiplier(
	baseTickets int64,
	multiplier shopspring_decimal.Decimal,
) int64 {
	if baseTickets <= 0 {
		return 0
	}
	if multiplier.Sign() <= 0 {
		return 0
	}

	out := shopspring_decimal.NewFromInt(baseTickets).Mul(multiplier).Floor()

	return out.IntPart()
}
