package snaxpot

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_DeriveAutogeneratedTicketNumbers_REQUIRES_SEED(t *testing.T) {
	_, _, err := DeriveAutogeneratedTicketNumbers(nil, 1, 1)

	require.ErrorIs(t, err, errAssignmentSeedEmpty)
}

func Test_DeriveAutogeneratedTicketNumbers_DETERMINISTIC(t *testing.T) {
	seed := []byte("seed-32-bytes-long-enough-for-test")

	firstBalls, firstSnax, firstErr := DeriveAutogeneratedTicketNumbers(seed, 7, 11)
	secondBalls, secondSnax, secondErr := DeriveAutogeneratedTicketNumbers(seed, 7, 11)

	require.NoError(
		t,
		firstErr,
		"expected `err` to be `nil`, but it was '%[1]s' (%[1]T)",
		firstErr,
	)
	require.NoError(
		t,
		secondErr,
		"expected `err` to be `nil`, but it was '%[1]s' (%[1]T)",
		secondErr,
	)
	assert.Equal(t, firstBalls, secondBalls)
	assert.Equal(t, firstSnax, secondSnax)
}

func Test_DeriveAutogeneratedTicketNumbers_RANGE_AND_UNIQUENESS(t *testing.T) {
	seed := []byte("seed-32-bytes-long-enough-for-test")

	standard, snaxBall, err := DeriveAutogeneratedTicketNumbers(seed, 3, 99)

	require.NoError(
		t,
		err,
		"expected `err` to be `nil`, but it was '%[1]s' (%[1]T)",
		err,
	)

	seen := make(map[int]struct{}, len(standard))
	for _, ball := range standard {
		assert.GreaterOrEqual(t, ball, StandardBallMin)
		assert.LessOrEqual(t, ball, StandardBallMax)
		_, exists := seen[ball]
		assert.False(t, exists)
		seen[ball] = struct{}{}
	}
	assert.True(t, ValidStandardBalls(standard))

	assert.GreaterOrEqual(t, snaxBall, SnaxBallMin)
	assert.LessOrEqual(t, snaxBall, SnaxBallMax)
	assert.Len(t, standard, standardBallCount)
}

func Test_DeriveAutogeneratedTicketNumbers_REFERENCE_VECTORS(t *testing.T) {
	testCases := []struct {
		name         string
		seed         []byte
		epochID      uint64
		ticketSerial uint64
		wantBalls    []int
		wantSnax     int
	}{
		{
			name:         "seed_a_epoch_1_serial_1",
			seed:         []byte("seed-32-bytes-long-enough-for-test"),
			epochID:      1,
			ticketSerial: 1,
			wantBalls:    []int{7, 12, 15, 16, 31},
			wantSnax:     4,
		},
		{
			name:         "seed_b_epoch_1_serial_1",
			seed:         []byte("seed-32-bytes-long-enough-for-test-2"),
			epochID:      1,
			ticketSerial: 1,
			wantBalls:    []int{6, 7, 8, 26, 31},
			wantSnax:     5,
		},
		{
			name:         "seed_a_epoch_7_serial_11",
			seed:         []byte("seed-32-bytes-long-enough-for-test"),
			epochID:      7,
			ticketSerial: 11,
			wantBalls:    []int{1, 5, 6, 11, 30},
			wantSnax:     4,
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			balls, snax, err := DeriveAutogeneratedTicketNumbers(
				tc.seed,
				tc.epochID,
				tc.ticketSerial,
			)

			require.NoError(
				t,
				err,
				"expected `err` to be `nil`, but it was '%[1]s' (%[1]T)",
				err,
			)
			assert.Equal(t, tc.wantBalls, balls)
			assert.Equal(t, tc.wantSnax, snax)
		})
	}
}
