package snaxpot

import (
	"encoding/binary"
	"errors"
	"sort"

	"github.com/ethereum/go-ethereum/crypto"
)

var (
	errAssignmentSeedEmpty = errors.New("assignment seed is empty")
)

// DeriveAutogeneratedTicketNumbers derives standard balls and one Snax ball
// from the assignment seed, epoch ID, and ticket serial. Ball ranges are the
// compiled-in constants StandardBallMin/Max and SnaxBallMin/Max.
func DeriveAutogeneratedTicketNumbers(
	assignmentSeed []byte,
	epochID uint64,
	ticketSerial uint64,
) ([]int, int, error) {
	if len(assignmentSeed) == 0 {
		return nil, 0, errAssignmentSeedEmpty
	}

	stream := newTicketEntropyStream(assignmentSeed, epochID, ticketSerial)

	standardRangeSize := StandardBallMax - StandardBallMin + 1
	balls := make([]int, standardRangeSize)
	for i := range balls {
		balls[i] = StandardBallMin + i
	}
	for i := len(balls) - 1; i > 0; i-- {
		j := int(stream.nextUint64Bounded(uint64(i + 1)))
		balls[i], balls[j] = balls[j], balls[i]
	}

	standard := append([]int(nil), balls[:standardBallCount]...)
	sort.Ints(standard)

	snaxRangeSize := SnaxBallMax - SnaxBallMin + 1
	snaxPool := make([]int, snaxRangeSize)
	for i := range snaxPool {
		snaxPool[i] = SnaxBallMin + i
	}
	for i := len(snaxPool) - 1; i > 0; i-- {
		j := int(stream.nextUint64Bounded(uint64(i + 1)))
		snaxPool[i], snaxPool[j] = snaxPool[j], snaxPool[i]
	}

	return standard, snaxPool[0], nil
}

type ticketEntropyStream struct {
	buf []byte
	off int
}

func newTicketEntropyStream(
	assignmentSeed []byte,
	epochID uint64,
	ticketSerial uint64,
) *ticketEntropyStream {
	pack := make([]byte, 0, len(assignmentSeed)+2*8)
	pack = append(pack, assignmentSeed...)
	pack = binary.BigEndian.AppendUint64(pack, epochID)
	pack = binary.BigEndian.AppendUint64(pack, ticketSerial)

	return &ticketEntropyStream{
		buf: crypto.Keccak256(pack),
	}
}

func (s *ticketEntropyStream) refill() {
	s.buf = crypto.Keccak256(s.buf)
	s.off = 0
}

func (s *ticketEntropyStream) nextByte() byte {
	if s.off >= len(s.buf) {
		s.refill()
	}

	b := s.buf[s.off]
	s.off++

	return b
}

func (s *ticketEntropyStream) nextUint64Bounded(mod uint64) uint64 {
	if mod == 0 {
		return 0
	}

	const maxUint64 = ^uint64(0)
	limit := maxUint64 - (maxUint64 % mod)

	for {
		var value uint64
		for i := 0; i < 8; i++ {
			value = value<<8 | uint64(s.nextByte())
		}
		if value < limit {
			return value % mod
		}
	}
}
