// Proto definition for Synthetix V4-Offchain Common
// To compile:
// protoc --go_out=. --go-grpc_out=. common.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: common.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Defines the order side (buy or sell)
type Side int32

const (
	Side_BUY  Side = 0
	Side_SELL Side = 1
)

// Enum value maps for Side.
var (
	Side_name = map[int32]string{
		0: "BUY",
		1: "SELL",
	}
	Side_value = map[string]int32{
		"BUY":  0,
		"SELL": 1,
	}
)

func (x Side) Enum() *Side {
	p := new(Side)
	*p = x
	return p
}

func (x Side) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Side) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[0].Descriptor()
}

func (Side) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[0]
}

func (x Side) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Side.Descriptor instead.
func (Side) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

// Defines the position side for hedge mode vs one-way mode
type PositionSide int32

const (
	PositionSide_BOTH  PositionSide = 0 // For One-way Mode
	PositionSide_LONG  PositionSide = 1 // For Hedge Mode
	PositionSide_SHORT PositionSide = 2 // For Hedge Mode
)

// Enum value maps for PositionSide.
var (
	PositionSide_name = map[int32]string{
		0: "BOTH",
		1: "LONG",
		2: "SHORT",
	}
	PositionSide_value = map[string]int32{
		"BOTH":  0,
		"LONG":  1,
		"SHORT": 2,
	}
)

func (x PositionSide) Enum() *PositionSide {
	p := new(PositionSide)
	*p = x
	return p
}

func (x PositionSide) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PositionSide) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[1].Descriptor()
}

func (PositionSide) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[1]
}

func (x PositionSide) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PositionSide.Descriptor instead.
func (PositionSide) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

// Defines the supported order types (limit, market, stop, etc.)
type OrderType int32

const (
	OrderType_LIMIT                OrderType = 0
	OrderType_MARKET               OrderType = 1
	OrderType_STOP                 OrderType = 2
	OrderType_STOP_MARKET          OrderType = 3
	OrderType_TAKE_PROFIT          OrderType = 4
	OrderType_TAKE_PROFIT_MARKET   OrderType = 5
	OrderType_TRAILING_STOP_MARKET OrderType = 6
	OrderType_TWAP                 OrderType = 7
)

// Enum value maps for OrderType.
var (
	OrderType_name = map[int32]string{
		0: "LIMIT",
		1: "MARKET",
		2: "STOP",
		3: "STOP_MARKET",
		4: "TAKE_PROFIT",
		5: "TAKE_PROFIT_MARKET",
		6: "TRAILING_STOP_MARKET",
		7: "TWAP",
	}
	OrderType_value = map[string]int32{
		"LIMIT":                0,
		"MARKET":               1,
		"STOP":                 2,
		"STOP_MARKET":          3,
		"TAKE_PROFIT":          4,
		"TAKE_PROFIT_MARKET":   5,
		"TRAILING_STOP_MARKET": 6,
		"TWAP":                 7,
	}
)

func (x OrderType) Enum() *OrderType {
	p := new(OrderType)
	*p = x
	return p
}

func (x OrderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[2].Descriptor()
}

func (OrderType) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[2]
}

func (x OrderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderType.Descriptor instead.
func (OrderType) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

// Defines the order lifetime policy
type TimeInForce int32

const (
	TimeInForce_GTC TimeInForce = 0 // Good Til Canceled
	TimeInForce_IOC TimeInForce = 1 // Immediate or Cancel
	TimeInForce_FOK TimeInForce = 2 // Fill or Kill
	TimeInForce_GTD TimeInForce = 3 // Good Til Date
)

// Enum value maps for TimeInForce.
var (
	TimeInForce_name = map[int32]string{
		0: "GTC",
		1: "IOC",
		2: "FOK",
		3: "GTD",
	}
	TimeInForce_value = map[string]int32{
		"GTC": 0,
		"IOC": 1,
		"FOK": 2,
		"GTD": 3,
	}
)

func (x TimeInForce) Enum() *TimeInForce {
	p := new(TimeInForce)
	*p = x
	return p
}

func (x TimeInForce) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TimeInForce) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[3].Descriptor()
}

func (TimeInForce) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[3]
}

func (x TimeInForce) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TimeInForce.Descriptor instead.
func (TimeInForce) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{3}
}

// Always keep UNKNOWN as the first option.
// Sort anything after UNKNOWN
type OrderStatus int32

const (
	OrderStatus_UNKNOWN          OrderStatus = 0
	OrderStatus_MODIFIED         OrderStatus = 1
	OrderStatus_ACCEPTED         OrderStatus = 2
	OrderStatus_CANCELLED        OrderStatus = 3
	OrderStatus_EXPIRED          OrderStatus = 4 // Order expired (e.g., IOC, FOK not filled)
	OrderStatus_FILLED           OrderStatus = 5
	OrderStatus_PARTIALLY_FILLED OrderStatus = 6 // Market orders that get partially filled the rest just gets cancelled nothing is left on the order book
	OrderStatus_PENDING          OrderStatus = 7
	OrderStatus_REJECTED         OrderStatus = 8 // No liquidity in the order book when a market order hits the matching service
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "MODIFIED",
		2: "ACCEPTED",
		3: "CANCELLED",
		4: "EXPIRED",
		5: "FILLED",
		6: "PARTIALLY_FILLED",
		7: "PENDING",
		8: "REJECTED",
	}
	OrderStatus_value = map[string]int32{
		"UNKNOWN":          0,
		"MODIFIED":         1,
		"ACCEPTED":         2,
		"CANCELLED":        3,
		"EXPIRED":          4,
		"FILLED":           5,
		"PARTIALLY_FILLED": 6,
		"PENDING":          7,
		"REJECTED":         8,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[4].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[4]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4}
}

// A composite order identifier, comprising the system-generated venue
// identifier and the optional client order identifier
//
// NOTE: once all the CLOID work has been propagated throughout the
// codebase, this will be renamed to `OrderId`
type OrderId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VenueId       uint64                 `protobuf:"varint,1,opt,name=venue_id,json=venueId,proto3" json:"venue_id,omitempty"`   // The internal, mandatory, system-generated identifier
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"` // The (optional, because can be empty) client order identifier that will be always associated with the venue id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderId) Reset() {
	*x = OrderId{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderId) ProtoMessage() {}

func (x *OrderId) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderId.ProtoReflect.Descriptor instead.
func (*OrderId) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *OrderId) GetVenueId() uint64 {
	if x != nil {
		return x.VenueId
	}
	return 0
}

func (x *OrderId) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\x1csynthetix.v4_offchain.common\"A\n" +
	"\aOrderId\x12\x19\n" +
	"\bvenue_id\x18\x01 \x01(\x04R\avenueId\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId*\x19\n" +
	"\x04Side\x12\a\n" +
	"\x03BUY\x10\x00\x12\b\n" +
	"\x04SELL\x10\x01*-\n" +
	"\fPositionSide\x12\b\n" +
	"\x04BOTH\x10\x00\x12\b\n" +
	"\x04LONG\x10\x01\x12\t\n" +
	"\x05SHORT\x10\x02*\x8a\x01\n" +
	"\tOrderType\x12\t\n" +
	"\x05LIMIT\x10\x00\x12\n" +
	"\n" +
	"\x06MARKET\x10\x01\x12\b\n" +
	"\x04STOP\x10\x02\x12\x0f\n" +
	"\vSTOP_MARKET\x10\x03\x12\x0f\n" +
	"\vTAKE_PROFIT\x10\x04\x12\x16\n" +
	"\x12TAKE_PROFIT_MARKET\x10\x05\x12\x18\n" +
	"\x14TRAILING_STOP_MARKET\x10\x06\x12\b\n" +
	"\x04TWAP\x10\a*1\n" +
	"\vTimeInForce\x12\a\n" +
	"\x03GTC\x10\x00\x12\a\n" +
	"\x03IOC\x10\x01\x12\a\n" +
	"\x03FOK\x10\x02\x12\a\n" +
	"\x03GTD\x10\x03*\x8f\x01\n" +
	"\vOrderStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\f\n" +
	"\bMODIFIED\x10\x01\x12\f\n" +
	"\bACCEPTED\x10\x02\x12\r\n" +
	"\tCANCELLED\x10\x03\x12\v\n" +
	"\aEXPIRED\x10\x04\x12\n" +
	"\n" +
	"\x06FILLED\x10\x05\x12\x14\n" +
	"\x10PARTIALLY_FILLED\x10\x06\x12\v\n" +
	"\aPENDING\x10\a\x12\f\n" +
	"\bREJECTED\x10\bB5Z3github.com/Synthetixio/v4-offchain/lib/message/grpcb\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_common_proto_goTypes = []any{
	(Side)(0),         // 0: synthetix.v4_offchain.common.Side
	(PositionSide)(0), // 1: synthetix.v4_offchain.common.PositionSide
	(OrderType)(0),    // 2: synthetix.v4_offchain.common.OrderType
	(TimeInForce)(0),  // 3: synthetix.v4_offchain.common.TimeInForce
	(OrderStatus)(0),  // 4: synthetix.v4_offchain.common.OrderStatus
	(*OrderId)(nil),   // 5: synthetix.v4_offchain.common.OrderId
}
var file_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		EnumInfos:         file_common_proto_enumTypes,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
