// Proto definition for Synthetix V4-Offchain Market Configuration Service
// To compile:
// protoc --go_out=. --go-grpc_out=. marketconfig.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: marketconfig.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MarketConfigService_GetAllMarketPrices_FullMethodName          = "/synthetix.v4_offchain.marketconfig.MarketConfigService/GetAllMarketPrices"
	MarketConfigService_GetAllMarkets_FullMethodName               = "/synthetix.v4_offchain.marketconfig.MarketConfigService/GetAllMarkets"
	MarketConfigService_GetMarket_FullMethodName                   = "/synthetix.v4_offchain.marketconfig.MarketConfigService/GetMarket"
	MarketConfigService_GetFundingSettings_FullMethodName          = "/synthetix.v4_offchain.marketconfig.MarketConfigService/GetFundingSettings"
	MarketConfigService_GetExchangeConfigs_FullMethodName          = "/synthetix.v4_offchain.marketconfig.MarketConfigService/GetExchangeConfigs"
	MarketConfigService_UpdateMarketStatus_FullMethodName          = "/synthetix.v4_offchain.marketconfig.MarketConfigService/UpdateMarketStatus"
	MarketConfigService_CreateMarket_FullMethodName                = "/synthetix.v4_offchain.marketconfig.MarketConfigService/CreateMarket"
	MarketConfigService_GetAllSLPExposureLimits_FullMethodName     = "/synthetix.v4_offchain.marketconfig.MarketConfigService/GetAllSLPExposureLimits"
	MarketConfigService_GetCollateralConfigs_FullMethodName        = "/synthetix.v4_offchain.marketconfig.MarketConfigService/GetCollateralConfigs"
	MarketConfigService_GetCollateralPricingConfigs_FullMethodName = "/synthetix.v4_offchain.marketconfig.MarketConfigService/GetCollateralPricingConfigs"
)

// MarketConfigServiceClient is the client API for MarketConfigService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Provides market configuration and pricing data
type MarketConfigServiceClient interface {
	// Get all latest market prices
	GetAllMarketPrices(ctx context.Context, in *GetAllMarketPricesRequest, opts ...grpc.CallOption) (*GetAllMarketPricesResponse, error)
	// Get all markets with full configuration
	GetAllMarkets(ctx context.Context, in *GetAllMarketsRequest, opts ...grpc.CallOption) (*GetAllMarketsResponse, error)
	// Get a specific market by symbol
	GetMarket(ctx context.Context, in *GetMarketRequest, opts ...grpc.CallOption) (*GetMarketResponse, error)
	// Get global funding settings
	GetFundingSettings(ctx context.Context, in *GetFundingSettingsRequest, opts ...grpc.CallOption) (*GetFundingSettingsResponse, error)
	// Get exchange configurations for aggregate pricing
	GetExchangeConfigs(ctx context.Context, in *GetExchangeConfigsRequest, opts ...grpc.CallOption) (*GetExchangeConfigsResponse, error)
	// Admin: Update market status (open/close, freeze/unfreeze)
	UpdateMarketStatus(ctx context.Context, in *UpdateMarketStatusRequest, opts ...grpc.CallOption) (*UpdateMarketStatusResponse, error)
	// Admin: Create a new market
	CreateMarket(ctx context.Context, in *CreateMarketRequest, opts ...grpc.CallOption) (*CreateMarketResponse, error)
	// Get all SLP exposure limits per market
	GetAllSLPExposureLimits(ctx context.Context, in *GetAllSLPExposureLimitsRequest, opts ...grpc.CallOption) (*GetAllSLPExposureLimitsResponse, error)
	// Get all collateral configurations with haircut tiers
	GetCollateralConfigs(ctx context.Context, in *GetCollateralConfigsRequest, opts ...grpc.CallOption) (*GetCollateralConfigsResponse, error)
	// Get collateral pricing configurations used by the pricing service
	GetCollateralPricingConfigs(ctx context.Context, in *GetCollateralPricingConfigsRequest, opts ...grpc.CallOption) (*GetCollateralPricingConfigsResponse, error)
}

type marketConfigServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMarketConfigServiceClient(cc grpc.ClientConnInterface) MarketConfigServiceClient {
	return &marketConfigServiceClient{cc}
}

func (c *marketConfigServiceClient) GetAllMarketPrices(ctx context.Context, in *GetAllMarketPricesRequest, opts ...grpc.CallOption) (*GetAllMarketPricesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllMarketPricesResponse)
	err := c.cc.Invoke(ctx, MarketConfigService_GetAllMarketPrices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketConfigServiceClient) GetAllMarkets(ctx context.Context, in *GetAllMarketsRequest, opts ...grpc.CallOption) (*GetAllMarketsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllMarketsResponse)
	err := c.cc.Invoke(ctx, MarketConfigService_GetAllMarkets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketConfigServiceClient) GetMarket(ctx context.Context, in *GetMarketRequest, opts ...grpc.CallOption) (*GetMarketResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMarketResponse)
	err := c.cc.Invoke(ctx, MarketConfigService_GetMarket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketConfigServiceClient) GetFundingSettings(ctx context.Context, in *GetFundingSettingsRequest, opts ...grpc.CallOption) (*GetFundingSettingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFundingSettingsResponse)
	err := c.cc.Invoke(ctx, MarketConfigService_GetFundingSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketConfigServiceClient) GetExchangeConfigs(ctx context.Context, in *GetExchangeConfigsRequest, opts ...grpc.CallOption) (*GetExchangeConfigsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetExchangeConfigsResponse)
	err := c.cc.Invoke(ctx, MarketConfigService_GetExchangeConfigs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketConfigServiceClient) UpdateMarketStatus(ctx context.Context, in *UpdateMarketStatusRequest, opts ...grpc.CallOption) (*UpdateMarketStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateMarketStatusResponse)
	err := c.cc.Invoke(ctx, MarketConfigService_UpdateMarketStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketConfigServiceClient) CreateMarket(ctx context.Context, in *CreateMarketRequest, opts ...grpc.CallOption) (*CreateMarketResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateMarketResponse)
	err := c.cc.Invoke(ctx, MarketConfigService_CreateMarket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketConfigServiceClient) GetAllSLPExposureLimits(ctx context.Context, in *GetAllSLPExposureLimitsRequest, opts ...grpc.CallOption) (*GetAllSLPExposureLimitsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllSLPExposureLimitsResponse)
	err := c.cc.Invoke(ctx, MarketConfigService_GetAllSLPExposureLimits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketConfigServiceClient) GetCollateralConfigs(ctx context.Context, in *GetCollateralConfigsRequest, opts ...grpc.CallOption) (*GetCollateralConfigsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCollateralConfigsResponse)
	err := c.cc.Invoke(ctx, MarketConfigService_GetCollateralConfigs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketConfigServiceClient) GetCollateralPricingConfigs(ctx context.Context, in *GetCollateralPricingConfigsRequest, opts ...grpc.CallOption) (*GetCollateralPricingConfigsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCollateralPricingConfigsResponse)
	err := c.cc.Invoke(ctx, MarketConfigService_GetCollateralPricingConfigs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MarketConfigServiceServer is the server API for MarketConfigService service.
// All implementations must embed UnimplementedMarketConfigServiceServer
// for forward compatibility.
//
// Provides market configuration and pricing data
type MarketConfigServiceServer interface {
	// Get all latest market prices
	GetAllMarketPrices(context.Context, *GetAllMarketPricesRequest) (*GetAllMarketPricesResponse, error)
	// Get all markets with full configuration
	GetAllMarkets(context.Context, *GetAllMarketsRequest) (*GetAllMarketsResponse, error)
	// Get a specific market by symbol
	GetMarket(context.Context, *GetMarketRequest) (*GetMarketResponse, error)
	// Get global funding settings
	GetFundingSettings(context.Context, *GetFundingSettingsRequest) (*GetFundingSettingsResponse, error)
	// Get exchange configurations for aggregate pricing
	GetExchangeConfigs(context.Context, *GetExchangeConfigsRequest) (*GetExchangeConfigsResponse, error)
	// Admin: Update market status (open/close, freeze/unfreeze)
	UpdateMarketStatus(context.Context, *UpdateMarketStatusRequest) (*UpdateMarketStatusResponse, error)
	// Admin: Create a new market
	CreateMarket(context.Context, *CreateMarketRequest) (*CreateMarketResponse, error)
	// Get all SLP exposure limits per market
	GetAllSLPExposureLimits(context.Context, *GetAllSLPExposureLimitsRequest) (*GetAllSLPExposureLimitsResponse, error)
	// Get all collateral configurations with haircut tiers
	GetCollateralConfigs(context.Context, *GetCollateralConfigsRequest) (*GetCollateralConfigsResponse, error)
	// Get collateral pricing configurations used by the pricing service
	GetCollateralPricingConfigs(context.Context, *GetCollateralPricingConfigsRequest) (*GetCollateralPricingConfigsResponse, error)
	mustEmbedUnimplementedMarketConfigServiceServer()
}

// UnimplementedMarketConfigServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMarketConfigServiceServer struct{}

func (UnimplementedMarketConfigServiceServer) GetAllMarketPrices(context.Context, *GetAllMarketPricesRequest) (*GetAllMarketPricesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllMarketPrices not implemented")
}
func (UnimplementedMarketConfigServiceServer) GetAllMarkets(context.Context, *GetAllMarketsRequest) (*GetAllMarketsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllMarkets not implemented")
}
func (UnimplementedMarketConfigServiceServer) GetMarket(context.Context, *GetMarketRequest) (*GetMarketResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMarket not implemented")
}
func (UnimplementedMarketConfigServiceServer) GetFundingSettings(context.Context, *GetFundingSettingsRequest) (*GetFundingSettingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFundingSettings not implemented")
}
func (UnimplementedMarketConfigServiceServer) GetExchangeConfigs(context.Context, *GetExchangeConfigsRequest) (*GetExchangeConfigsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetExchangeConfigs not implemented")
}
func (UnimplementedMarketConfigServiceServer) UpdateMarketStatus(context.Context, *UpdateMarketStatusRequest) (*UpdateMarketStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateMarketStatus not implemented")
}
func (UnimplementedMarketConfigServiceServer) CreateMarket(context.Context, *CreateMarketRequest) (*CreateMarketResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateMarket not implemented")
}
func (UnimplementedMarketConfigServiceServer) GetAllSLPExposureLimits(context.Context, *GetAllSLPExposureLimitsRequest) (*GetAllSLPExposureLimitsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllSLPExposureLimits not implemented")
}
func (UnimplementedMarketConfigServiceServer) GetCollateralConfigs(context.Context, *GetCollateralConfigsRequest) (*GetCollateralConfigsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCollateralConfigs not implemented")
}
func (UnimplementedMarketConfigServiceServer) GetCollateralPricingConfigs(context.Context, *GetCollateralPricingConfigsRequest) (*GetCollateralPricingConfigsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCollateralPricingConfigs not implemented")
}
func (UnimplementedMarketConfigServiceServer) mustEmbedUnimplementedMarketConfigServiceServer() {}
func (UnimplementedMarketConfigServiceServer) testEmbeddedByValue()                             {}

// UnsafeMarketConfigServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MarketConfigServiceServer will
// result in compilation errors.
type UnsafeMarketConfigServiceServer interface {
	mustEmbedUnimplementedMarketConfigServiceServer()
}

func RegisterMarketConfigServiceServer(s grpc.ServiceRegistrar, srv MarketConfigServiceServer) {
	// If the following call panics, it indicates UnimplementedMarketConfigServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MarketConfigService_ServiceDesc, srv)
}

func _MarketConfigService_GetAllMarketPrices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllMarketPricesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketConfigServiceServer).GetAllMarketPrices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketConfigService_GetAllMarketPrices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketConfigServiceServer).GetAllMarketPrices(ctx, req.(*GetAllMarketPricesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketConfigService_GetAllMarkets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllMarketsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketConfigServiceServer).GetAllMarkets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketConfigService_GetAllMarkets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketConfigServiceServer).GetAllMarkets(ctx, req.(*GetAllMarketsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketConfigService_GetMarket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMarketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketConfigServiceServer).GetMarket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketConfigService_GetMarket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketConfigServiceServer).GetMarket(ctx, req.(*GetMarketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketConfigService_GetFundingSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFundingSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketConfigServiceServer).GetFundingSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketConfigService_GetFundingSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketConfigServiceServer).GetFundingSettings(ctx, req.(*GetFundingSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketConfigService_GetExchangeConfigs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExchangeConfigsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketConfigServiceServer).GetExchangeConfigs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketConfigService_GetExchangeConfigs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketConfigServiceServer).GetExchangeConfigs(ctx, req.(*GetExchangeConfigsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketConfigService_UpdateMarketStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMarketStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketConfigServiceServer).UpdateMarketStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketConfigService_UpdateMarketStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketConfigServiceServer).UpdateMarketStatus(ctx, req.(*UpdateMarketStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketConfigService_CreateMarket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMarketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketConfigServiceServer).CreateMarket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketConfigService_CreateMarket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketConfigServiceServer).CreateMarket(ctx, req.(*CreateMarketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketConfigService_GetAllSLPExposureLimits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllSLPExposureLimitsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketConfigServiceServer).GetAllSLPExposureLimits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketConfigService_GetAllSLPExposureLimits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketConfigServiceServer).GetAllSLPExposureLimits(ctx, req.(*GetAllSLPExposureLimitsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketConfigService_GetCollateralConfigs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCollateralConfigsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketConfigServiceServer).GetCollateralConfigs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketConfigService_GetCollateralConfigs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketConfigServiceServer).GetCollateralConfigs(ctx, req.(*GetCollateralConfigsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketConfigService_GetCollateralPricingConfigs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCollateralPricingConfigsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketConfigServiceServer).GetCollateralPricingConfigs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketConfigService_GetCollateralPricingConfigs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketConfigServiceServer).GetCollateralPricingConfigs(ctx, req.(*GetCollateralPricingConfigsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MarketConfigService_ServiceDesc is the grpc.ServiceDesc for MarketConfigService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MarketConfigService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "synthetix.v4_offchain.marketconfig.MarketConfigService",
	HandlerType: (*MarketConfigServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllMarketPrices",
			Handler:    _MarketConfigService_GetAllMarketPrices_Handler,
		},
		{
			MethodName: "GetAllMarkets",
			Handler:    _MarketConfigService_GetAllMarkets_Handler,
		},
		{
			MethodName: "GetMarket",
			Handler:    _MarketConfigService_GetMarket_Handler,
		},
		{
			MethodName: "GetFundingSettings",
			Handler:    _MarketConfigService_GetFundingSettings_Handler,
		},
		{
			MethodName: "GetExchangeConfigs",
			Handler:    _MarketConfigService_GetExchangeConfigs_Handler,
		},
		{
			MethodName: "UpdateMarketStatus",
			Handler:    _MarketConfigService_UpdateMarketStatus_Handler,
		},
		{
			MethodName: "CreateMarket",
			Handler:    _MarketConfigService_CreateMarket_Handler,
		},
		{
			MethodName: "GetAllSLPExposureLimits",
			Handler:    _MarketConfigService_GetAllSLPExposureLimits_Handler,
		},
		{
			MethodName: "GetCollateralConfigs",
			Handler:    _MarketConfigService_GetCollateralConfigs_Handler,
		},
		{
			MethodName: "GetCollateralPricingConfigs",
			Handler:    _MarketConfigService_GetCollateralPricingConfigs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "marketconfig.proto",
}
