// Proto definition for Synthetix V4-Offchain Market Data Service
// To compile:
// protoc --go_out=. --go-grpc_out=. marketdata.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: marketdata.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Represents a single price level in the orderbook [price, quantity]
type PriceLevel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         string                 `protobuf:"bytes,1,opt,name=price,proto3" json:"price,omitempty"`       // Price as string to maintain precision
	Quantity      string                 `protobuf:"bytes,2,opt,name=quantity,proto3" json:"quantity,omitempty"` // Quantity as string to maintain precision
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceLevel) Reset() {
	*x = PriceLevel{}
	mi := &file_marketdata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceLevel) ProtoMessage() {}

func (x *PriceLevel) ProtoReflect() protoreflect.Message {
	mi := &file_marketdata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceLevel.ProtoReflect.Descriptor instead.
func (*PriceLevel) Descriptor() ([]byte, []int) {
	return file_marketdata_proto_rawDescGZIP(), []int{0}
}

func (x *PriceLevel) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *PriceLevel) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

// Requests a complete orderbook snapshot for a symbol
type OrderbookSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimestampMs   int64                  `protobuf:"varint,101,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	TimestampUs   int64                  `protobuf:"varint,102,opt,name=timestamp_us,json=timestampUs,proto3" json:"timestamp_us,omitempty"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"` // Trading symbol (e.g., "BTC-USD")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderbookSnapshotRequest) Reset() {
	*x = OrderbookSnapshotRequest{}
	mi := &file_marketdata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderbookSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderbookSnapshotRequest) ProtoMessage() {}

func (x *OrderbookSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marketdata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderbookSnapshotRequest.ProtoReflect.Descriptor instead.
func (*OrderbookSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_marketdata_proto_rawDescGZIP(), []int{1}
}

func (x *OrderbookSnapshotRequest) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *OrderbookSnapshotRequest) GetTimestampUs() int64 {
	if x != nil {
		return x.TimestampUs
	}
	return 0
}

func (x *OrderbookSnapshotRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

// Returns a complete orderbook snapshot with bid and ask levels
type OrderbookSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimestampMs   int64                  `protobuf:"varint,101,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	TimestampUs   int64                  `protobuf:"varint,102,opt,name=timestamp_us,json=timestampUs,proto3" json:"timestamp_us,omitempty"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"` // Trading symbol
	Bids          []*PriceLevel          `protobuf:"bytes,2,rep,name=bids,proto3" json:"bids,omitempty"`     // Bid levels (highest to lowest)
	Asks          []*PriceLevel          `protobuf:"bytes,3,rep,name=asks,proto3" json:"asks,omitempty"`     // Ask levels (lowest to highest)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderbookSnapshotResponse) Reset() {
	*x = OrderbookSnapshotResponse{}
	mi := &file_marketdata_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderbookSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderbookSnapshotResponse) ProtoMessage() {}

func (x *OrderbookSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marketdata_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderbookSnapshotResponse.ProtoReflect.Descriptor instead.
func (*OrderbookSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_marketdata_proto_rawDescGZIP(), []int{2}
}

func (x *OrderbookSnapshotResponse) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *OrderbookSnapshotResponse) GetTimestampUs() int64 {
	if x != nil {
		return x.TimestampUs
	}
	return 0
}

func (x *OrderbookSnapshotResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *OrderbookSnapshotResponse) GetBids() []*PriceLevel {
	if x != nil {
		return x.Bids
	}
	return nil
}

func (x *OrderbookSnapshotResponse) GetAsks() []*PriceLevel {
	if x != nil {
		return x.Asks
	}
	return nil
}

// Requests orderbook depth data with a configurable level limit
type OrderbookDepthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimestampMs   int64                  `protobuf:"varint,101,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	TimestampUs   int64                  `protobuf:"varint,102,opt,name=timestamp_us,json=timestampUs,proto3" json:"timestamp_us,omitempty"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"` // Trading symbol (e.g., "BTC-USD")
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`  // Number of price levels to return (0 means server applies default of 500)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderbookDepthRequest) Reset() {
	*x = OrderbookDepthRequest{}
	mi := &file_marketdata_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderbookDepthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderbookDepthRequest) ProtoMessage() {}

func (x *OrderbookDepthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marketdata_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderbookDepthRequest.ProtoReflect.Descriptor instead.
func (*OrderbookDepthRequest) Descriptor() ([]byte, []int) {
	return file_marketdata_proto_rawDescGZIP(), []int{3}
}

func (x *OrderbookDepthRequest) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *OrderbookDepthRequest) GetTimestampUs() int64 {
	if x != nil {
		return x.TimestampUs
	}
	return 0
}

func (x *OrderbookDepthRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *OrderbookDepthRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// Returns orderbook depth data with bid and ask levels
type OrderbookDepthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimestampMs   int64                  `protobuf:"varint,101,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	TimestampUs   int64                  `protobuf:"varint,102,opt,name=timestamp_us,json=timestampUs,proto3" json:"timestamp_us,omitempty"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"` // Trading symbol
	Bids          []*PriceLevel          `protobuf:"bytes,2,rep,name=bids,proto3" json:"bids,omitempty"`     // Bid levels (highest to lowest)
	Asks          []*PriceLevel          `protobuf:"bytes,3,rep,name=asks,proto3" json:"asks,omitempty"`     // Ask levels (lowest to highest)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderbookDepthResponse) Reset() {
	*x = OrderbookDepthResponse{}
	mi := &file_marketdata_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderbookDepthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderbookDepthResponse) ProtoMessage() {}

func (x *OrderbookDepthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marketdata_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderbookDepthResponse.ProtoReflect.Descriptor instead.
func (*OrderbookDepthResponse) Descriptor() ([]byte, []int) {
	return file_marketdata_proto_rawDescGZIP(), []int{4}
}

func (x *OrderbookDepthResponse) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *OrderbookDepthResponse) GetTimestampUs() int64 {
	if x != nil {
		return x.TimestampUs
	}
	return 0
}

func (x *OrderbookDepthResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *OrderbookDepthResponse) GetBids() []*PriceLevel {
	if x != nil {
		return x.Bids
	}
	return nil
}

func (x *OrderbookDepthResponse) GetAsks() []*PriceLevel {
	if x != nil {
		return x.Asks
	}
	return nil
}

// Requests current market data for a symbol
type MarketDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimestampMs   int64                  `protobuf:"varint,101,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	TimestampUs   int64                  `protobuf:"varint,102,opt,name=timestamp_us,json=timestampUs,proto3" json:"timestamp_us,omitempty"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"` // Trading symbol (e.g., "BTC-USD")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketDataRequest) Reset() {
	*x = MarketDataRequest{}
	mi := &file_marketdata_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketDataRequest) ProtoMessage() {}

func (x *MarketDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marketdata_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketDataRequest.ProtoReflect.Descriptor instead.
func (*MarketDataRequest) Descriptor() ([]byte, []int) {
	return file_marketdata_proto_rawDescGZIP(), []int{5}
}

func (x *MarketDataRequest) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *MarketDataRequest) GetTimestampUs() int64 {
	if x != nil {
		return x.TimestampUs
	}
	return 0
}

func (x *MarketDataRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

// Returns current market data including prices and volume
type MarketDataResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TimestampMs     int64                  `protobuf:"varint,101,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	TimestampUs     int64                  `protobuf:"varint,102,opt,name=timestamp_us,json=timestampUs,proto3" json:"timestamp_us,omitempty"`
	Symbol          string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`                                            // Trading symbol
	BestBidPrice    string                 `protobuf:"bytes,2,opt,name=best_bid_price,json=bestBidPrice,proto3" json:"best_bid_price,omitempty"`          // Best bid price
	BestAskPrice    string                 `protobuf:"bytes,3,opt,name=best_ask_price,json=bestAskPrice,proto3" json:"best_ask_price,omitempty"`          // Best ask price
	LastTradedPrice string                 `protobuf:"bytes,4,opt,name=last_traded_price,json=lastTradedPrice,proto3" json:"last_traded_price,omitempty"` // Last traded price
	LastTradedTime  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_traded_time,json=lastTradedTime,proto3" json:"last_traded_time,omitempty"`    // Last trade timestamp
	PrevDayPrice    string                 `protobuf:"bytes,6,opt,name=prev_day_price,json=prevDayPrice,proto3" json:"prev_day_price,omitempty"`          // Previous day closing price (24h ago)
	Volume_24H      string                 `protobuf:"bytes,7,opt,name=volume_24h,json=volume24h,proto3" json:"volume_24h,omitempty"`                     // 24-hour trading volume in base asset
	QuoteVolume_24H string                 `protobuf:"bytes,8,opt,name=quote_volume_24h,json=quoteVolume24h,proto3" json:"quote_volume_24h,omitempty"`    // 24-hour trading volume in quote asset
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MarketDataResponse) Reset() {
	*x = MarketDataResponse{}
	mi := &file_marketdata_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketDataResponse) ProtoMessage() {}

func (x *MarketDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marketdata_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketDataResponse.ProtoReflect.Descriptor instead.
func (*MarketDataResponse) Descriptor() ([]byte, []int) {
	return file_marketdata_proto_rawDescGZIP(), []int{6}
}

func (x *MarketDataResponse) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *MarketDataResponse) GetTimestampUs() int64 {
	if x != nil {
		return x.TimestampUs
	}
	return 0
}

func (x *MarketDataResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *MarketDataResponse) GetBestBidPrice() string {
	if x != nil {
		return x.BestBidPrice
	}
	return ""
}

func (x *MarketDataResponse) GetBestAskPrice() string {
	if x != nil {
		return x.BestAskPrice
	}
	return ""
}

func (x *MarketDataResponse) GetLastTradedPrice() string {
	if x != nil {
		return x.LastTradedPrice
	}
	return ""
}

func (x *MarketDataResponse) GetLastTradedTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastTradedTime
	}
	return nil
}

func (x *MarketDataResponse) GetPrevDayPrice() string {
	if x != nil {
		return x.PrevDayPrice
	}
	return ""
}

func (x *MarketDataResponse) GetVolume_24H() string {
	if x != nil {
		return x.Volume_24H
	}
	return ""
}

func (x *MarketDataResponse) GetQuoteVolume_24H() string {
	if x != nil {
		return x.QuoteVolume_24H
	}
	return ""
}

// Requests current market data for multiple symbols in one call
type GetAllMarketDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimestampMs   int64                  `protobuf:"varint,101,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	TimestampUs   int64                  `protobuf:"varint,102,opt,name=timestamp_us,json=timestampUs,proto3" json:"timestamp_us,omitempty"`
	Symbols       []string               `protobuf:"bytes,1,rep,name=symbols,proto3" json:"symbols,omitempty"` // Symbols to fetch; request must include at least one symbol
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllMarketDataRequest) Reset() {
	*x = GetAllMarketDataRequest{}
	mi := &file_marketdata_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllMarketDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllMarketDataRequest) ProtoMessage() {}

func (x *GetAllMarketDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marketdata_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllMarketDataRequest.ProtoReflect.Descriptor instead.
func (*GetAllMarketDataRequest) Descriptor() ([]byte, []int) {
	return file_marketdata_proto_rawDescGZIP(), []int{7}
}

func (x *GetAllMarketDataRequest) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *GetAllMarketDataRequest) GetTimestampUs() int64 {
	if x != nil {
		return x.TimestampUs
	}
	return 0
}

func (x *GetAllMarketDataRequest) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

// Returns current market data for all requested symbols
type GetAllMarketDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimestampMs   int64                  `protobuf:"varint,101,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	TimestampUs   int64                  `protobuf:"varint,102,opt,name=timestamp_us,json=timestampUs,proto3" json:"timestamp_us,omitempty"`
	Markets       []*MarketDataResponse  `protobuf:"bytes,1,rep,name=markets,proto3" json:"markets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllMarketDataResponse) Reset() {
	*x = GetAllMarketDataResponse{}
	mi := &file_marketdata_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllMarketDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllMarketDataResponse) ProtoMessage() {}

func (x *GetAllMarketDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marketdata_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllMarketDataResponse.ProtoReflect.Descriptor instead.
func (*GetAllMarketDataResponse) Descriptor() ([]byte, []int) {
	return file_marketdata_proto_rawDescGZIP(), []int{8}
}

func (x *GetAllMarketDataResponse) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *GetAllMarketDataResponse) GetTimestampUs() int64 {
	if x != nil {
		return x.TimestampUs
	}
	return 0
}

func (x *GetAllMarketDataResponse) GetMarkets() []*MarketDataResponse {
	if x != nil {
		return x.Markets
	}
	return nil
}

// Represents a single candlestick (OHLCV) data point
type Candlestick struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`                               // Trading symbol
	Timeframe     string                 `protobuf:"bytes,2,opt,name=timeframe,proto3" json:"timeframe,omitempty"`                         // Timeframe (e.g., "1m", "5m", "1h", "1d")
	OpenTime      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=open_time,json=openTime,proto3" json:"open_time,omitempty"`           // Candle open time
	CloseTime     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=close_time,json=closeTime,proto3" json:"close_time,omitempty"`        // Candle close time
	OpenPrice     string                 `protobuf:"bytes,5,opt,name=open_price,json=openPrice,proto3" json:"open_price,omitempty"`        // Opening price
	HighPrice     string                 `protobuf:"bytes,6,opt,name=high_price,json=highPrice,proto3" json:"high_price,omitempty"`        // Highest price
	LowPrice      string                 `protobuf:"bytes,7,opt,name=low_price,json=lowPrice,proto3" json:"low_price,omitempty"`           // Lowest price
	ClosePrice    string                 `protobuf:"bytes,8,opt,name=close_price,json=closePrice,proto3" json:"close_price,omitempty"`     // Closing price
	Volume        string                 `protobuf:"bytes,9,opt,name=volume,proto3" json:"volume,omitempty"`                               // Base asset volume
	QuoteVolume   string                 `protobuf:"bytes,10,opt,name=quote_volume,json=quoteVolume,proto3" json:"quote_volume,omitempty"` // Quote asset volume
	TradeCount    int32                  `protobuf:"varint,11,opt,name=trade_count,json=tradeCount,proto3" json:"trade_count,omitempty"`   // Number of trades
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Candlestick) Reset() {
	*x = Candlestick{}
	mi := &file_marketdata_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Candlestick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Candlestick) ProtoMessage() {}

func (x *Candlestick) ProtoReflect() protoreflect.Message {
	mi := &file_marketdata_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Candlestick.ProtoReflect.Descriptor instead.
func (*Candlestick) Descriptor() ([]byte, []int) {
	return file_marketdata_proto_rawDescGZIP(), []int{9}
}

func (x *Candlestick) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Candlestick) GetTimeframe() string {
	if x != nil {
		return x.Timeframe
	}
	return ""
}

func (x *Candlestick) GetOpenTime() *timestamppb.Timestamp {
	if x != nil {
		return x.OpenTime
	}
	return nil
}

func (x *Candlestick) GetCloseTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CloseTime
	}
	return nil
}

func (x *Candlestick) GetOpenPrice() string {
	if x != nil {
		return x.OpenPrice
	}
	return ""
}

func (x *Candlestick) GetHighPrice() string {
	if x != nil {
		return x.HighPrice
	}
	return ""
}

func (x *Candlestick) GetLowPrice() string {
	if x != nil {
		return x.LowPrice
	}
	return ""
}

func (x *Candlestick) GetClosePrice() string {
	if x != nil {
		return x.ClosePrice
	}
	return ""
}

func (x *Candlestick) GetVolume() string {
	if x != nil {
		return x.Volume
	}
	return ""
}

func (x *Candlestick) GetQuoteVolume() string {
	if x != nil {
		return x.QuoteVolume
	}
	return ""
}

func (x *Candlestick) GetTradeCount() int32 {
	if x != nil {
		return x.TradeCount
	}
	return 0
}

// Requests historical candlestick data for a symbol and timeframe
type GetCandlesticksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimestampMs   int64                  `protobuf:"varint,101,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	TimestampUs   int64                  `protobuf:"varint,102,opt,name=timestamp_us,json=timestampUs,proto3" json:"timestamp_us,omitempty"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`                        // Trading symbol (e.g., "BTC-USD")
	Timeframe     string                 `protobuf:"bytes,2,opt,name=timeframe,proto3" json:"timeframe,omitempty"`                  // Timeframe (e.g., "1m", "5m", "1h", "1d")
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"` // Start time (optional, defaults to 24h ago)
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`       // End time (optional, defaults to now)
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`                         // Maximum number of candles to return (optional, 0 = no limit)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCandlesticksRequest) Reset() {
	*x = GetCandlesticksRequest{}
	mi := &file_marketdata_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCandlesticksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCandlesticksRequest) ProtoMessage() {}

func (x *GetCandlesticksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marketdata_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCandlesticksRequest.ProtoReflect.Descriptor instead.
func (*GetCandlesticksRequest) Descriptor() ([]byte, []int) {
	return file_marketdata_proto_rawDescGZIP(), []int{10}
}

func (x *GetCandlesticksRequest) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *GetCandlesticksRequest) GetTimestampUs() int64 {
	if x != nil {
		return x.TimestampUs
	}
	return 0
}

func (x *GetCandlesticksRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetCandlesticksRequest) GetTimeframe() string {
	if x != nil {
		return x.Timeframe
	}
	return ""
}

func (x *GetCandlesticksRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *GetCandlesticksRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *GetCandlesticksRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// Returns historical candlestick data for a symbol and timeframe
type GetCandlesticksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimestampMs   int64                  `protobuf:"varint,101,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	TimestampUs   int64                  `protobuf:"varint,102,opt,name=timestamp_us,json=timestampUs,proto3" json:"timestamp_us,omitempty"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`             // Trading symbol
	Timeframe     string                 `protobuf:"bytes,2,opt,name=timeframe,proto3" json:"timeframe,omitempty"`       // Timeframe
	Candlesticks  []*Candlestick         `protobuf:"bytes,3,rep,name=candlesticks,proto3" json:"candlesticks,omitempty"` // List of candlesticks (newest first)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCandlesticksResponse) Reset() {
	*x = GetCandlesticksResponse{}
	mi := &file_marketdata_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCandlesticksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCandlesticksResponse) ProtoMessage() {}

func (x *GetCandlesticksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marketdata_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCandlesticksResponse.ProtoReflect.Descriptor instead.
func (*GetCandlesticksResponse) Descriptor() ([]byte, []int) {
	return file_marketdata_proto_rawDescGZIP(), []int{11}
}

func (x *GetCandlesticksResponse) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *GetCandlesticksResponse) GetTimestampUs() int64 {
	if x != nil {
		return x.TimestampUs
	}
	return 0
}

func (x *GetCandlesticksResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetCandlesticksResponse) GetTimeframe() string {
	if x != nil {
		return x.Timeframe
	}
	return ""
}

func (x *GetCandlesticksResponse) GetCandlesticks() []*Candlestick {
	if x != nil {
		return x.Candlesticks
	}
	return nil
}

// TriggerBackfillRequest triggers historical candle backfill from Coinmetrics
type TriggerBackfillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimestampMs   int64                  `protobuf:"varint,101,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	TimestampUs   int64                  `protobuf:"varint,102,opt,name=timestamp_us,json=timestampUs,proto3" json:"timestamp_us,omitempty"`
	Symbols       []string               `protobuf:"bytes,1,rep,name=symbols,proto3" json:"symbols,omitempty"` // Optional: specific symbol to backfill (empty = all active markets)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerBackfillRequest) Reset() {
	*x = TriggerBackfillRequest{}
	mi := &file_marketdata_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerBackfillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerBackfillRequest) ProtoMessage() {}

func (x *TriggerBackfillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marketdata_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerBackfillRequest.ProtoReflect.Descriptor instead.
func (*TriggerBackfillRequest) Descriptor() ([]byte, []int) {
	return file_marketdata_proto_rawDescGZIP(), []int{12}
}

func (x *TriggerBackfillRequest) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *TriggerBackfillRequest) GetTimestampUs() int64 {
	if x != nil {
		return x.TimestampUs
	}
	return 0
}

func (x *TriggerBackfillRequest) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

// TriggerBackfillResponse returns the result of the backfill trigger
type TriggerBackfillResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimestampMs   int64                  `protobuf:"varint,101,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	TimestampUs   int64                  `protobuf:"varint,102,opt,name=timestamp_us,json=timestampUs,proto3" json:"timestamp_us,omitempty"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`                            // Human-readable status message
	SymbolQueue   []string               `protobuf:"bytes,2,rep,name=symbol_queue,json=symbolQueue,proto3" json:"symbol_queue,omitempty"` // Number of symbols queued for backfill
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerBackfillResponse) Reset() {
	*x = TriggerBackfillResponse{}
	mi := &file_marketdata_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerBackfillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerBackfillResponse) ProtoMessage() {}

func (x *TriggerBackfillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marketdata_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerBackfillResponse.ProtoReflect.Descriptor instead.
func (*TriggerBackfillResponse) Descriptor() ([]byte, []int) {
	return file_marketdata_proto_rawDescGZIP(), []int{13}
}

func (x *TriggerBackfillResponse) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *TriggerBackfillResponse) GetTimestampUs() int64 {
	if x != nil {
		return x.TimestampUs
	}
	return 0
}

func (x *TriggerBackfillResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TriggerBackfillResponse) GetSymbolQueue() []string {
	if x != nil {
		return x.SymbolQueue
	}
	return nil
}

var File_marketdata_proto protoreflect.FileDescriptor

const file_marketdata_proto_rawDesc = "" +
	"\n" +
	"\x10marketdata.proto\x12 synthetix.v4_offchain.marketdata\x1a\x1fgoogle/protobuf/timestamp.proto\">\n" +
	"\n" +
	"PriceLevel\x12\x14\n" +
	"\x05price\x18\x01 \x01(\tR\x05price\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\tR\bquantity\"x\n" +
	"\x18OrderbookSnapshotRequest\x12!\n" +
	"\ftimestamp_ms\x18e \x01(\x03R\vtimestampMs\x12!\n" +
	"\ftimestamp_us\x18f \x01(\x03R\vtimestampUs\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\"\xfd\x01\n" +
	"\x19OrderbookSnapshotResponse\x12!\n" +
	"\ftimestamp_ms\x18e \x01(\x03R\vtimestampMs\x12!\n" +
	"\ftimestamp_us\x18f \x01(\x03R\vtimestampUs\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12@\n" +
	"\x04bids\x18\x02 \x03(\v2,.synthetix.v4_offchain.marketdata.PriceLevelR\x04bids\x12@\n" +
	"\x04asks\x18\x03 \x03(\v2,.synthetix.v4_offchain.marketdata.PriceLevelR\x04asks\"\x8b\x01\n" +
	"\x15OrderbookDepthRequest\x12!\n" +
	"\ftimestamp_ms\x18e \x01(\x03R\vtimestampMs\x12!\n" +
	"\ftimestamp_us\x18f \x01(\x03R\vtimestampUs\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\xfa\x01\n" +
	"\x16OrderbookDepthResponse\x12!\n" +
	"\ftimestamp_ms\x18e \x01(\x03R\vtimestampMs\x12!\n" +
	"\ftimestamp_us\x18f \x01(\x03R\vtimestampUs\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12@\n" +
	"\x04bids\x18\x02 \x03(\v2,.synthetix.v4_offchain.marketdata.PriceLevelR\x04bids\x12@\n" +
	"\x04asks\x18\x03 \x03(\v2,.synthetix.v4_offchain.marketdata.PriceLevelR\x04asks\"q\n" +
	"\x11MarketDataRequest\x12!\n" +
	"\ftimestamp_ms\x18e \x01(\x03R\vtimestampMs\x12!\n" +
	"\ftimestamp_us\x18f \x01(\x03R\vtimestampUs\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\"\x9f\x03\n" +
	"\x12MarketDataResponse\x12!\n" +
	"\ftimestamp_ms\x18e \x01(\x03R\vtimestampMs\x12!\n" +
	"\ftimestamp_us\x18f \x01(\x03R\vtimestampUs\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12$\n" +
	"\x0ebest_bid_price\x18\x02 \x01(\tR\fbestBidPrice\x12$\n" +
	"\x0ebest_ask_price\x18\x03 \x01(\tR\fbestAskPrice\x12*\n" +
	"\x11last_traded_price\x18\x04 \x01(\tR\x0flastTradedPrice\x12D\n" +
	"\x10last_traded_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x0elastTradedTime\x12$\n" +
	"\x0eprev_day_price\x18\x06 \x01(\tR\fprevDayPrice\x12\x1d\n" +
	"\n" +
	"volume_24h\x18\a \x01(\tR\tvolume24h\x12(\n" +
	"\x10quote_volume_24h\x18\b \x01(\tR\x0equoteVolume24h\"y\n" +
	"\x17GetAllMarketDataRequest\x12!\n" +
	"\ftimestamp_ms\x18e \x01(\x03R\vtimestampMs\x12!\n" +
	"\ftimestamp_us\x18f \x01(\x03R\vtimestampUs\x12\x18\n" +
	"\asymbols\x18\x01 \x03(\tR\asymbols\"\xb0\x01\n" +
	"\x18GetAllMarketDataResponse\x12!\n" +
	"\ftimestamp_ms\x18e \x01(\x03R\vtimestampMs\x12!\n" +
	"\ftimestamp_us\x18f \x01(\x03R\vtimestampUs\x12N\n" +
	"\amarkets\x18\x01 \x03(\v24.synthetix.v4_offchain.marketdata.MarketDataResponseR\amarkets\"\x8f\x03\n" +
	"\vCandlestick\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1c\n" +
	"\ttimeframe\x18\x02 \x01(\tR\ttimeframe\x127\n" +
	"\topen_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\bopenTime\x129\n" +
	"\n" +
	"close_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcloseTime\x12\x1d\n" +
	"\n" +
	"open_price\x18\x05 \x01(\tR\topenPrice\x12\x1d\n" +
	"\n" +
	"high_price\x18\x06 \x01(\tR\thighPrice\x12\x1b\n" +
	"\tlow_price\x18\a \x01(\tR\blowPrice\x12\x1f\n" +
	"\vclose_price\x18\b \x01(\tR\n" +
	"closePrice\x12\x16\n" +
	"\x06volume\x18\t \x01(\tR\x06volume\x12!\n" +
	"\fquote_volume\x18\n" +
	" \x01(\tR\vquoteVolume\x12\x1f\n" +
	"\vtrade_count\x18\v \x01(\x05R\n" +
	"tradeCount\"\x9c\x02\n" +
	"\x16GetCandlesticksRequest\x12!\n" +
	"\ftimestamp_ms\x18e \x01(\x03R\vtimestampMs\x12!\n" +
	"\ftimestamp_us\x18f \x01(\x03R\vtimestampUs\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1c\n" +
	"\ttimeframe\x18\x02 \x01(\tR\ttimeframe\x129\n" +
	"\n" +
	"start_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\"\xe8\x01\n" +
	"\x17GetCandlesticksResponse\x12!\n" +
	"\ftimestamp_ms\x18e \x01(\x03R\vtimestampMs\x12!\n" +
	"\ftimestamp_us\x18f \x01(\x03R\vtimestampUs\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1c\n" +
	"\ttimeframe\x18\x02 \x01(\tR\ttimeframe\x12Q\n" +
	"\fcandlesticks\x18\x03 \x03(\v2-.synthetix.v4_offchain.marketdata.CandlestickR\fcandlesticks\"x\n" +
	"\x16TriggerBackfillRequest\x12!\n" +
	"\ftimestamp_ms\x18e \x01(\x03R\vtimestampMs\x12!\n" +
	"\ftimestamp_us\x18f \x01(\x03R\vtimestampUs\x12\x18\n" +
	"\asymbols\x18\x01 \x03(\tR\asymbols\"\x9c\x01\n" +
	"\x17TriggerBackfillResponse\x12!\n" +
	"\ftimestamp_ms\x18e \x01(\x03R\vtimestampMs\x12!\n" +
	"\ftimestamp_us\x18f \x01(\x03R\vtimestampUs\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12!\n" +
	"\fsymbol_queue\x18\x02 \x03(\tR\vsymbolQueue2\xc8\x06\n" +
	"\x11MarketDataService\x12\x8f\x01\n" +
	"\x14GetOrderbookSnapshot\x12:.synthetix.v4_offchain.marketdata.OrderbookSnapshotRequest\x1a;.synthetix.v4_offchain.marketdata.OrderbookSnapshotResponse\x12\x86\x01\n" +
	"\x11GetOrderbookDepth\x127.synthetix.v4_offchain.marketdata.OrderbookDepthRequest\x1a8.synthetix.v4_offchain.marketdata.OrderbookDepthResponse\x12z\n" +
	"\rGetMarketData\x123.synthetix.v4_offchain.marketdata.MarketDataRequest\x1a4.synthetix.v4_offchain.marketdata.MarketDataResponse\x12\x86\x01\n" +
	"\x0fGetCandlesticks\x128.synthetix.v4_offchain.marketdata.GetCandlesticksRequest\x1a9.synthetix.v4_offchain.marketdata.GetCandlesticksResponse\x12\x89\x01\n" +
	"\x10GetAllMarketData\x129.synthetix.v4_offchain.marketdata.GetAllMarketDataRequest\x1a:.synthetix.v4_offchain.marketdata.GetAllMarketDataResponse\x12\x86\x01\n" +
	"\x0fTriggerBackfill\x128.synthetix.v4_offchain.marketdata.TriggerBackfillRequest\x1a9.synthetix.v4_offchain.marketdata.TriggerBackfillResponseB5Z3github.com/Synthetixio/v4-offchain/lib/message/grpcb\x06proto3"

var (
	file_marketdata_proto_rawDescOnce sync.Once
	file_marketdata_proto_rawDescData []byte
)

func file_marketdata_proto_rawDescGZIP() []byte {
	file_marketdata_proto_rawDescOnce.Do(func() {
		file_marketdata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_marketdata_proto_rawDesc), len(file_marketdata_proto_rawDesc)))
	})
	return file_marketdata_proto_rawDescData
}

var file_marketdata_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_marketdata_proto_goTypes = []any{
	(*PriceLevel)(nil),                // 0: synthetix.v4_offchain.marketdata.PriceLevel
	(*OrderbookSnapshotRequest)(nil),  // 1: synthetix.v4_offchain.marketdata.OrderbookSnapshotRequest
	(*OrderbookSnapshotResponse)(nil), // 2: synthetix.v4_offchain.marketdata.OrderbookSnapshotResponse
	(*OrderbookDepthRequest)(nil),     // 3: synthetix.v4_offchain.marketdata.OrderbookDepthRequest
	(*OrderbookDepthResponse)(nil),    // 4: synthetix.v4_offchain.marketdata.OrderbookDepthResponse
	(*MarketDataRequest)(nil),         // 5: synthetix.v4_offchain.marketdata.MarketDataRequest
	(*MarketDataResponse)(nil),        // 6: synthetix.v4_offchain.marketdata.MarketDataResponse
	(*GetAllMarketDataRequest)(nil),   // 7: synthetix.v4_offchain.marketdata.GetAllMarketDataRequest
	(*GetAllMarketDataResponse)(nil),  // 8: synthetix.v4_offchain.marketdata.GetAllMarketDataResponse
	(*Candlestick)(nil),               // 9: synthetix.v4_offchain.marketdata.Candlestick
	(*GetCandlesticksRequest)(nil),    // 10: synthetix.v4_offchain.marketdata.GetCandlesticksRequest
	(*GetCandlesticksResponse)(nil),   // 11: synthetix.v4_offchain.marketdata.GetCandlesticksResponse
	(*TriggerBackfillRequest)(nil),    // 12: synthetix.v4_offchain.marketdata.TriggerBackfillRequest
	(*TriggerBackfillResponse)(nil),   // 13: synthetix.v4_offchain.marketdata.TriggerBackfillResponse
	(*timestamppb.Timestamp)(nil),     // 14: google.protobuf.Timestamp
}
var file_marketdata_proto_depIdxs = []int32{
	0,  // 0: synthetix.v4_offchain.marketdata.OrderbookSnapshotResponse.bids:type_name -> synthetix.v4_offchain.marketdata.PriceLevel
	0,  // 1: synthetix.v4_offchain.marketdata.OrderbookSnapshotResponse.asks:type_name -> synthetix.v4_offchain.marketdata.PriceLevel
	0,  // 2: synthetix.v4_offchain.marketdata.OrderbookDepthResponse.bids:type_name -> synthetix.v4_offchain.marketdata.PriceLevel
	0,  // 3: synthetix.v4_offchain.marketdata.OrderbookDepthResponse.asks:type_name -> synthetix.v4_offchain.marketdata.PriceLevel
	14, // 4: synthetix.v4_offchain.marketdata.MarketDataResponse.last_traded_time:type_name -> google.protobuf.Timestamp
	6,  // 5: synthetix.v4_offchain.marketdata.GetAllMarketDataResponse.markets:type_name -> synthetix.v4_offchain.marketdata.MarketDataResponse
	14, // 6: synthetix.v4_offchain.marketdata.Candlestick.open_time:type_name -> google.protobuf.Timestamp
	14, // 7: synthetix.v4_offchain.marketdata.Candlestick.close_time:type_name -> google.protobuf.Timestamp
	14, // 8: synthetix.v4_offchain.marketdata.GetCandlesticksRequest.start_time:type_name -> google.protobuf.Timestamp
	14, // 9: synthetix.v4_offchain.marketdata.GetCandlesticksRequest.end_time:type_name -> google.protobuf.Timestamp
	9,  // 10: synthetix.v4_offchain.marketdata.GetCandlesticksResponse.candlesticks:type_name -> synthetix.v4_offchain.marketdata.Candlestick
	1,  // 11: synthetix.v4_offchain.marketdata.MarketDataService.GetOrderbookSnapshot:input_type -> synthetix.v4_offchain.marketdata.OrderbookSnapshotRequest
	3,  // 12: synthetix.v4_offchain.marketdata.MarketDataService.GetOrderbookDepth:input_type -> synthetix.v4_offchain.marketdata.OrderbookDepthRequest
	5,  // 13: synthetix.v4_offchain.marketdata.MarketDataService.GetMarketData:input_type -> synthetix.v4_offchain.marketdata.MarketDataRequest
	10, // 14: synthetix.v4_offchain.marketdata.MarketDataService.GetCandlesticks:input_type -> synthetix.v4_offchain.marketdata.GetCandlesticksRequest
	7,  // 15: synthetix.v4_offchain.marketdata.MarketDataService.GetAllMarketData:input_type -> synthetix.v4_offchain.marketdata.GetAllMarketDataRequest
	12, // 16: synthetix.v4_offchain.marketdata.MarketDataService.TriggerBackfill:input_type -> synthetix.v4_offchain.marketdata.TriggerBackfillRequest
	2,  // 17: synthetix.v4_offchain.marketdata.MarketDataService.GetOrderbookSnapshot:output_type -> synthetix.v4_offchain.marketdata.OrderbookSnapshotResponse
	4,  // 18: synthetix.v4_offchain.marketdata.MarketDataService.GetOrderbookDepth:output_type -> synthetix.v4_offchain.marketdata.OrderbookDepthResponse
	6,  // 19: synthetix.v4_offchain.marketdata.MarketDataService.GetMarketData:output_type -> synthetix.v4_offchain.marketdata.MarketDataResponse
	11, // 20: synthetix.v4_offchain.marketdata.MarketDataService.GetCandlesticks:output_type -> synthetix.v4_offchain.marketdata.GetCandlesticksResponse
	8,  // 21: synthetix.v4_offchain.marketdata.MarketDataService.GetAllMarketData:output_type -> synthetix.v4_offchain.marketdata.GetAllMarketDataResponse
	13, // 22: synthetix.v4_offchain.marketdata.MarketDataService.TriggerBackfill:output_type -> synthetix.v4_offchain.marketdata.TriggerBackfillResponse
	17, // [17:23] is the sub-list for method output_type
	11, // [11:17] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_marketdata_proto_init() }
func file_marketdata_proto_init() {
	if File_marketdata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_marketdata_proto_rawDesc), len(file_marketdata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_marketdata_proto_goTypes,
		DependencyIndexes: file_marketdata_proto_depIdxs,
		MessageInfos:      file_marketdata_proto_msgTypes,
	}.Build()
	File_marketdata_proto = out.File
	file_marketdata_proto_goTypes = nil
	file_marketdata_proto_depIdxs = nil
}
