// Proto definition for Synthetix V4-Offchain Market Data Service
// To compile:
// protoc --go_out=. --go-grpc_out=. marketdata.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: marketdata.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MarketDataService_GetOrderbookSnapshot_FullMethodName = "/synthetix.v4_offchain.marketdata.MarketDataService/GetOrderbookSnapshot"
	MarketDataService_GetOrderbookDepth_FullMethodName    = "/synthetix.v4_offchain.marketdata.MarketDataService/GetOrderbookDepth"
	MarketDataService_GetMarketData_FullMethodName        = "/synthetix.v4_offchain.marketdata.MarketDataService/GetMarketData"
	MarketDataService_GetCandlesticks_FullMethodName      = "/synthetix.v4_offchain.marketdata.MarketDataService/GetCandlesticks"
	MarketDataService_GetAllMarketData_FullMethodName     = "/synthetix.v4_offchain.marketdata.MarketDataService/GetAllMarketData"
	MarketDataService_TriggerBackfill_FullMethodName      = "/synthetix.v4_offchain.marketdata.MarketDataService/TriggerBackfill"
)

// MarketDataServiceClient is the client API for MarketDataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Provides market data functionality for orderbooks and price information
type MarketDataServiceClient interface {
	// Retrieves a complete orderbook snapshot for a symbol
	GetOrderbookSnapshot(ctx context.Context, in *OrderbookSnapshotRequest, opts ...grpc.CallOption) (*OrderbookSnapshotResponse, error)
	// Retrieves orderbook depth data with specified limit
	GetOrderbookDepth(ctx context.Context, in *OrderbookDepthRequest, opts ...grpc.CallOption) (*OrderbookDepthResponse, error)
	// Retrieves current market data including best bid/ask and last traded price
	GetMarketData(ctx context.Context, in *MarketDataRequest, opts ...grpc.CallOption) (*MarketDataResponse, error)
	// Retrieves historical candlestick data for a symbol and timeframe
	GetCandlesticks(ctx context.Context, in *GetCandlesticksRequest, opts ...grpc.CallOption) (*GetCandlesticksResponse, error)
	// Retrieves current market data for all requested symbols in a single call
	GetAllMarketData(ctx context.Context, in *GetAllMarketDataRequest, opts ...grpc.CallOption) (*GetAllMarketDataResponse, error)
	// TriggerBackfill triggers historical candle backfill from Coinmetrics.
	// If symbol is provided, backfills only that symbol; otherwise backfills all active markets.
	TriggerBackfill(ctx context.Context, in *TriggerBackfillRequest, opts ...grpc.CallOption) (*TriggerBackfillResponse, error)
}

type marketDataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMarketDataServiceClient(cc grpc.ClientConnInterface) MarketDataServiceClient {
	return &marketDataServiceClient{cc}
}

func (c *marketDataServiceClient) GetOrderbookSnapshot(ctx context.Context, in *OrderbookSnapshotRequest, opts ...grpc.CallOption) (*OrderbookSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderbookSnapshotResponse)
	err := c.cc.Invoke(ctx, MarketDataService_GetOrderbookSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketDataServiceClient) GetOrderbookDepth(ctx context.Context, in *OrderbookDepthRequest, opts ...grpc.CallOption) (*OrderbookDepthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderbookDepthResponse)
	err := c.cc.Invoke(ctx, MarketDataService_GetOrderbookDepth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketDataServiceClient) GetMarketData(ctx context.Context, in *MarketDataRequest, opts ...grpc.CallOption) (*MarketDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarketDataResponse)
	err := c.cc.Invoke(ctx, MarketDataService_GetMarketData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketDataServiceClient) GetCandlesticks(ctx context.Context, in *GetCandlesticksRequest, opts ...grpc.CallOption) (*GetCandlesticksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCandlesticksResponse)
	err := c.cc.Invoke(ctx, MarketDataService_GetCandlesticks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketDataServiceClient) GetAllMarketData(ctx context.Context, in *GetAllMarketDataRequest, opts ...grpc.CallOption) (*GetAllMarketDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllMarketDataResponse)
	err := c.cc.Invoke(ctx, MarketDataService_GetAllMarketData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketDataServiceClient) TriggerBackfill(ctx context.Context, in *TriggerBackfillRequest, opts ...grpc.CallOption) (*TriggerBackfillResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TriggerBackfillResponse)
	err := c.cc.Invoke(ctx, MarketDataService_TriggerBackfill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MarketDataServiceServer is the server API for MarketDataService service.
// All implementations must embed UnimplementedMarketDataServiceServer
// for forward compatibility.
//
// Provides market data functionality for orderbooks and price information
type MarketDataServiceServer interface {
	// Retrieves a complete orderbook snapshot for a symbol
	GetOrderbookSnapshot(context.Context, *OrderbookSnapshotRequest) (*OrderbookSnapshotResponse, error)
	// Retrieves orderbook depth data with specified limit
	GetOrderbookDepth(context.Context, *OrderbookDepthRequest) (*OrderbookDepthResponse, error)
	// Retrieves current market data including best bid/ask and last traded price
	GetMarketData(context.Context, *MarketDataRequest) (*MarketDataResponse, error)
	// Retrieves historical candlestick data for a symbol and timeframe
	GetCandlesticks(context.Context, *GetCandlesticksRequest) (*GetCandlesticksResponse, error)
	// Retrieves current market data for all requested symbols in a single call
	GetAllMarketData(context.Context, *GetAllMarketDataRequest) (*GetAllMarketDataResponse, error)
	// TriggerBackfill triggers historical candle backfill from Coinmetrics.
	// If symbol is provided, backfills only that symbol; otherwise backfills all active markets.
	TriggerBackfill(context.Context, *TriggerBackfillRequest) (*TriggerBackfillResponse, error)
	mustEmbedUnimplementedMarketDataServiceServer()
}

// UnimplementedMarketDataServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMarketDataServiceServer struct{}

func (UnimplementedMarketDataServiceServer) GetOrderbookSnapshot(context.Context, *OrderbookSnapshotRequest) (*OrderbookSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOrderbookSnapshot not implemented")
}
func (UnimplementedMarketDataServiceServer) GetOrderbookDepth(context.Context, *OrderbookDepthRequest) (*OrderbookDepthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOrderbookDepth not implemented")
}
func (UnimplementedMarketDataServiceServer) GetMarketData(context.Context, *MarketDataRequest) (*MarketDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMarketData not implemented")
}
func (UnimplementedMarketDataServiceServer) GetCandlesticks(context.Context, *GetCandlesticksRequest) (*GetCandlesticksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCandlesticks not implemented")
}
func (UnimplementedMarketDataServiceServer) GetAllMarketData(context.Context, *GetAllMarketDataRequest) (*GetAllMarketDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllMarketData not implemented")
}
func (UnimplementedMarketDataServiceServer) TriggerBackfill(context.Context, *TriggerBackfillRequest) (*TriggerBackfillResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TriggerBackfill not implemented")
}
func (UnimplementedMarketDataServiceServer) mustEmbedUnimplementedMarketDataServiceServer() {}
func (UnimplementedMarketDataServiceServer) testEmbeddedByValue()                           {}

// UnsafeMarketDataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MarketDataServiceServer will
// result in compilation errors.
type UnsafeMarketDataServiceServer interface {
	mustEmbedUnimplementedMarketDataServiceServer()
}

func RegisterMarketDataServiceServer(s grpc.ServiceRegistrar, srv MarketDataServiceServer) {
	// If the following call panics, it indicates UnimplementedMarketDataServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MarketDataService_ServiceDesc, srv)
}

func _MarketDataService_GetOrderbookSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderbookSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketDataServiceServer).GetOrderbookSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketDataService_GetOrderbookSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketDataServiceServer).GetOrderbookSnapshot(ctx, req.(*OrderbookSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketDataService_GetOrderbookDepth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderbookDepthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketDataServiceServer).GetOrderbookDepth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketDataService_GetOrderbookDepth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketDataServiceServer).GetOrderbookDepth(ctx, req.(*OrderbookDepthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketDataService_GetMarketData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarketDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketDataServiceServer).GetMarketData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketDataService_GetMarketData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketDataServiceServer).GetMarketData(ctx, req.(*MarketDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketDataService_GetCandlesticks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCandlesticksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketDataServiceServer).GetCandlesticks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketDataService_GetCandlesticks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketDataServiceServer).GetCandlesticks(ctx, req.(*GetCandlesticksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketDataService_GetAllMarketData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllMarketDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketDataServiceServer).GetAllMarketData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketDataService_GetAllMarketData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketDataServiceServer).GetAllMarketData(ctx, req.(*GetAllMarketDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketDataService_TriggerBackfill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerBackfillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketDataServiceServer).TriggerBackfill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketDataService_TriggerBackfill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketDataServiceServer).TriggerBackfill(ctx, req.(*TriggerBackfillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MarketDataService_ServiceDesc is the grpc.ServiceDesc for MarketDataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MarketDataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "synthetix.v4_offchain.marketdata.MarketDataService",
	HandlerType: (*MarketDataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOrderbookSnapshot",
			Handler:    _MarketDataService_GetOrderbookSnapshot_Handler,
		},
		{
			MethodName: "GetOrderbookDepth",
			Handler:    _MarketDataService_GetOrderbookDepth_Handler,
		},
		{
			MethodName: "GetMarketData",
			Handler:    _MarketDataService_GetMarketData_Handler,
		},
		{
			MethodName: "GetCandlesticks",
			Handler:    _MarketDataService_GetCandlesticks_Handler,
		},
		{
			MethodName: "GetAllMarketData",
			Handler:    _MarketDataService_GetAllMarketData_Handler,
		},
		{
			MethodName: "TriggerBackfill",
			Handler:    _MarketDataService_TriggerBackfill_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "marketdata.proto",
}
