// Proto definition for Synthetix V4-Offchain Matching Engine
// To compile:
// protoc --go_out=. --go-grpc_out=. matching.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: matching.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Defines the possible outcomes of a cancel operation
type CancelStatus int32

const (
	CancelStatus_CANCEL_SUCCESS   CancelStatus = 0
	CancelStatus_CANCEL_NOT_FOUND CancelStatus = 1
)

// Enum value maps for CancelStatus.
var (
	CancelStatus_name = map[int32]string{
		0: "CANCEL_SUCCESS",
		1: "CANCEL_NOT_FOUND",
	}
	CancelStatus_value = map[string]int32{
		"CANCEL_SUCCESS":   0,
		"CANCEL_NOT_FOUND": 1,
	}
)

func (x CancelStatus) Enum() *CancelStatus {
	p := new(CancelStatus)
	*p = x
	return p
}

func (x CancelStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CancelStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_matching_proto_enumTypes[0].Descriptor()
}

func (CancelStatus) Type() protoreflect.EnumType {
	return &file_matching_proto_enumTypes[0]
}

func (x CancelStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CancelStatus.Descriptor instead.
func (CancelStatus) EnumDescriptor() ([]byte, []int) {
	return file_matching_proto_rawDescGZIP(), []int{0}
}

// Defines the possible outcomes of a modify operation
type ModifyStatus int32

const (
	ModifyStatus_MODIFY_SUCCESS         ModifyStatus = 0
	ModifyStatus_MODIFY_ORDER_NOT_FOUND ModifyStatus = 1
	ModifyStatus_MODIFY_REJECTED        ModifyStatus = 2 // Modify was rejected (validation or business rule violation)
)

// Enum value maps for ModifyStatus.
var (
	ModifyStatus_name = map[int32]string{
		0: "MODIFY_SUCCESS",
		1: "MODIFY_ORDER_NOT_FOUND",
		2: "MODIFY_REJECTED",
	}
	ModifyStatus_value = map[string]int32{
		"MODIFY_SUCCESS":         0,
		"MODIFY_ORDER_NOT_FOUND": 1,
		"MODIFY_REJECTED":        2,
	}
)

func (x ModifyStatus) Enum() *ModifyStatus {
	p := new(ModifyStatus)
	*p = x
	return p
}

func (x ModifyStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ModifyStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_matching_proto_enumTypes[1].Descriptor()
}

func (ModifyStatus) Type() protoreflect.EnumType {
	return &file_matching_proto_enumTypes[1]
}

func (x ModifyStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ModifyStatus.Descriptor instead.
func (ModifyStatus) EnumDescriptor() ([]byte, []int) {
	return file_matching_proto_rawDescGZIP(), []int{1}
}

// Wraps all order operations for the matching engine
type MatchingOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TmRequestedAt *timestamppb.Timestamp `protobuf:"bytes,103,opt,name=tm_requested_at,json=tmRequestedAt,proto3" json:"tm_requested_at,omitempty"`
	// Unique request ID for correlation
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// The specific order operation
	//
	// Types that are valid to be assigned to Operation:
	//
	//	*MatchingOrderRequest_NewOrder
	//	*MatchingOrderRequest_CancelOrder
	//	*MatchingOrderRequest_ModifyOrder
	Operation     isMatchingOrderRequest_Operation `protobuf_oneof:"operation"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchingOrderRequest) Reset() {
	*x = MatchingOrderRequest{}
	mi := &file_matching_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchingOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchingOrderRequest) ProtoMessage() {}

func (x *MatchingOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_matching_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchingOrderRequest.ProtoReflect.Descriptor instead.
func (*MatchingOrderRequest) Descriptor() ([]byte, []int) {
	return file_matching_proto_rawDescGZIP(), []int{0}
}

func (x *MatchingOrderRequest) GetTmRequestedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TmRequestedAt
	}
	return nil
}

func (x *MatchingOrderRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *MatchingOrderRequest) GetOperation() isMatchingOrderRequest_Operation {
	if x != nil {
		return x.Operation
	}
	return nil
}

func (x *MatchingOrderRequest) GetNewOrder() *MatchingNewOrderRequest {
	if x != nil {
		if x, ok := x.Operation.(*MatchingOrderRequest_NewOrder); ok {
			return x.NewOrder
		}
	}
	return nil
}

func (x *MatchingOrderRequest) GetCancelOrder() *MatchingCancelOrderRequest {
	if x != nil {
		if x, ok := x.Operation.(*MatchingOrderRequest_CancelOrder); ok {
			return x.CancelOrder
		}
	}
	return nil
}

func (x *MatchingOrderRequest) GetModifyOrder() *MatchingModifyOrderRequest {
	if x != nil {
		if x, ok := x.Operation.(*MatchingOrderRequest_ModifyOrder); ok {
			return x.ModifyOrder
		}
	}
	return nil
}

type isMatchingOrderRequest_Operation interface {
	isMatchingOrderRequest_Operation()
}

type MatchingOrderRequest_NewOrder struct {
	NewOrder *MatchingNewOrderRequest `protobuf:"bytes,2,opt,name=new_order,json=newOrder,proto3,oneof"`
}

type MatchingOrderRequest_CancelOrder struct {
	CancelOrder *MatchingCancelOrderRequest `protobuf:"bytes,3,opt,name=cancel_order,json=cancelOrder,proto3,oneof"`
}

type MatchingOrderRequest_ModifyOrder struct {
	ModifyOrder *MatchingModifyOrderRequest `protobuf:"bytes,4,opt,name=modify_order,json=modifyOrder,proto3,oneof"`
}

func (*MatchingOrderRequest_NewOrder) isMatchingOrderRequest_Operation() {}

func (*MatchingOrderRequest_CancelOrder) isMatchingOrderRequest_Operation() {}

func (*MatchingOrderRequest_ModifyOrder) isMatchingOrderRequest_Operation() {}

// Wraps all order responses from the matching engine
type MatchingOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TmRespondedAt *timestamppb.Timestamp `protobuf:"bytes,104,opt,name=tm_responded_at,json=tmRespondedAt,proto3" json:"tm_responded_at,omitempty"`
	// Echo back the request ID
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Whether the operation was successful
	Success bool `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	// Error message if failed
	ErrorMessage *string `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"`
	// Machine-readable error code for programmatic handling
	ErrorCode *string `protobuf:"bytes,7,opt,name=error_code,json=errorCode,proto3,oneof" json:"error_code,omitempty"`
	// The specific response
	//
	// Types that are valid to be assigned to Response:
	//
	//	*MatchingOrderResponse_NewOrder
	//	*MatchingOrderResponse_CancelOrder
	//	*MatchingOrderResponse_ModifyOrder
	Response      isMatchingOrderResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchingOrderResponse) Reset() {
	*x = MatchingOrderResponse{}
	mi := &file_matching_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchingOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchingOrderResponse) ProtoMessage() {}

func (x *MatchingOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_matching_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchingOrderResponse.ProtoReflect.Descriptor instead.
func (*MatchingOrderResponse) Descriptor() ([]byte, []int) {
	return file_matching_proto_rawDescGZIP(), []int{1}
}

func (x *MatchingOrderResponse) GetTmRespondedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TmRespondedAt
	}
	return nil
}

func (x *MatchingOrderResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *MatchingOrderResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MatchingOrderResponse) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

func (x *MatchingOrderResponse) GetErrorCode() string {
	if x != nil && x.ErrorCode != nil {
		return *x.ErrorCode
	}
	return ""
}

func (x *MatchingOrderResponse) GetResponse() isMatchingOrderResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *MatchingOrderResponse) GetNewOrder() *MatchingNewOrderResponse {
	if x != nil {
		if x, ok := x.Response.(*MatchingOrderResponse_NewOrder); ok {
			return x.NewOrder
		}
	}
	return nil
}

func (x *MatchingOrderResponse) GetCancelOrder() *MatchingCancelOrderResponse {
	if x != nil {
		if x, ok := x.Response.(*MatchingOrderResponse_CancelOrder); ok {
			return x.CancelOrder
		}
	}
	return nil
}

func (x *MatchingOrderResponse) GetModifyOrder() *MatchingModifyOrderResponse {
	if x != nil {
		if x, ok := x.Response.(*MatchingOrderResponse_ModifyOrder); ok {
			return x.ModifyOrder
		}
	}
	return nil
}

type isMatchingOrderResponse_Response interface {
	isMatchingOrderResponse_Response()
}

type MatchingOrderResponse_NewOrder struct {
	NewOrder *MatchingNewOrderResponse `protobuf:"bytes,4,opt,name=new_order,json=newOrder,proto3,oneof"`
}

type MatchingOrderResponse_CancelOrder struct {
	CancelOrder *MatchingCancelOrderResponse `protobuf:"bytes,5,opt,name=cancel_order,json=cancelOrder,proto3,oneof"`
}

type MatchingOrderResponse_ModifyOrder struct {
	ModifyOrder *MatchingModifyOrderResponse `protobuf:"bytes,6,opt,name=modify_order,json=modifyOrder,proto3,oneof"`
}

func (*MatchingOrderResponse_NewOrder) isMatchingOrderResponse_Response() {}

func (*MatchingOrderResponse_CancelOrder) isMatchingOrderResponse_Response() {}

func (*MatchingOrderResponse_ModifyOrder) isMatchingOrderResponse_Response() {}

// Represents a matched order execution between a taker and maker
type Fill struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TakerVenueOrderId uint64                 `protobuf:"varint,1,opt,name=taker_venue_order_id,json=takerVenueOrderId,proto3" json:"taker_venue_order_id,omitempty"`
	TakerSubAccountId int64                  `protobuf:"varint,2,opt,name=taker_sub_account_id,json=takerSubAccountId,proto3" json:"taker_sub_account_id,omitempty"`
	MakerVenueOrderId uint64                 `protobuf:"varint,3,opt,name=maker_venue_order_id,json=makerVenueOrderId,proto3" json:"maker_venue_order_id,omitempty"`
	MakerSubAccountId int64                  `protobuf:"varint,4,opt,name=maker_sub_account_id,json=makerSubAccountId,proto3" json:"maker_sub_account_id,omitempty"`
	Quantity          uint64                 `protobuf:"varint,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price             uint64                 `protobuf:"varint,6,opt,name=price,proto3" json:"price,omitempty"`
	Meseq             *uint64                `protobuf:"varint,7,opt,name=meseq,proto3,oneof" json:"meseq,omitempty"` // Authoritative matching-engine sequence for this fill
	Met               *int64                 `protobuf:"varint,8,opt,name=met,proto3,oneof" json:"met,omitempty"`     // Authoritative matching-engine event time (Unix microseconds)
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Fill) Reset() {
	*x = Fill{}
	mi := &file_matching_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Fill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fill) ProtoMessage() {}

func (x *Fill) ProtoReflect() protoreflect.Message {
	mi := &file_matching_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fill.ProtoReflect.Descriptor instead.
func (*Fill) Descriptor() ([]byte, []int) {
	return file_matching_proto_rawDescGZIP(), []int{2}
}

func (x *Fill) GetTakerVenueOrderId() uint64 {
	if x != nil {
		return x.TakerVenueOrderId
	}
	return 0
}

func (x *Fill) GetTakerSubAccountId() int64 {
	if x != nil {
		return x.TakerSubAccountId
	}
	return 0
}

func (x *Fill) GetMakerVenueOrderId() uint64 {
	if x != nil {
		return x.MakerVenueOrderId
	}
	return 0
}

func (x *Fill) GetMakerSubAccountId() int64 {
	if x != nil {
		return x.MakerSubAccountId
	}
	return 0
}

func (x *Fill) GetQuantity() uint64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Fill) GetPrice() uint64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Fill) GetMeseq() uint64 {
	if x != nil && x.Meseq != nil {
		return *x.Meseq
	}
	return 0
}

func (x *Fill) GetMet() int64 {
	if x != nil && x.Met != nil {
		return *x.Met
	}
	return 0
}

// Requests placement of a new order in the matching engine
type MatchingNewOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TmRequestedAt *timestamppb.Timestamp `protobuf:"bytes,103,opt,name=tm_requested_at,json=tmRequestedAt,proto3" json:"tm_requested_at,omitempty"`
	SubAccountId  int64                  `protobuf:"varint,1,opt,name=sub_account_id,json=subAccountId,proto3" json:"sub_account_id,omitempty"`                                                  // The subaccount ID placing the order
	VenueOrderId  uint64                 `protobuf:"varint,2,opt,name=venue_order_id,json=venueOrderId,proto3" json:"venue_order_id,omitempty"`                                                  // The system-generated order ID
	Symbol        string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`                                                                                     // The market identifier, e.g., "BTC-USD"
	Side          Side                   `protobuf:"varint,4,opt,name=side,proto3,enum=synthetix.v4_offchain.common.Side" json:"side,omitempty"`                                                 // The side of the order using enum from common.proto
	Type          OrderType              `protobuf:"varint,5,opt,name=type,proto3,enum=synthetix.v4_offchain.common.OrderType" json:"type,omitempty"`                                            // The type of order using enum from common.proto
	Quantity      uint64                 `protobuf:"varint,6,opt,name=quantity,proto3" json:"quantity,omitempty"`                                                                                // The quantity of the order
	Price         uint64                 `protobuf:"varint,7,opt,name=price,proto3" json:"price,omitempty"`                                                                                      // The limit price. Required for LIMIT orders, must be null for MARKET orders
	TimeInForce   *TimeInForce           `protobuf:"varint,8,opt,name=time_in_force,json=timeInForce,proto3,enum=synthetix.v4_offchain.common.TimeInForce,oneof" json:"time_in_force,omitempty"` // Order lifetime policy using enum from common.proto
	ReduceOnly    *bool                  `protobuf:"varint,9,opt,name=reduce_only,json=reduceOnly,proto3,oneof" json:"reduce_only,omitempty"`                                                    // If true, the order is only accepted if it reduces an existing position
	PostOnly      bool                   `protobuf:"varint,10,opt,name=post_only,json=postOnly,proto3" json:"post_only,omitempty"`
	// Market order price limit (for market orders only)
	// Pre-calculated max/min allowed price to prevent execution at extreme prices during volatile conditions
	// For BUY orders: this is the max allowed fill price (markPrice * (1 + capRatio))
	// For SELL orders: this is the min allowed fill price (markPrice * (1 - floorRatio))
	// Set to 0 to disable validation
	MarketOrderPriceLimit *uint64 `protobuf:"varint,11,opt,name=market_order_price_limit,json=marketOrderPriceLimit,proto3,oneof" json:"market_order_price_limit,omitempty"` // Scaled by market's PriceExponent
	// OI Cap enforcement fields
	IsClosingPosition bool   `protobuf:"varint,12,opt,name=is_closing_position,json=isClosingPosition,proto3" json:"is_closing_position,omitempty"` // True if order reduces an existing position (DirectionCloseLong/CloseShort)
	MarkPrice         uint64 `protobuf:"varint,13,opt,name=mark_price,json=markPrice,proto3" json:"mark_price,omitempty"`                           // Current mark price for OI cap notional calculation (scaled by PriceExponent)
	PositionQuantity  uint64 `protobuf:"varint,14,opt,name=position_quantity,json=positionQuantity,proto3" json:"position_quantity,omitempty"`      // Current position size for flip detection (scaled by QuantityExponent)
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MatchingNewOrderRequest) Reset() {
	*x = MatchingNewOrderRequest{}
	mi := &file_matching_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchingNewOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchingNewOrderRequest) ProtoMessage() {}

func (x *MatchingNewOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_matching_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchingNewOrderRequest.ProtoReflect.Descriptor instead.
func (*MatchingNewOrderRequest) Descriptor() ([]byte, []int) {
	return file_matching_proto_rawDescGZIP(), []int{3}
}

func (x *MatchingNewOrderRequest) GetTmRequestedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TmRequestedAt
	}
	return nil
}

func (x *MatchingNewOrderRequest) GetSubAccountId() int64 {
	if x != nil {
		return x.SubAccountId
	}
	return 0
}

func (x *MatchingNewOrderRequest) GetVenueOrderId() uint64 {
	if x != nil {
		return x.VenueOrderId
	}
	return 0
}

func (x *MatchingNewOrderRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *MatchingNewOrderRequest) GetSide() Side {
	if x != nil {
		return x.Side
	}
	return Side_BUY
}

func (x *MatchingNewOrderRequest) GetType() OrderType {
	if x != nil {
		return x.Type
	}
	return OrderType_LIMIT
}

func (x *MatchingNewOrderRequest) GetQuantity() uint64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *MatchingNewOrderRequest) GetPrice() uint64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *MatchingNewOrderRequest) GetTimeInForce() TimeInForce {
	if x != nil && x.TimeInForce != nil {
		return *x.TimeInForce
	}
	return TimeInForce_GTC
}

func (x *MatchingNewOrderRequest) GetReduceOnly() bool {
	if x != nil && x.ReduceOnly != nil {
		return *x.ReduceOnly
	}
	return false
}

func (x *MatchingNewOrderRequest) GetPostOnly() bool {
	if x != nil {
		return x.PostOnly
	}
	return false
}

func (x *MatchingNewOrderRequest) GetMarketOrderPriceLimit() uint64 {
	if x != nil && x.MarketOrderPriceLimit != nil {
		return *x.MarketOrderPriceLimit
	}
	return 0
}

func (x *MatchingNewOrderRequest) GetIsClosingPosition() bool {
	if x != nil {
		return x.IsClosingPosition
	}
	return false
}

func (x *MatchingNewOrderRequest) GetMarkPrice() uint64 {
	if x != nil {
		return x.MarkPrice
	}
	return 0
}

func (x *MatchingNewOrderRequest) GetPositionQuantity() uint64 {
	if x != nil {
		return x.PositionQuantity
	}
	return 0
}

// Returns the result of a new order placement including fills
type MatchingNewOrderResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TmRespondedAt     *timestamppb.Timestamp `protobuf:"bytes,104,opt,name=tm_responded_at,json=tmRespondedAt,proto3" json:"tm_responded_at,omitempty"`
	SubAccountId      int64                  `protobuf:"varint,1,opt,name=sub_account_id,json=subAccountId,proto3" json:"sub_account_id,omitempty"`       // The subaccount ID placing the order
	VenueOrderId      uint64                 `protobuf:"varint,2,opt,name=venue_order_id,json=venueOrderId,proto3" json:"venue_order_id,omitempty"`       // The system-generated order ID
	Symbol            string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`                                          // The market of the order
	Side              Side                   `protobuf:"varint,4,opt,name=side,proto3,enum=synthetix.v4_offchain.common.Side" json:"side,omitempty"`      // The side of the order using enum from common.proto
	Type              OrderType              `protobuf:"varint,5,opt,name=type,proto3,enum=synthetix.v4_offchain.common.OrderType" json:"type,omitempty"` // The type of the order using enum from common.proto
	Quantity          uint64                 `protobuf:"varint,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price             uint64                 `protobuf:"varint,7,opt,name=price,proto3" json:"price,omitempty"`                                                  // The limit price of the order (null for market orders)
	Status            OrderStatus            `protobuf:"varint,8,opt,name=status,proto3,enum=synthetix.v4_offchain.common.OrderStatus" json:"status,omitempty"`  // The status of the order
	RemainingQuantity uint64                 `protobuf:"varint,9,opt,name=remaining_quantity,json=remainingQuantity,proto3" json:"remaining_quantity,omitempty"` // The size of the order that is not yet filled
	// Enhanced fields for detailed execution information
	Fills                 []*Fill                `protobuf:"bytes,10,rep,name=fills,proto3" json:"fills,omitempty"`                                                                          // All fills that occurred during order execution
	CanceledVenueOrderIds []uint64               `protobuf:"varint,11,rep,packed,name=canceled_venue_order_ids,json=canceledVenueOrderIds,proto3" json:"canceled_venue_order_ids,omitempty"` // IDs of orders that were canceled during execution
	PlacedAt              *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=placed_at,json=placedAt,proto3" json:"placed_at,omitempty"`                                                    // The timestamp of when the order was accepted by the system (ISO 8601)
	TradedAt              *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=traded_at,json=tradedAt,proto3" json:"traded_at,omitempty"`                                                    // The timestamp of when the order was accepted by the system (ISO 8601)
	RejectedAt            *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=rejected_at,json=rejectedAt,proto3" json:"rejected_at,omitempty"`                                              // The timestamp of when the order was accepted by the system (ISO 8601)
	Meseq                 *uint64                `protobuf:"varint,15,opt,name=meseq,proto3,oneof" json:"meseq,omitempty"`                                                                   // Authoritative matching-engine sequence for this response
	Met                   *int64                 `protobuf:"varint,16,opt,name=met,proto3,oneof" json:"met,omitempty"`                                                                       // Authoritative matching-engine event time (Unix microseconds)
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *MatchingNewOrderResponse) Reset() {
	*x = MatchingNewOrderResponse{}
	mi := &file_matching_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchingNewOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchingNewOrderResponse) ProtoMessage() {}

func (x *MatchingNewOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_matching_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchingNewOrderResponse.ProtoReflect.Descriptor instead.
func (*MatchingNewOrderResponse) Descriptor() ([]byte, []int) {
	return file_matching_proto_rawDescGZIP(), []int{4}
}

func (x *MatchingNewOrderResponse) GetTmRespondedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TmRespondedAt
	}
	return nil
}

func (x *MatchingNewOrderResponse) GetSubAccountId() int64 {
	if x != nil {
		return x.SubAccountId
	}
	return 0
}

func (x *MatchingNewOrderResponse) GetVenueOrderId() uint64 {
	if x != nil {
		return x.VenueOrderId
	}
	return 0
}

func (x *MatchingNewOrderResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *MatchingNewOrderResponse) GetSide() Side {
	if x != nil {
		return x.Side
	}
	return Side_BUY
}

func (x *MatchingNewOrderResponse) GetType() OrderType {
	if x != nil {
		return x.Type
	}
	return OrderType_LIMIT
}

func (x *MatchingNewOrderResponse) GetQuantity() uint64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *MatchingNewOrderResponse) GetPrice() uint64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *MatchingNewOrderResponse) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_UNKNOWN
}

func (x *MatchingNewOrderResponse) GetRemainingQuantity() uint64 {
	if x != nil {
		return x.RemainingQuantity
	}
	return 0
}

func (x *MatchingNewOrderResponse) GetFills() []*Fill {
	if x != nil {
		return x.Fills
	}
	return nil
}

func (x *MatchingNewOrderResponse) GetCanceledVenueOrderIds() []uint64 {
	if x != nil {
		return x.CanceledVenueOrderIds
	}
	return nil
}

func (x *MatchingNewOrderResponse) GetPlacedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PlacedAt
	}
	return nil
}

func (x *MatchingNewOrderResponse) GetTradedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TradedAt
	}
	return nil
}

func (x *MatchingNewOrderResponse) GetRejectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RejectedAt
	}
	return nil
}

func (x *MatchingNewOrderResponse) GetMeseq() uint64 {
	if x != nil && x.Meseq != nil {
		return *x.Meseq
	}
	return 0
}

func (x *MatchingNewOrderResponse) GetMet() int64 {
	if x != nil && x.Met != nil {
		return *x.Met
	}
	return 0
}

// Requests cancellation of an order in the matching engine
type MatchingCancelOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TmRequestedAt *timestamppb.Timestamp `protobuf:"bytes,103,opt,name=tm_requested_at,json=tmRequestedAt,proto3" json:"tm_requested_at,omitempty"`
	SubAccountId  int64                  `protobuf:"varint,1,opt,name=sub_account_id,json=subAccountId,proto3" json:"sub_account_id,omitempty"` // The subaccount ID placing the order
	VenueOrderId  uint64                 `protobuf:"varint,2,opt,name=venue_order_id,json=venueOrderId,proto3" json:"venue_order_id,omitempty"` // The system-generated order ID
	Symbol        string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`                                    // The market identifier. Helps route the request and provides context
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchingCancelOrderRequest) Reset() {
	*x = MatchingCancelOrderRequest{}
	mi := &file_matching_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchingCancelOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchingCancelOrderRequest) ProtoMessage() {}

func (x *MatchingCancelOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_matching_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchingCancelOrderRequest.ProtoReflect.Descriptor instead.
func (*MatchingCancelOrderRequest) Descriptor() ([]byte, []int) {
	return file_matching_proto_rawDescGZIP(), []int{5}
}

func (x *MatchingCancelOrderRequest) GetTmRequestedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TmRequestedAt
	}
	return nil
}

func (x *MatchingCancelOrderRequest) GetSubAccountId() int64 {
	if x != nil {
		return x.SubAccountId
	}
	return 0
}

func (x *MatchingCancelOrderRequest) GetVenueOrderId() uint64 {
	if x != nil {
		return x.VenueOrderId
	}
	return 0
}

func (x *MatchingCancelOrderRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

// Returns the result of an order cancellation
type MatchingCancelOrderResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TmRespondedAt     *timestamppb.Timestamp `protobuf:"bytes,104,opt,name=tm_responded_at,json=tmRespondedAt,proto3" json:"tm_responded_at,omitempty"`
	SubAccountId      int64                  `protobuf:"varint,1,opt,name=sub_account_id,json=subAccountId,proto3" json:"sub_account_id,omitempty"`                // The subaccount ID placing the order
	VenueOrderId      uint64                 `protobuf:"varint,2,opt,name=venue_order_id,json=venueOrderId,proto3" json:"venue_order_id,omitempty"`                // The system-generated order ID
	Symbol            string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`                                                   // The market identifier. Helps route the request and provides context
	Status            CancelStatus           `protobuf:"varint,4,opt,name=status,proto3,enum=synthetix.v4_offchain.matching.CancelStatus" json:"status,omitempty"` // The status of the cancel operation
	CancelledQuantity uint64                 `protobuf:"varint,5,opt,name=cancelled_quantity,json=cancelledQuantity,proto3" json:"cancelled_quantity,omitempty"`   // The quantity of the order that was cancelled
	CancelledAt       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=cancelled_at,json=cancelledAt,proto3" json:"cancelled_at,omitempty"`                      // The timestamp when the order was cancelled (ISO 8601)
	Meseq             *uint64                `protobuf:"varint,7,opt,name=meseq,proto3,oneof" json:"meseq,omitempty"`                                              // Authoritative matching-engine sequence for this response
	Met               *int64                 `protobuf:"varint,8,opt,name=met,proto3,oneof" json:"met,omitempty"`                                                  // Authoritative matching-engine event time (Unix microseconds)
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MatchingCancelOrderResponse) Reset() {
	*x = MatchingCancelOrderResponse{}
	mi := &file_matching_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchingCancelOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchingCancelOrderResponse) ProtoMessage() {}

func (x *MatchingCancelOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_matching_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchingCancelOrderResponse.ProtoReflect.Descriptor instead.
func (*MatchingCancelOrderResponse) Descriptor() ([]byte, []int) {
	return file_matching_proto_rawDescGZIP(), []int{6}
}

func (x *MatchingCancelOrderResponse) GetTmRespondedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TmRespondedAt
	}
	return nil
}

func (x *MatchingCancelOrderResponse) GetSubAccountId() int64 {
	if x != nil {
		return x.SubAccountId
	}
	return 0
}

func (x *MatchingCancelOrderResponse) GetVenueOrderId() uint64 {
	if x != nil {
		return x.VenueOrderId
	}
	return 0
}

func (x *MatchingCancelOrderResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *MatchingCancelOrderResponse) GetStatus() CancelStatus {
	if x != nil {
		return x.Status
	}
	return CancelStatus_CANCEL_SUCCESS
}

func (x *MatchingCancelOrderResponse) GetCancelledQuantity() uint64 {
	if x != nil {
		return x.CancelledQuantity
	}
	return 0
}

func (x *MatchingCancelOrderResponse) GetCancelledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CancelledAt
	}
	return nil
}

func (x *MatchingCancelOrderResponse) GetMeseq() uint64 {
	if x != nil && x.Meseq != nil {
		return *x.Meseq
	}
	return 0
}

func (x *MatchingCancelOrderResponse) GetMet() int64 {
	if x != nil && x.Met != nil {
		return *x.Met
	}
	return 0
}

// Requests modification of an existing order in the matching engine
type MatchingModifyOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TmRequestedAt *timestamppb.Timestamp `protobuf:"bytes,103,opt,name=tm_requested_at,json=tmRequestedAt,proto3" json:"tm_requested_at,omitempty"`
	SubAccountId  int64                  `protobuf:"varint,1,opt,name=sub_account_id,json=subAccountId,proto3" json:"sub_account_id,omitempty"`       // The subaccount ID placing the order
	VenueOrderId  uint64                 `protobuf:"varint,2,opt,name=venue_order_id,json=venueOrderId,proto3" json:"venue_order_id,omitempty"`       // The system-generated order ID
	Symbol        string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`                                          // The market identifier, e.g., "BTC-USD"
	Side          Side                   `protobuf:"varint,4,opt,name=side,proto3,enum=synthetix.v4_offchain.common.Side" json:"side,omitempty"`      // The side of the order using enum from common.proto
	Type          OrderType              `protobuf:"varint,5,opt,name=type,proto3,enum=synthetix.v4_offchain.common.OrderType" json:"type,omitempty"` // The type of order using enum from common.proto
	Quantity      uint64                 `protobuf:"varint,6,opt,name=quantity,proto3" json:"quantity,omitempty"`                                     // The quantity of the order
	Price         uint64                 `protobuf:"varint,7,opt,name=price,proto3" json:"price,omitempty"`                                           // The limit price. Required for LIMIT orders, must be null for MARKET orders
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchingModifyOrderRequest) Reset() {
	*x = MatchingModifyOrderRequest{}
	mi := &file_matching_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchingModifyOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchingModifyOrderRequest) ProtoMessage() {}

func (x *MatchingModifyOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_matching_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchingModifyOrderRequest.ProtoReflect.Descriptor instead.
func (*MatchingModifyOrderRequest) Descriptor() ([]byte, []int) {
	return file_matching_proto_rawDescGZIP(), []int{7}
}

func (x *MatchingModifyOrderRequest) GetTmRequestedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TmRequestedAt
	}
	return nil
}

func (x *MatchingModifyOrderRequest) GetSubAccountId() int64 {
	if x != nil {
		return x.SubAccountId
	}
	return 0
}

func (x *MatchingModifyOrderRequest) GetVenueOrderId() uint64 {
	if x != nil {
		return x.VenueOrderId
	}
	return 0
}

func (x *MatchingModifyOrderRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *MatchingModifyOrderRequest) GetSide() Side {
	if x != nil {
		return x.Side
	}
	return Side_BUY
}

func (x *MatchingModifyOrderRequest) GetType() OrderType {
	if x != nil {
		return x.Type
	}
	return OrderType_LIMIT
}

func (x *MatchingModifyOrderRequest) GetQuantity() uint64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *MatchingModifyOrderRequest) GetPrice() uint64 {
	if x != nil {
		return x.Price
	}
	return 0
}

// Returns the result of an order modification (cancel/replace)
type MatchingModifyOrderResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TmRespondedAt     *timestamppb.Timestamp `protobuf:"bytes,104,opt,name=tm_responded_at,json=tmRespondedAt,proto3" json:"tm_responded_at,omitempty"`
	SubAccountId      int64                  `protobuf:"varint,1,opt,name=sub_account_id,json=subAccountId,proto3" json:"sub_account_id,omitempty"`                // The subaccount ID placing the order
	VenueOrderId      uint64                 `protobuf:"varint,2,opt,name=venue_order_id,json=venueOrderId,proto3" json:"venue_order_id,omitempty"`                // The system-generated order ID
	Symbol            string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`                                                   // The market of the order
	Side              Side                   `protobuf:"varint,4,opt,name=side,proto3,enum=synthetix.v4_offchain.common.Side" json:"side,omitempty"`               // The side of the order using enum from common.proto
	Type              OrderType              `protobuf:"varint,5,opt,name=type,proto3,enum=synthetix.v4_offchain.common.OrderType" json:"type,omitempty"`          // The type of the order using enum from common.proto
	OrgQuantity       uint64                 `protobuf:"varint,6,opt,name=org_quantity,json=orgQuantity,proto3" json:"org_quantity,omitempty"`                     // The original size of the order
	NewQuantity       uint64                 `protobuf:"varint,7,opt,name=new_quantity,json=newQuantity,proto3" json:"new_quantity,omitempty"`                     // The new size of the order
	Price             uint64                 `protobuf:"varint,8,opt,name=price,proto3" json:"price,omitempty"`                                                    // The price of the order
	Status            ModifyStatus           `protobuf:"varint,9,opt,name=status,proto3,enum=synthetix.v4_offchain.matching.ModifyStatus" json:"status,omitempty"` // The status of the modify operation
	RemainingQuantity uint64                 `protobuf:"varint,10,opt,name=remaining_quantity,json=remainingQuantity,proto3" json:"remaining_quantity,omitempty"`  // The size of the new order that is not yet filled
	ModifiedAt        *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=modified_at,json=modifiedAt,proto3" json:"modified_at,omitempty"`                        // The timestamp when the order was modified (ISO 8601)
	// Enhanced fields for detailed execution information
	Fills                 []*Fill                `protobuf:"bytes,12,rep,name=fills,proto3" json:"fills,omitempty"`                                                                          // All fills that occurred during order modification
	CanceledVenueOrderIds []uint64               `protobuf:"varint,13,rep,packed,name=canceled_venue_order_ids,json=canceledVenueOrderIds,proto3" json:"canceled_venue_order_ids,omitempty"` // IDs of orders that were canceled during modification
	TradedAt              *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=traded_at,json=tradedAt,proto3" json:"traded_at,omitempty"`
	Meseq                 *uint64                `protobuf:"varint,15,opt,name=meseq,proto3,oneof" json:"meseq,omitempty"`                      // Authoritative matching-engine sequence for this response
	Met                   *int64                 `protobuf:"varint,16,opt,name=met,proto3,oneof" json:"met,omitempty"`                          // Authoritative matching-engine event time (Unix microseconds)
	RejectedAt            *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=rejected_at,json=rejectedAt,proto3" json:"rejected_at,omitempty"` // The timestamp of when the modify was rejected
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *MatchingModifyOrderResponse) Reset() {
	*x = MatchingModifyOrderResponse{}
	mi := &file_matching_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchingModifyOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchingModifyOrderResponse) ProtoMessage() {}

func (x *MatchingModifyOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_matching_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchingModifyOrderResponse.ProtoReflect.Descriptor instead.
func (*MatchingModifyOrderResponse) Descriptor() ([]byte, []int) {
	return file_matching_proto_rawDescGZIP(), []int{8}
}

func (x *MatchingModifyOrderResponse) GetTmRespondedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TmRespondedAt
	}
	return nil
}

func (x *MatchingModifyOrderResponse) GetSubAccountId() int64 {
	if x != nil {
		return x.SubAccountId
	}
	return 0
}

func (x *MatchingModifyOrderResponse) GetVenueOrderId() uint64 {
	if x != nil {
		return x.VenueOrderId
	}
	return 0
}

func (x *MatchingModifyOrderResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *MatchingModifyOrderResponse) GetSide() Side {
	if x != nil {
		return x.Side
	}
	return Side_BUY
}

func (x *MatchingModifyOrderResponse) GetType() OrderType {
	if x != nil {
		return x.Type
	}
	return OrderType_LIMIT
}

func (x *MatchingModifyOrderResponse) GetOrgQuantity() uint64 {
	if x != nil {
		return x.OrgQuantity
	}
	return 0
}

func (x *MatchingModifyOrderResponse) GetNewQuantity() uint64 {
	if x != nil {
		return x.NewQuantity
	}
	return 0
}

func (x *MatchingModifyOrderResponse) GetPrice() uint64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *MatchingModifyOrderResponse) GetStatus() ModifyStatus {
	if x != nil {
		return x.Status
	}
	return ModifyStatus_MODIFY_SUCCESS
}

func (x *MatchingModifyOrderResponse) GetRemainingQuantity() uint64 {
	if x != nil {
		return x.RemainingQuantity
	}
	return 0
}

func (x *MatchingModifyOrderResponse) GetModifiedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ModifiedAt
	}
	return nil
}

func (x *MatchingModifyOrderResponse) GetFills() []*Fill {
	if x != nil {
		return x.Fills
	}
	return nil
}

func (x *MatchingModifyOrderResponse) GetCanceledVenueOrderIds() []uint64 {
	if x != nil {
		return x.CanceledVenueOrderIds
	}
	return nil
}

func (x *MatchingModifyOrderResponse) GetTradedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TradedAt
	}
	return nil
}

func (x *MatchingModifyOrderResponse) GetMeseq() uint64 {
	if x != nil && x.Meseq != nil {
		return *x.Meseq
	}
	return 0
}

func (x *MatchingModifyOrderResponse) GetMet() int64 {
	if x != nil && x.Met != nil {
		return *x.Met
	}
	return 0
}

func (x *MatchingModifyOrderResponse) GetRejectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RejectedAt
	}
	return nil
}

var File_matching_proto protoreflect.FileDescriptor

const file_matching_proto_rawDesc = "" +
	"\n" +
	"\x0ematching.proto\x12\x1esynthetix.v4_offchain.matching\x1a\fcommon.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb2\x03\n" +
	"\x14MatchingOrderRequest\x12B\n" +
	"\x0ftm_requested_at\x18g \x01(\v2\x1a.google.protobuf.TimestampR\rtmRequestedAt\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12V\n" +
	"\tnew_order\x18\x02 \x01(\v27.synthetix.v4_offchain.matching.MatchingNewOrderRequestH\x00R\bnewOrder\x12_\n" +
	"\fcancel_order\x18\x03 \x01(\v2:.synthetix.v4_offchain.matching.MatchingCancelOrderRequestH\x00R\vcancelOrder\x12_\n" +
	"\fmodify_order\x18\x04 \x01(\v2:.synthetix.v4_offchain.matching.MatchingModifyOrderRequestH\x00R\vmodifyOrderB\v\n" +
	"\toperationJ\x04\be\x10fJ\x04\bf\x10gJ\x04\bh\x10i\"\xbe\x04\n" +
	"\x15MatchingOrderResponse\x12B\n" +
	"\x0ftm_responded_at\x18h \x01(\v2\x1a.google.protobuf.TimestampR\rtmRespondedAt\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12(\n" +
	"\rerror_message\x18\x03 \x01(\tH\x01R\ferrorMessage\x88\x01\x01\x12\"\n" +
	"\n" +
	"error_code\x18\a \x01(\tH\x02R\terrorCode\x88\x01\x01\x12W\n" +
	"\tnew_order\x18\x04 \x01(\v28.synthetix.v4_offchain.matching.MatchingNewOrderResponseH\x00R\bnewOrder\x12`\n" +
	"\fcancel_order\x18\x05 \x01(\v2;.synthetix.v4_offchain.matching.MatchingCancelOrderResponseH\x00R\vcancelOrder\x12`\n" +
	"\fmodify_order\x18\x06 \x01(\v2;.synthetix.v4_offchain.matching.MatchingModifyOrderResponseH\x00R\vmodifyOrderB\n" +
	"\n" +
	"\bresponseB\x10\n" +
	"\x0e_error_messageB\r\n" +
	"\v_error_codeJ\x04\be\x10fJ\x04\bf\x10gJ\x04\bg\x10h\"\xc0\x02\n" +
	"\x04Fill\x12/\n" +
	"\x14taker_venue_order_id\x18\x01 \x01(\x04R\x11takerVenueOrderId\x12/\n" +
	"\x14taker_sub_account_id\x18\x02 \x01(\x03R\x11takerSubAccountId\x12/\n" +
	"\x14maker_venue_order_id\x18\x03 \x01(\x04R\x11makerVenueOrderId\x12/\n" +
	"\x14maker_sub_account_id\x18\x04 \x01(\x03R\x11makerSubAccountId\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\x04R\bquantity\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x04R\x05price\x12\x19\n" +
	"\x05meseq\x18\a \x01(\x04H\x00R\x05meseq\x88\x01\x01\x12\x15\n" +
	"\x03met\x18\b \x01(\x03H\x01R\x03met\x88\x01\x01B\b\n" +
	"\x06_meseqB\x06\n" +
	"\x04_met\"\x8a\x06\n" +
	"\x17MatchingNewOrderRequest\x12B\n" +
	"\x0ftm_requested_at\x18g \x01(\v2\x1a.google.protobuf.TimestampR\rtmRequestedAt\x12$\n" +
	"\x0esub_account_id\x18\x01 \x01(\x03R\fsubAccountId\x12$\n" +
	"\x0evenue_order_id\x18\x02 \x01(\x04R\fvenueOrderId\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x126\n" +
	"\x04side\x18\x04 \x01(\x0e2\".synthetix.v4_offchain.common.SideR\x04side\x12;\n" +
	"\x04type\x18\x05 \x01(\x0e2'.synthetix.v4_offchain.common.OrderTypeR\x04type\x12\x1a\n" +
	"\bquantity\x18\x06 \x01(\x04R\bquantity\x12\x14\n" +
	"\x05price\x18\a \x01(\x04R\x05price\x12R\n" +
	"\rtime_in_force\x18\b \x01(\x0e2).synthetix.v4_offchain.common.TimeInForceH\x00R\vtimeInForce\x88\x01\x01\x12$\n" +
	"\vreduce_only\x18\t \x01(\bH\x01R\n" +
	"reduceOnly\x88\x01\x01\x12\x1b\n" +
	"\tpost_only\x18\n" +
	" \x01(\bR\bpostOnly\x12<\n" +
	"\x18market_order_price_limit\x18\v \x01(\x04H\x02R\x15marketOrderPriceLimit\x88\x01\x01\x12.\n" +
	"\x13is_closing_position\x18\f \x01(\bR\x11isClosingPosition\x12\x1d\n" +
	"\n" +
	"mark_price\x18\r \x01(\x04R\tmarkPrice\x12+\n" +
	"\x11position_quantity\x18\x0e \x01(\x04R\x10positionQuantityB\x10\n" +
	"\x0e_time_in_forceB\x0e\n" +
	"\f_reduce_onlyB\x1b\n" +
	"\x19_market_order_price_limitJ\x04\be\x10fJ\x04\bf\x10gJ\x04\bh\x10i\"\xd5\x06\n" +
	"\x18MatchingNewOrderResponse\x12B\n" +
	"\x0ftm_responded_at\x18h \x01(\v2\x1a.google.protobuf.TimestampR\rtmRespondedAt\x12$\n" +
	"\x0esub_account_id\x18\x01 \x01(\x03R\fsubAccountId\x12$\n" +
	"\x0evenue_order_id\x18\x02 \x01(\x04R\fvenueOrderId\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x126\n" +
	"\x04side\x18\x04 \x01(\x0e2\".synthetix.v4_offchain.common.SideR\x04side\x12;\n" +
	"\x04type\x18\x05 \x01(\x0e2'.synthetix.v4_offchain.common.OrderTypeR\x04type\x12\x1a\n" +
	"\bquantity\x18\x06 \x01(\x04R\bquantity\x12\x14\n" +
	"\x05price\x18\a \x01(\x04R\x05price\x12A\n" +
	"\x06status\x18\b \x01(\x0e2).synthetix.v4_offchain.common.OrderStatusR\x06status\x12-\n" +
	"\x12remaining_quantity\x18\t \x01(\x04R\x11remainingQuantity\x12:\n" +
	"\x05fills\x18\n" +
	" \x03(\v2$.synthetix.v4_offchain.matching.FillR\x05fills\x127\n" +
	"\x18canceled_venue_order_ids\x18\v \x03(\x04R\x15canceledVenueOrderIds\x127\n" +
	"\tplaced_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\bplacedAt\x127\n" +
	"\ttraded_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\btradedAt\x12;\n" +
	"\vrejected_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"rejectedAt\x12\x19\n" +
	"\x05meseq\x18\x0f \x01(\x04H\x00R\x05meseq\x88\x01\x01\x12\x15\n" +
	"\x03met\x18\x10 \x01(\x03H\x01R\x03met\x88\x01\x01B\b\n" +
	"\x06_meseqB\x06\n" +
	"\x04_metJ\x04\be\x10fJ\x04\bf\x10gJ\x04\bg\x10h\"\xd6\x01\n" +
	"\x1aMatchingCancelOrderRequest\x12B\n" +
	"\x0ftm_requested_at\x18g \x01(\v2\x1a.google.protobuf.TimestampR\rtmRequestedAt\x12$\n" +
	"\x0esub_account_id\x18\x01 \x01(\x03R\fsubAccountId\x12$\n" +
	"\x0evenue_order_id\x18\x02 \x01(\x04R\fvenueOrderId\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbolJ\x04\be\x10fJ\x04\bf\x10gJ\x04\bh\x10i\"\xcf\x03\n" +
	"\x1bMatchingCancelOrderResponse\x12B\n" +
	"\x0ftm_responded_at\x18h \x01(\v2\x1a.google.protobuf.TimestampR\rtmRespondedAt\x12$\n" +
	"\x0esub_account_id\x18\x01 \x01(\x03R\fsubAccountId\x12$\n" +
	"\x0evenue_order_id\x18\x02 \x01(\x04R\fvenueOrderId\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x12D\n" +
	"\x06status\x18\x04 \x01(\x0e2,.synthetix.v4_offchain.matching.CancelStatusR\x06status\x12-\n" +
	"\x12cancelled_quantity\x18\x05 \x01(\x04R\x11cancelledQuantity\x12=\n" +
	"\fcancelled_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vcancelledAt\x12\x19\n" +
	"\x05meseq\x18\a \x01(\x04H\x00R\x05meseq\x88\x01\x01\x12\x15\n" +
	"\x03met\x18\b \x01(\x03H\x01R\x03met\x88\x01\x01B\b\n" +
	"\x06_meseqB\x06\n" +
	"\x04_metJ\x04\be\x10fJ\x04\bf\x10gJ\x04\bg\x10h\"\xfd\x02\n" +
	"\x1aMatchingModifyOrderRequest\x12B\n" +
	"\x0ftm_requested_at\x18g \x01(\v2\x1a.google.protobuf.TimestampR\rtmRequestedAt\x12$\n" +
	"\x0esub_account_id\x18\x01 \x01(\x03R\fsubAccountId\x12$\n" +
	"\x0evenue_order_id\x18\x02 \x01(\x04R\fvenueOrderId\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x126\n" +
	"\x04side\x18\x04 \x01(\x0e2\".synthetix.v4_offchain.common.SideR\x04side\x12;\n" +
	"\x04type\x18\x05 \x01(\x0e2'.synthetix.v4_offchain.common.OrderTypeR\x04type\x12\x1a\n" +
	"\bquantity\x18\x06 \x01(\x04R\bquantity\x12\x14\n" +
	"\x05price\x18\a \x01(\x04R\x05priceJ\x04\be\x10fJ\x04\bf\x10gJ\x04\bh\x10i\"\x89\a\n" +
	"\x1bMatchingModifyOrderResponse\x12B\n" +
	"\x0ftm_responded_at\x18h \x01(\v2\x1a.google.protobuf.TimestampR\rtmRespondedAt\x12$\n" +
	"\x0esub_account_id\x18\x01 \x01(\x03R\fsubAccountId\x12$\n" +
	"\x0evenue_order_id\x18\x02 \x01(\x04R\fvenueOrderId\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x126\n" +
	"\x04side\x18\x04 \x01(\x0e2\".synthetix.v4_offchain.common.SideR\x04side\x12;\n" +
	"\x04type\x18\x05 \x01(\x0e2'.synthetix.v4_offchain.common.OrderTypeR\x04type\x12!\n" +
	"\forg_quantity\x18\x06 \x01(\x04R\vorgQuantity\x12!\n" +
	"\fnew_quantity\x18\a \x01(\x04R\vnewQuantity\x12\x14\n" +
	"\x05price\x18\b \x01(\x04R\x05price\x12D\n" +
	"\x06status\x18\t \x01(\x0e2,.synthetix.v4_offchain.matching.ModifyStatusR\x06status\x12-\n" +
	"\x12remaining_quantity\x18\n" +
	" \x01(\x04R\x11remainingQuantity\x12;\n" +
	"\vmodified_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"modifiedAt\x12:\n" +
	"\x05fills\x18\f \x03(\v2$.synthetix.v4_offchain.matching.FillR\x05fills\x127\n" +
	"\x18canceled_venue_order_ids\x18\r \x03(\x04R\x15canceledVenueOrderIds\x127\n" +
	"\ttraded_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\btradedAt\x12\x19\n" +
	"\x05meseq\x18\x0f \x01(\x04H\x00R\x05meseq\x88\x01\x01\x12\x15\n" +
	"\x03met\x18\x10 \x01(\x03H\x01R\x03met\x88\x01\x01\x12;\n" +
	"\vrejected_at\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"rejectedAtB\b\n" +
	"\x06_meseqB\x06\n" +
	"\x04_metJ\x04\be\x10fJ\x04\bf\x10gJ\x04\bg\x10h*8\n" +
	"\fCancelStatus\x12\x12\n" +
	"\x0eCANCEL_SUCCESS\x10\x00\x12\x14\n" +
	"\x10CANCEL_NOT_FOUND\x10\x01*S\n" +
	"\fModifyStatus\x12\x12\n" +
	"\x0eMODIFY_SUCCESS\x10\x00\x12\x1a\n" +
	"\x16MODIFY_ORDER_NOT_FOUND\x10\x01\x12\x13\n" +
	"\x0fMODIFY_REJECTED\x10\x02B5Z3github.com/Synthetixio/v4-offchain/lib/message/grpcb\x06proto3"

var (
	file_matching_proto_rawDescOnce sync.Once
	file_matching_proto_rawDescData []byte
)

func file_matching_proto_rawDescGZIP() []byte {
	file_matching_proto_rawDescOnce.Do(func() {
		file_matching_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_matching_proto_rawDesc), len(file_matching_proto_rawDesc)))
	})
	return file_matching_proto_rawDescData
}

var file_matching_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_matching_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_matching_proto_goTypes = []any{
	(CancelStatus)(0),                   // 0: synthetix.v4_offchain.matching.CancelStatus
	(ModifyStatus)(0),                   // 1: synthetix.v4_offchain.matching.ModifyStatus
	(*MatchingOrderRequest)(nil),        // 2: synthetix.v4_offchain.matching.MatchingOrderRequest
	(*MatchingOrderResponse)(nil),       // 3: synthetix.v4_offchain.matching.MatchingOrderResponse
	(*Fill)(nil),                        // 4: synthetix.v4_offchain.matching.Fill
	(*MatchingNewOrderRequest)(nil),     // 5: synthetix.v4_offchain.matching.MatchingNewOrderRequest
	(*MatchingNewOrderResponse)(nil),    // 6: synthetix.v4_offchain.matching.MatchingNewOrderResponse
	(*MatchingCancelOrderRequest)(nil),  // 7: synthetix.v4_offchain.matching.MatchingCancelOrderRequest
	(*MatchingCancelOrderResponse)(nil), // 8: synthetix.v4_offchain.matching.MatchingCancelOrderResponse
	(*MatchingModifyOrderRequest)(nil),  // 9: synthetix.v4_offchain.matching.MatchingModifyOrderRequest
	(*MatchingModifyOrderResponse)(nil), // 10: synthetix.v4_offchain.matching.MatchingModifyOrderResponse
	(*timestamppb.Timestamp)(nil),       // 11: google.protobuf.Timestamp
	(Side)(0),                           // 12: synthetix.v4_offchain.common.Side
	(OrderType)(0),                      // 13: synthetix.v4_offchain.common.OrderType
	(TimeInForce)(0),                    // 14: synthetix.v4_offchain.common.TimeInForce
	(OrderStatus)(0),                    // 15: synthetix.v4_offchain.common.OrderStatus
}
var file_matching_proto_depIdxs = []int32{
	11, // 0: synthetix.v4_offchain.matching.MatchingOrderRequest.tm_requested_at:type_name -> google.protobuf.Timestamp
	5,  // 1: synthetix.v4_offchain.matching.MatchingOrderRequest.new_order:type_name -> synthetix.v4_offchain.matching.MatchingNewOrderRequest
	7,  // 2: synthetix.v4_offchain.matching.MatchingOrderRequest.cancel_order:type_name -> synthetix.v4_offchain.matching.MatchingCancelOrderRequest
	9,  // 3: synthetix.v4_offchain.matching.MatchingOrderRequest.modify_order:type_name -> synthetix.v4_offchain.matching.MatchingModifyOrderRequest
	11, // 4: synthetix.v4_offchain.matching.MatchingOrderResponse.tm_responded_at:type_name -> google.protobuf.Timestamp
	6,  // 5: synthetix.v4_offchain.matching.MatchingOrderResponse.new_order:type_name -> synthetix.v4_offchain.matching.MatchingNewOrderResponse
	8,  // 6: synthetix.v4_offchain.matching.MatchingOrderResponse.cancel_order:type_name -> synthetix.v4_offchain.matching.MatchingCancelOrderResponse
	10, // 7: synthetix.v4_offchain.matching.MatchingOrderResponse.modify_order:type_name -> synthetix.v4_offchain.matching.MatchingModifyOrderResponse
	11, // 8: synthetix.v4_offchain.matching.MatchingNewOrderRequest.tm_requested_at:type_name -> google.protobuf.Timestamp
	12, // 9: synthetix.v4_offchain.matching.MatchingNewOrderRequest.side:type_name -> synthetix.v4_offchain.common.Side
	13, // 10: synthetix.v4_offchain.matching.MatchingNewOrderRequest.type:type_name -> synthetix.v4_offchain.common.OrderType
	14, // 11: synthetix.v4_offchain.matching.MatchingNewOrderRequest.time_in_force:type_name -> synthetix.v4_offchain.common.TimeInForce
	11, // 12: synthetix.v4_offchain.matching.MatchingNewOrderResponse.tm_responded_at:type_name -> google.protobuf.Timestamp
	12, // 13: synthetix.v4_offchain.matching.MatchingNewOrderResponse.side:type_name -> synthetix.v4_offchain.common.Side
	13, // 14: synthetix.v4_offchain.matching.MatchingNewOrderResponse.type:type_name -> synthetix.v4_offchain.common.OrderType
	15, // 15: synthetix.v4_offchain.matching.MatchingNewOrderResponse.status:type_name -> synthetix.v4_offchain.common.OrderStatus
	4,  // 16: synthetix.v4_offchain.matching.MatchingNewOrderResponse.fills:type_name -> synthetix.v4_offchain.matching.Fill
	11, // 17: synthetix.v4_offchain.matching.MatchingNewOrderResponse.placed_at:type_name -> google.protobuf.Timestamp
	11, // 18: synthetix.v4_offchain.matching.MatchingNewOrderResponse.traded_at:type_name -> google.protobuf.Timestamp
	11, // 19: synthetix.v4_offchain.matching.MatchingNewOrderResponse.rejected_at:type_name -> google.protobuf.Timestamp
	11, // 20: synthetix.v4_offchain.matching.MatchingCancelOrderRequest.tm_requested_at:type_name -> google.protobuf.Timestamp
	11, // 21: synthetix.v4_offchain.matching.MatchingCancelOrderResponse.tm_responded_at:type_name -> google.protobuf.Timestamp
	0,  // 22: synthetix.v4_offchain.matching.MatchingCancelOrderResponse.status:type_name -> synthetix.v4_offchain.matching.CancelStatus
	11, // 23: synthetix.v4_offchain.matching.MatchingCancelOrderResponse.cancelled_at:type_name -> google.protobuf.Timestamp
	11, // 24: synthetix.v4_offchain.matching.MatchingModifyOrderRequest.tm_requested_at:type_name -> google.protobuf.Timestamp
	12, // 25: synthetix.v4_offchain.matching.MatchingModifyOrderRequest.side:type_name -> synthetix.v4_offchain.common.Side
	13, // 26: synthetix.v4_offchain.matching.MatchingModifyOrderRequest.type:type_name -> synthetix.v4_offchain.common.OrderType
	11, // 27: synthetix.v4_offchain.matching.MatchingModifyOrderResponse.tm_responded_at:type_name -> google.protobuf.Timestamp
	12, // 28: synthetix.v4_offchain.matching.MatchingModifyOrderResponse.side:type_name -> synthetix.v4_offchain.common.Side
	13, // 29: synthetix.v4_offchain.matching.MatchingModifyOrderResponse.type:type_name -> synthetix.v4_offchain.common.OrderType
	1,  // 30: synthetix.v4_offchain.matching.MatchingModifyOrderResponse.status:type_name -> synthetix.v4_offchain.matching.ModifyStatus
	11, // 31: synthetix.v4_offchain.matching.MatchingModifyOrderResponse.modified_at:type_name -> google.protobuf.Timestamp
	4,  // 32: synthetix.v4_offchain.matching.MatchingModifyOrderResponse.fills:type_name -> synthetix.v4_offchain.matching.Fill
	11, // 33: synthetix.v4_offchain.matching.MatchingModifyOrderResponse.traded_at:type_name -> google.protobuf.Timestamp
	11, // 34: synthetix.v4_offchain.matching.MatchingModifyOrderResponse.rejected_at:type_name -> google.protobuf.Timestamp
	35, // [35:35] is the sub-list for method output_type
	35, // [35:35] is the sub-list for method input_type
	35, // [35:35] is the sub-list for extension type_name
	35, // [35:35] is the sub-list for extension extendee
	0,  // [0:35] is the sub-list for field type_name
}

func init() { file_matching_proto_init() }
func file_matching_proto_init() {
	if File_matching_proto != nil {
		return
	}
	file_common_proto_init()
	file_matching_proto_msgTypes[0].OneofWrappers = []any{
		(*MatchingOrderRequest_NewOrder)(nil),
		(*MatchingOrderRequest_CancelOrder)(nil),
		(*MatchingOrderRequest_ModifyOrder)(nil),
	}
	file_matching_proto_msgTypes[1].OneofWrappers = []any{
		(*MatchingOrderResponse_NewOrder)(nil),
		(*MatchingOrderResponse_CancelOrder)(nil),
		(*MatchingOrderResponse_ModifyOrder)(nil),
	}
	file_matching_proto_msgTypes[2].OneofWrappers = []any{}
	file_matching_proto_msgTypes[3].OneofWrappers = []any{}
	file_matching_proto_msgTypes[4].OneofWrappers = []any{}
	file_matching_proto_msgTypes[6].OneofWrappers = []any{}
	file_matching_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_matching_proto_rawDesc), len(file_matching_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_matching_proto_goTypes,
		DependencyIndexes: file_matching_proto_depIdxs,
		EnumInfos:         file_matching_proto_enumTypes,
		MessageInfos:      file_matching_proto_msgTypes,
	}.Build()
	File_matching_proto = out.File
	file_matching_proto_goTypes = nil
	file_matching_proto_depIdxs = nil
}
