// Proto definition for Synthetix V4-Offchain Pricing Service
// To compile:
// protoc --go_out=. --go-grpc_out=. pricing.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: pricing.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MEXC Public Aggregated Book Ticker
// From: https://github.com/mexcdevelop/websocket-proto/blob/main/PublicAggreBookTickerV3Api.proto
type PublicAggreBookTickerV3Api struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BidPrice      string                 `protobuf:"bytes,1,opt,name=bid_price,json=bidPrice,proto3" json:"bid_price,omitempty"`
	BidQuantity   string                 `protobuf:"bytes,2,opt,name=bid_quantity,json=bidQuantity,proto3" json:"bid_quantity,omitempty"`
	AskPrice      string                 `protobuf:"bytes,3,opt,name=ask_price,json=askPrice,proto3" json:"ask_price,omitempty"`
	AskQuantity   string                 `protobuf:"bytes,4,opt,name=ask_quantity,json=askQuantity,proto3" json:"ask_quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicAggreBookTickerV3Api) Reset() {
	*x = PublicAggreBookTickerV3Api{}
	mi := &file_pricing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicAggreBookTickerV3Api) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicAggreBookTickerV3Api) ProtoMessage() {}

func (x *PublicAggreBookTickerV3Api) ProtoReflect() protoreflect.Message {
	mi := &file_pricing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicAggreBookTickerV3Api.ProtoReflect.Descriptor instead.
func (*PublicAggreBookTickerV3Api) Descriptor() ([]byte, []int) {
	return file_pricing_proto_rawDescGZIP(), []int{0}
}

func (x *PublicAggreBookTickerV3Api) GetBidPrice() string {
	if x != nil {
		return x.BidPrice
	}
	return ""
}

func (x *PublicAggreBookTickerV3Api) GetBidQuantity() string {
	if x != nil {
		return x.BidQuantity
	}
	return ""
}

func (x *PublicAggreBookTickerV3Api) GetAskPrice() string {
	if x != nil {
		return x.AskPrice
	}
	return ""
}

func (x *PublicAggreBookTickerV3Api) GetAskQuantity() string {
	if x != nil {
		return x.AskQuantity
	}
	return ""
}

// MEXC WebSocket wrapper message - all messages are wrapped in this
// From: https://github.com/mexcdevelop/websocket-proto
type PushDataV3ApiWrapper struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Channel name (e.g., "spot@public.aggre.bookTicker.v3.api.pb@100ms@BTCUSDT")
	Channel string `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	// Body contains the actual data - using oneof for different message types
	//
	// Types that are valid to be assigned to Body:
	//
	//	*PushDataV3ApiWrapper_PublicAggreBookTicker
	Body isPushDataV3ApiWrapper_Body `protobuf_oneof:"body"`
	// Trading pair symbol
	Symbol *string `protobuf:"bytes,3,opt,name=symbol,proto3,oneof" json:"symbol,omitempty"`
	// Trading pair ID
	SymbolId *string `protobuf:"bytes,4,opt,name=symbolId,proto3,oneof" json:"symbolId,omitempty"`
	// Message creation time
	CreateTime *int64 `protobuf:"varint,5,opt,name=createTime,proto3,oneof" json:"createTime,omitempty"`
	// Message send time
	SendTime      *int64 `protobuf:"varint,6,opt,name=sendTime,proto3,oneof" json:"sendTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushDataV3ApiWrapper) Reset() {
	*x = PushDataV3ApiWrapper{}
	mi := &file_pricing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushDataV3ApiWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushDataV3ApiWrapper) ProtoMessage() {}

func (x *PushDataV3ApiWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_pricing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushDataV3ApiWrapper.ProtoReflect.Descriptor instead.
func (*PushDataV3ApiWrapper) Descriptor() ([]byte, []int) {
	return file_pricing_proto_rawDescGZIP(), []int{1}
}

func (x *PushDataV3ApiWrapper) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *PushDataV3ApiWrapper) GetBody() isPushDataV3ApiWrapper_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *PushDataV3ApiWrapper) GetPublicAggreBookTicker() *PublicAggreBookTickerV3Api {
	if x != nil {
		if x, ok := x.Body.(*PushDataV3ApiWrapper_PublicAggreBookTicker); ok {
			return x.PublicAggreBookTicker
		}
	}
	return nil
}

func (x *PushDataV3ApiWrapper) GetSymbol() string {
	if x != nil && x.Symbol != nil {
		return *x.Symbol
	}
	return ""
}

func (x *PushDataV3ApiWrapper) GetSymbolId() string {
	if x != nil && x.SymbolId != nil {
		return *x.SymbolId
	}
	return ""
}

func (x *PushDataV3ApiWrapper) GetCreateTime() int64 {
	if x != nil && x.CreateTime != nil {
		return *x.CreateTime
	}
	return 0
}

func (x *PushDataV3ApiWrapper) GetSendTime() int64 {
	if x != nil && x.SendTime != nil {
		return *x.SendTime
	}
	return 0
}

type isPushDataV3ApiWrapper_Body interface {
	isPushDataV3ApiWrapper_Body()
}

type PushDataV3ApiWrapper_PublicAggreBookTicker struct {
	PublicAggreBookTicker *PublicAggreBookTickerV3Api `protobuf:"bytes,315,opt,name=publicAggreBookTicker,proto3,oneof"`
}

func (*PushDataV3ApiWrapper_PublicAggreBookTicker) isPushDataV3ApiWrapper_Body() {}

var File_pricing_proto protoreflect.FileDescriptor

const file_pricing_proto_rawDesc = "" +
	"\n" +
	"\rpricing.proto\x12\x1dsynthetix.v4_offchain.pricing\"\x9c\x01\n" +
	"\x1aPublicAggreBookTickerV3Api\x12\x1b\n" +
	"\tbid_price\x18\x01 \x01(\tR\bbidPrice\x12!\n" +
	"\fbid_quantity\x18\x02 \x01(\tR\vbidQuantity\x12\x1b\n" +
	"\task_price\x18\x03 \x01(\tR\baskPrice\x12!\n" +
	"\fask_quantity\x18\x04 \x01(\tR\vaskQuantity\"\xe4\x02\n" +
	"\x14PushDataV3ApiWrapper\x12\x18\n" +
	"\achannel\x18\x01 \x01(\tR\achannel\x12r\n" +
	"\x15publicAggreBookTicker\x18\xbb\x02 \x01(\v29.synthetix.v4_offchain.pricing.PublicAggreBookTickerV3ApiH\x00R\x15publicAggreBookTicker\x12\x1b\n" +
	"\x06symbol\x18\x03 \x01(\tH\x01R\x06symbol\x88\x01\x01\x12\x1f\n" +
	"\bsymbolId\x18\x04 \x01(\tH\x02R\bsymbolId\x88\x01\x01\x12#\n" +
	"\n" +
	"createTime\x18\x05 \x01(\x03H\x03R\n" +
	"createTime\x88\x01\x01\x12\x1f\n" +
	"\bsendTime\x18\x06 \x01(\x03H\x04R\bsendTime\x88\x01\x01B\x06\n" +
	"\x04bodyB\t\n" +
	"\a_symbolB\v\n" +
	"\t_symbolIdB\r\n" +
	"\v_createTimeB\v\n" +
	"\t_sendTimeB5Z3github.com/Synthetixio/v4-offchain/lib/message/grpcb\x06proto3"

var (
	file_pricing_proto_rawDescOnce sync.Once
	file_pricing_proto_rawDescData []byte
)

func file_pricing_proto_rawDescGZIP() []byte {
	file_pricing_proto_rawDescOnce.Do(func() {
		file_pricing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pricing_proto_rawDesc), len(file_pricing_proto_rawDesc)))
	})
	return file_pricing_proto_rawDescData
}

var file_pricing_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pricing_proto_goTypes = []any{
	(*PublicAggreBookTickerV3Api)(nil), // 0: synthetix.v4_offchain.pricing.PublicAggreBookTickerV3Api
	(*PushDataV3ApiWrapper)(nil),       // 1: synthetix.v4_offchain.pricing.PushDataV3ApiWrapper
}
var file_pricing_proto_depIdxs = []int32{
	0, // 0: synthetix.v4_offchain.pricing.PushDataV3ApiWrapper.publicAggreBookTicker:type_name -> synthetix.v4_offchain.pricing.PublicAggreBookTickerV3Api
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pricing_proto_init() }
func file_pricing_proto_init() {
	if File_pricing_proto != nil {
		return
	}
	file_pricing_proto_msgTypes[1].OneofWrappers = []any{
		(*PushDataV3ApiWrapper_PublicAggreBookTicker)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pricing_proto_rawDesc), len(file_pricing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pricing_proto_goTypes,
		DependencyIndexes: file_pricing_proto_depIdxs,
		MessageInfos:      file_pricing_proto_msgTypes,
	}.Build()
	File_pricing_proto = out.File
	file_pricing_proto_goTypes = nil
	file_pricing_proto_depIdxs = nil
}
