// Proto definition for Synthetix V4-Offchain SubAccount Service
// To compile:
// protoc --go_out=. --go-grpc_out=. subaccount.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: subaccount.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SubaccountService_CreateSubaccount_FullMethodName                   = "/synthetix.v4_offchain.subaccount.SubaccountService/CreateSubaccount"
	SubaccountService_UpdateSubaccount_FullMethodName                   = "/synthetix.v4_offchain.subaccount.SubaccountService/UpdateSubaccount"
	SubaccountService_UpdateSubAccountMarketLeverage_FullMethodName     = "/synthetix.v4_offchain.subaccount.SubaccountService/UpdateSubAccountMarketLeverage"
	SubaccountService_ListSubaccounts_FullMethodName                    = "/synthetix.v4_offchain.subaccount.SubaccountService/ListSubaccounts"
	SubaccountService_GetSubaccount_FullMethodName                      = "/synthetix.v4_offchain.subaccount.SubaccountService/GetSubaccount"
	SubaccountService_GetOrderHistory_FullMethodName                    = "/synthetix.v4_offchain.subaccount.SubaccountService/GetOrderHistory"
	SubaccountService_GetTradeHistory_FullMethodName                    = "/synthetix.v4_offchain.subaccount.SubaccountService/GetTradeHistory"
	SubaccountService_GetLastTrades_FullMethodName                      = "/synthetix.v4_offchain.subaccount.SubaccountService/GetLastTrades"
	SubaccountService_GetPositionHistory_FullMethodName                 = "/synthetix.v4_offchain.subaccount.SubaccountService/GetPositionHistory"
	SubaccountService_GetPositions_FullMethodName                       = "/synthetix.v4_offchain.subaccount.SubaccountService/GetPositions"
	SubaccountService_GetOpenOrders_FullMethodName                      = "/synthetix.v4_offchain.subaccount.SubaccountService/GetOpenOrders"
	SubaccountService_GetOpenLimitOrders_FullMethodName                 = "/synthetix.v4_offchain.subaccount.SubaccountService/GetOpenLimitOrders"
	SubaccountService_GetExpiredOpenOrders_FullMethodName               = "/synthetix.v4_offchain.subaccount.SubaccountService/GetExpiredOpenOrders"
	SubaccountService_GetAllSubaccounts_FullMethodName                  = "/synthetix.v4_offchain.subaccount.SubaccountService/GetAllSubaccounts"
	SubaccountService_GetSLPMappings_FullMethodName                     = "/synthetix.v4_offchain.subaccount.SubaccountService/GetSLPMappings"
	SubaccountService_BatchUpdateLeverages_FullMethodName               = "/synthetix.v4_offchain.subaccount.SubaccountService/BatchUpdateLeverages"
	SubaccountService_CreateDelegation_FullMethodName                   = "/synthetix.v4_offchain.subaccount.SubaccountService/CreateDelegation"
	SubaccountService_RemoveDelegation_FullMethodName                   = "/synthetix.v4_offchain.subaccount.SubaccountService/RemoveDelegation"
	SubaccountService_RemoveAllDelegations_FullMethodName               = "/synthetix.v4_offchain.subaccount.SubaccountService/RemoveAllDelegations"
	SubaccountService_GetDelegations_FullMethodName                     = "/synthetix.v4_offchain.subaccount.SubaccountService/GetDelegations"
	SubaccountService_GetDelegationsForDelegate_FullMethodName          = "/synthetix.v4_offchain.subaccount.SubaccountService/GetDelegationsForDelegate"
	SubaccountService_VerifySubaccountAuthorization_FullMethodName      = "/synthetix.v4_offchain.subaccount.SubaccountService/VerifySubaccountAuthorization"
	SubaccountService_GetLatestFundingRates_FullMethodName              = "/synthetix.v4_offchain.subaccount.SubaccountService/GetLatestFundingRates"
	SubaccountService_GetFundingRateHistory_FullMethodName              = "/synthetix.v4_offchain.subaccount.SubaccountService/GetFundingRateHistory"
	SubaccountService_GetFundingPayments_FullMethodName                 = "/synthetix.v4_offchain.subaccount.SubaccountService/GetFundingPayments"
	SubaccountService_GetPositionsBySymbol_FullMethodName               = "/synthetix.v4_offchain.subaccount.SubaccountService/GetPositionsBySymbol"
	SubaccountService_GetOITotalsBySymbol_FullMethodName                = "/synthetix.v4_offchain.subaccount.SubaccountService/GetOITotalsBySymbol"
	SubaccountService_GetAllOITotals_FullMethodName                     = "/synthetix.v4_offchain.subaccount.SubaccountService/GetAllOITotals"
	SubaccountService_GetPerformanceHistory_FullMethodName              = "/synthetix.v4_offchain.subaccount.SubaccountService/GetPerformanceHistory"
	SubaccountService_UpdateSubaccountStatus_FullMethodName             = "/synthetix.v4_offchain.subaccount.SubaccountService/UpdateSubaccountStatus"
	SubaccountService_AddToWithdrawBlacklist_FullMethodName             = "/synthetix.v4_offchain.subaccount.SubaccountService/AddToWithdrawBlacklist"
	SubaccountService_ListWithdrawBlacklist_FullMethodName              = "/synthetix.v4_offchain.subaccount.SubaccountService/ListWithdrawBlacklist"
	SubaccountService_RemoveFromWithdrawBlacklist_FullMethodName        = "/synthetix.v4_offchain.subaccount.SubaccountService/RemoveFromWithdrawBlacklist"
	SubaccountService_AssignWalletTier_FullMethodName                   = "/synthetix.v4_offchain.subaccount.SubaccountService/AssignWalletTier"
	SubaccountService_UnbrickPendingWithdraw_FullMethodName             = "/synthetix.v4_offchain.subaccount.SubaccountService/UnbrickPendingWithdraw"
	SubaccountService_GetInsuranceSubscription_FullMethodName           = "/synthetix.v4_offchain.subaccount.SubaccountService/GetInsuranceSubscription"
	SubaccountService_GetInsuranceProtection_FullMethodName             = "/synthetix.v4_offchain.subaccount.SubaccountService/GetInsuranceProtection"
	SubaccountService_CreateDefaultInsuranceSubscription_FullMethodName = "/synthetix.v4_offchain.subaccount.SubaccountService/CreateDefaultInsuranceSubscription"
	SubaccountService_GetBalanceUpdates_FullMethodName                  = "/synthetix.v4_offchain.subaccount.SubaccountService/GetBalanceUpdates"
	SubaccountService_TransferBetweenSubAccounts_FullMethodName         = "/synthetix.v4_offchain.subaccount.SubaccountService/TransferBetweenSubAccounts"
	SubaccountService_GetTransfers_FullMethodName                       = "/synthetix.v4_offchain.subaccount.SubaccountService/GetTransfers"
	SubaccountService_GetTradesForPosition_FullMethodName               = "/synthetix.v4_offchain.subaccount.SubaccountService/GetTradesForPosition"
	SubaccountService_GetSnaxpotNumberPreference_FullMethodName         = "/synthetix.v4_offchain.subaccount.SubaccountService/GetSnaxpotNumberPreference"
	SubaccountService_SetSnaxpotPreference_FullMethodName               = "/synthetix.v4_offchain.subaccount.SubaccountService/SetSnaxpotPreference"
	SubaccountService_ClearSnaxpotPreference_FullMethodName             = "/synthetix.v4_offchain.subaccount.SubaccountService/ClearSnaxpotPreference"
	SubaccountService_SaveSnaxpotTickets_FullMethodName                 = "/synthetix.v4_offchain.subaccount.SubaccountService/SaveSnaxpotTickets"
	SubaccountService_GetSnaxpotTicketStatus_FullMethodName             = "/synthetix.v4_offchain.subaccount.SubaccountService/GetSnaxpotTicketStatus"
)

// SubaccountServiceClient is the client API for SubaccountService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Provides gRPC API for subaccount management
type SubaccountServiceClient interface {
	// Creates a new subaccount
	CreateSubaccount(ctx context.Context, in *CreateSubaccountRequest, opts ...grpc.CallOption) (*SubaccountResponse, error)
	// Updates an existing subaccount
	UpdateSubaccount(ctx context.Context, in *UpdateSubaccountRequest, opts ...grpc.CallOption) (*SubaccountResponse, error)
	UpdateSubAccountMarketLeverage(ctx context.Context, in *UpdateSubAccountMarketLeverageRequest, opts ...grpc.CallOption) (*UpdateSubAccountMarketLeverageResponse, error)
	// Lists subaccounts with filtering and pagination
	ListSubaccounts(ctx context.Context, in *ListSubaccountsRequest, opts ...grpc.CallOption) (*ListSubaccountsResponse, error)
	// Fetches a single subaccount by ID
	GetSubaccount(ctx context.Context, in *GetSubaccountRequest, opts ...grpc.CallOption) (*SubaccountInfo, error)
	// Retrieves order history for a subaccount
	GetOrderHistory(ctx context.Context, in *GetOrderHistoryRequest, opts ...grpc.CallOption) (*GetOrderHistoryResponse, error)
	// Retrieves trade history for a subaccount
	GetTradeHistory(ctx context.Context, in *GetTradeHistoryRequest, opts ...grpc.CallOption) (*GetTradeHistoryResponse, error)
	// Retrieves the most recent trades for a market (public data)
	GetLastTrades(ctx context.Context, in *GetLastTradesRequest, opts ...grpc.CallOption) (*GetLastTradesResponse, error)
	// Retrieves closed position history for a subaccount
	GetPositionHistory(ctx context.Context, in *GetPositionHistoryRequest, opts ...grpc.CallOption) (*GetPositionHistoryResponse, error)
	// Retrieves open positions for a subaccount
	GetPositions(ctx context.Context, in *GetPositionsRequest, opts ...grpc.CallOption) (*GetPositionsResponse, error)
	// Retrieves open orders for a subaccount
	GetOpenOrders(ctx context.Context, in *GetOpenOrdersRequest, opts ...grpc.CallOption) (*GetOpenOrdersResponse, error)
	// Retrieves all open limit orders for recovery purposes
	GetOpenLimitOrders(ctx context.Context, in *GetOpenLimitOrdersRequest, opts ...grpc.CallOption) (*GetOpenLimitOrdersResponse, error)
	// Retrieves expired open orders for Trading's expiration sweeper.
	GetExpiredOpenOrders(ctx context.Context, in *GetExpiredOpenOrdersRequest, opts ...grpc.CallOption) (*GetExpiredOpenOrdersResponse, error)
	// Retrieves all subaccounts with their basic information
	GetAllSubaccounts(ctx context.Context, in *GetAllSubaccountsRequest, opts ...grpc.CallOption) (*GetAllSubaccountsResponse, error)
	// Retrieves SLP account mappings for markets and collaterals
	GetSLPMappings(ctx context.Context, in *GetSLPMappingsRequest, opts ...grpc.CallOption) (*GetSLPMappingsResponse, error)
	// Updates leverages for multiple subaccounts in batch
	BatchUpdateLeverages(ctx context.Context, in *BatchUpdateLeveragesRequest, opts ...grpc.CallOption) (*BatchUpdateLeveragesResponse, error)
	// Delegation management methods
	CreateDelegation(ctx context.Context, in *CreateDelegationRequest, opts ...grpc.CallOption) (*CreateDelegationResponse, error)
	RemoveDelegation(ctx context.Context, in *RemoveDelegationRequest, opts ...grpc.CallOption) (*RemoveDelegationResponse, error)
	RemoveAllDelegations(ctx context.Context, in *RemoveAllDelegationsRequest, opts ...grpc.CallOption) (*RemoveAllDelegationsResponse, error)
	GetDelegations(ctx context.Context, in *GetDelegationsRequest, opts ...grpc.CallOption) (*GetDelegationsResponse, error)
	GetDelegationsForDelegate(ctx context.Context, in *GetDelegationsForDelegateRequest, opts ...grpc.CallOption) (*GetDelegationsForDelegateResponse, error)
	VerifySubaccountAuthorization(ctx context.Context, in *VerifySubaccountAuthorizationRequest, opts ...grpc.CallOption) (*VerifySubaccountAuthorizationResponse, error)
	// Gets the latest funding rates for provided symbols (or all if none provided)
	GetLatestFundingRates(ctx context.Context, in *GetLatestFundingRatesRequest, opts ...grpc.CallOption) (*GetLatestFundingRatesResponse, error)
	// Gets historical funding rates for a symbol
	GetFundingRateHistory(ctx context.Context, in *GetFundingRateHistoryRequest, opts ...grpc.CallOption) (*GetFundingRateHistoryResponse, error)
	// Retrieves funding payment history for a subaccount with aggregation
	GetFundingPayments(ctx context.Context, in *GetFundingPaymentsRequest, opts ...grpc.CallOption) (*GetFundingPaymentsResponse, error)
	// Retrieves open positions for a subaccount by symbol
	GetPositionsBySymbol(ctx context.Context, in *GetPositionsBySymbolRequest, opts ...grpc.CallOption) (*GetPositionsBySymbolResponse, error)
	// Retrieves only the total OI quantities for a symbol (lightweight, for matching service)
	GetOITotalsBySymbol(ctx context.Context, in *GetOITotalsBySymbolRequest, opts ...grpc.CallOption) (*GetOITotalsBySymbolResponse, error)
	// Retrieves OI totals for all symbols in a single query (for market prices endpoint)
	GetAllOITotals(ctx context.Context, in *GetAllOITotalsRequest, opts ...grpc.CallOption) (*GetAllOITotalsResponse, error)
	// Retrieves historical performance metrics (account value, PnL, volume)
	GetPerformanceHistory(ctx context.Context, in *GetPerformanceHistoryRequest, opts ...grpc.CallOption) (*GetPerformanceHistoryResponse, error)
	// Admin: Update subaccount status (freeze/unfreeze)
	UpdateSubaccountStatus(ctx context.Context, in *UpdateSubaccountStatusRequest, opts ...grpc.CallOption) (*UpdateSubaccountStatusResponse, error)
	// Admin: Withdraw blacklist (relayer disputes withdrawals for these wallets)
	AddToWithdrawBlacklist(ctx context.Context, in *AddToWithdrawBlacklistRequest, opts ...grpc.CallOption) (*AddToWithdrawBlacklistResponse, error)
	ListWithdrawBlacklist(ctx context.Context, in *ListWithdrawBlacklistRequest, opts ...grpc.CallOption) (*ListWithdrawBlacklistResponse, error)
	RemoveFromWithdrawBlacklist(ctx context.Context, in *RemoveFromWithdrawBlacklistRequest, opts ...grpc.CallOption) (*RemoveFromWithdrawBlacklistResponse, error)
	// Admin: Assign a wallet to a custom fee tier
	AssignWalletTier(ctx context.Context, in *AssignWalletTierRequest, opts ...grpc.CallOption) (*AssignWalletTierResponse, error)
	// Admin: Unbrick subaccount with pending withdrawal
	UnbrickPendingWithdraw(ctx context.Context, in *UnbrickPendingWithdrawRequest, opts ...grpc.CallOption) (*UnbrickPendingWithdrawResponse, error)
	// Insurance RPC
	GetInsuranceSubscription(ctx context.Context, in *GetInsuranceSubscriptionRequest, opts ...grpc.CallOption) (*GetInsuranceSubscriptionResponse, error)
	GetInsuranceProtection(ctx context.Context, in *GetInsuranceProtectionRequest, opts ...grpc.CallOption) (*GetInsuranceProtectionResponse, error)
	CreateDefaultInsuranceSubscription(ctx context.Context, in *CreateDefaultInsuranceSubscriptionRequest, opts ...grpc.CallOption) (*CreateDefaultInsuranceSubscriptionResponse, error)
	// Retrieves deposit and withdrawal history for a subaccount
	GetBalanceUpdates(ctx context.Context, in *GetBalanceUpdatesRequest, opts ...grpc.CallOption) (*GetBalanceUpdatesResponse, error)
	// Transfers collateral between two subaccounts owned by the same wallet
	TransferBetweenSubAccounts(ctx context.Context, in *TransferBetweenSubAccountsRequest, opts ...grpc.CallOption) (*TransferBetweenSubAccountsResponse, error)
	// Retrieves transfer history for a subaccount (as sender or receiver)
	GetTransfers(ctx context.Context, in *GetTransfersRequest, opts ...grpc.CallOption) (*GetTransfersResponse, error)
	// Retrieves trades that contributed to a specific position's lifecycle
	GetTradesForPosition(ctx context.Context, in *GetTradesForPositionRequest, opts ...grpc.CallOption) (*GetTradesForPositionResponse, error)
	// Snaxpot: current number-selection preference for a subaccount wallet
	GetSnaxpotNumberPreference(ctx context.Context, in *GetSnaxpotNumberPreferenceRequest, opts ...grpc.CallOption) (*GetSnaxpotNumberPreferenceResponse, error)
	// Snaxpot: opt into snax_only by saving a Snax-ball for the given scope
	SetSnaxpotPreference(ctx context.Context, in *SetSnaxpotPreferenceRequest, opts ...grpc.CallOption) (*SetSnaxpotPreferenceResponse, error)
	// Snaxpot: clear the Snax-ball for the given scope; when no scoped
	// preference remains the wallet falls back to auto
	ClearSnaxpotPreference(ctx context.Context, in *ClearSnaxpotPreferenceRequest, opts ...grpc.CallOption) (*ClearSnaxpotPreferenceResponse, error)
	// Snaxpot: overwrite already-issued ticket numbers for selected tickets
	SaveSnaxpotTickets(ctx context.Context, in *SaveSnaxpotTicketsRequest, opts ...grpc.CallOption) (*SaveSnaxpotTicketsResponse, error)
	// Snaxpot: ticket status, issued tickets, and effective preferences
	GetSnaxpotTicketStatus(ctx context.Context, in *GetSnaxpotTicketStatusRequest, opts ...grpc.CallOption) (*GetSnaxpotTicketStatusResponse, error)
}

type subaccountServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSubaccountServiceClient(cc grpc.ClientConnInterface) SubaccountServiceClient {
	return &subaccountServiceClient{cc}
}

func (c *subaccountServiceClient) CreateSubaccount(ctx context.Context, in *CreateSubaccountRequest, opts ...grpc.CallOption) (*SubaccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubaccountResponse)
	err := c.cc.Invoke(ctx, SubaccountService_CreateSubaccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subaccountServiceClient) UpdateSubaccount(ctx context.Context, in *UpdateSubaccountRequest, opts ...grpc.CallOption) (*SubaccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubaccountResponse)
	err := c.cc.Invoke(ctx, SubaccountService_UpdateSubaccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subaccountServiceClient) UpdateSubAccountMarketLeverage(ctx context.Context, in *UpdateSubAccountMarketLeverageRequest, opts ...grpc.CallOption) (*UpdateSubAccountMarketLeverageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSubAccountMarketLeverageResponse)
	err := c.cc.Invoke(ctx, SubaccountService_UpdateSubAccountMarketLeverage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subaccountServiceClient) ListSubaccounts(ctx context.Context, in *ListSubaccountsRequest, opts ...grpc.CallOption) (*ListSubaccountsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSubaccountsResponse)
	err := c.cc.Invoke(ctx, SubaccountService_ListSubaccounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subaccountServiceClient) GetSubaccount(ctx context.Context, in *GetSubaccountRequest, opts ...grpc.CallOption) (*SubaccountInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubaccountInfo)
	err := c.cc.Invoke(ctx, SubaccountService_GetSubaccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subaccountServiceClient) GetOrderHistory(ctx context.Context, in *GetOrderHistoryRequest, opts ...grpc.CallOption) (*GetOrderHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOrderHistoryResponse)
	err := c.cc.Invoke(ctx, SubaccountService_GetOrderHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subaccountServiceClient) GetTradeHistory(ctx context.Context, in *GetTradeHistoryRequest, opts ...grpc.CallOption) (*GetTradeHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTradeHistoryResponse)
	err := c.cc.Invoke(ctx, SubaccountService_GetTradeHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subaccountServiceClient) GetLastTrades(ctx context.Context, in *GetLastTradesRequest, opts ...grpc.CallOption) (*GetLastTradesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLastTradesResponse)
	err := c.cc.Invoke(ctx, SubaccountService_GetLastTrades_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subaccountServiceClient) GetPositionHistory(ctx context.Context, in *GetPositionHistoryRequest, opts ...grpc.CallOption) (*GetPositionHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPositionHistoryResponse)
	err := c.cc.Invoke(ctx, SubaccountService_GetPositionHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subaccountServiceClient) GetPositions(ctx context.Context, in *GetPositionsRequest, opts ...grpc.CallOption) (*GetPositionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPositionsResponse)
	err := c.cc.Invoke(ctx, SubaccountService_GetPositions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subaccountServiceClient) GetOpenOrders(ctx context.Context, in *GetOpenOrdersRequest, opts ...grpc.CallOption) (*GetOpenOrdersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOpenOrdersResponse)
	err := c.cc.Invoke(ctx, SubaccountService_GetOpenOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subaccountServiceClient) GetOpenLimitOrders(ctx context.Context, in *GetOpenLimitOrdersRequest, opts ...grpc.CallOption) (*GetOpenLimitOrdersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOpenLimitOrdersResponse)
	err := c.cc.Invoke(ctx, SubaccountService_GetOpenLimitOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subaccountServiceClient) GetExpiredOpenOrders(ctx context.Context, in *GetExpiredOpenOrdersRequest, opts ...grpc.CallOption) (*GetExpiredOpenOrdersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetExpiredOpenOrdersResponse)
	err := c.cc.Invoke(ctx, SubaccountService_GetExpiredOpenOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subaccountServiceClient) GetAllSubaccounts(ctx context.Context, in *GetAllSubaccountsRequest, opts ...grpc.CallOption) (*GetAllSubaccountsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllSubaccountsResponse)
	err := c.cc.Invoke(ctx, SubaccountService_GetAllSubaccounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subaccountServiceClient) GetSLPMappings(ctx context.Context, in *GetSLPMappingsRequest, opts ...grpc.CallOption) (*GetSLPMappingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSLPMappingsResponse)
	err := c.cc.Invoke(ctx, SubaccountService_GetSLPMappings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subaccountServiceClient) BatchUpdateLeverages(ctx context.Context, in *BatchUpdateLeveragesRequest, opts ...grpc.CallOption) (*BatchUpdateLeveragesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchUpdateLeveragesResponse)
	err := c.cc.Invoke(ctx, SubaccountService_BatchUpdateLeverages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subaccountServiceClient) CreateDelegation(ctx context.Context, in *CreateDelegationRequest, opts ...grpc.CallOption) (*CreateDelegationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateDelegationResponse)
	err := c.cc.Invoke(ctx, SubaccountService_CreateDelegation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subaccountServiceClient) RemoveDelegation(ctx context.Context, in *RemoveDelegationRequest, opts ...grpc.CallOption) (*RemoveDelegationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveDelegationResponse)
	err := c.cc.Invoke(ctx, SubaccountService_RemoveDelegation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subaccountServiceClient) RemoveAllDelegations(ctx context.Context, in *RemoveAllDelegationsRequest, opts ...grpc.CallOption) (*RemoveAllDelegationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveAllDelegationsResponse)
	err := c.cc.Invoke(ctx, SubaccountService_RemoveAllDelegations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subaccountServiceClient) GetDelegations(ctx context.Context, in *GetDelegationsRequest, opts ...grpc.CallOption) (*GetDelegationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDelegationsResponse)
	err := c.cc.Invoke(ctx, SubaccountService_GetDelegations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subaccountServiceClient) GetDelegationsForDelegate(ctx context.Context, in *GetDelegationsForDelegateRequest, opts ...grpc.CallOption) (*GetDelegationsForDelegateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDelegationsForDelegateResponse)
	err := c.cc.Invoke(ctx, SubaccountService_GetDelegationsForDelegate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subaccountServiceClient) VerifySubaccountAuthorization(ctx context.Context, in *VerifySubaccountAuthorizationRequest, opts ...grpc.CallOption) (*VerifySubaccountAuthorizationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifySubaccountAuthorizationResponse)
	err := c.cc.Invoke(ctx, SubaccountService_VerifySubaccountAuthorization_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subaccountServiceClient) GetLatestFundingRates(ctx context.Context, in *GetLatestFundingRatesRequest, opts ...grpc.CallOption) (*GetLatestFundingRatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLatestFundingRatesResponse)
	err := c.cc.Invoke(ctx, SubaccountService_GetLatestFundingRates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subaccountServiceClient) GetFundingRateHistory(ctx context.Context, in *GetFundingRateHistoryRequest, opts ...grpc.CallOption) (*GetFundingRateHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFundingRateHistoryResponse)
	err := c.cc.Invoke(ctx, SubaccountService_GetFundingRateHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subaccountServiceClient) GetFundingPayments(ctx context.Context, in *GetFundingPaymentsRequest, opts ...grpc.CallOption) (*GetFundingPaymentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFundingPaymentsResponse)
	err := c.cc.Invoke(ctx, SubaccountService_GetFundingPayments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subaccountServiceClient) GetPositionsBySymbol(ctx context.Context, in *GetPositionsBySymbolRequest, opts ...grpc.CallOption) (*GetPositionsBySymbolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPositionsBySymbolResponse)
	err := c.cc.Invoke(ctx, SubaccountService_GetPositionsBySymbol_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subaccountServiceClient) GetOITotalsBySymbol(ctx context.Context, in *GetOITotalsBySymbolRequest, opts ...grpc.CallOption) (*GetOITotalsBySymbolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOITotalsBySymbolResponse)
	err := c.cc.Invoke(ctx, SubaccountService_GetOITotalsBySymbol_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subaccountServiceClient) GetAllOITotals(ctx context.Context, in *GetAllOITotalsRequest, opts ...grpc.CallOption) (*GetAllOITotalsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllOITotalsResponse)
	err := c.cc.Invoke(ctx, SubaccountService_GetAllOITotals_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subaccountServiceClient) GetPerformanceHistory(ctx context.Context, in *GetPerformanceHistoryRequest, opts ...grpc.CallOption) (*GetPerformanceHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPerformanceHistoryResponse)
	err := c.cc.Invoke(ctx, SubaccountService_GetPerformanceHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subaccountServiceClient) UpdateSubaccountStatus(ctx context.Context, in *UpdateSubaccountStatusRequest, opts ...grpc.CallOption) (*UpdateSubaccountStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSubaccountStatusResponse)
	err := c.cc.Invoke(ctx, SubaccountService_UpdateSubaccountStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subaccountServiceClient) AddToWithdrawBlacklist(ctx context.Context, in *AddToWithdrawBlacklistRequest, opts ...grpc.CallOption) (*AddToWithdrawBlacklistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddToWithdrawBlacklistResponse)
	err := c.cc.Invoke(ctx, SubaccountService_AddToWithdrawBlacklist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subaccountServiceClient) ListWithdrawBlacklist(ctx context.Context, in *ListWithdrawBlacklistRequest, opts ...grpc.CallOption) (*ListWithdrawBlacklistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWithdrawBlacklistResponse)
	err := c.cc.Invoke(ctx, SubaccountService_ListWithdrawBlacklist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subaccountServiceClient) RemoveFromWithdrawBlacklist(ctx context.Context, in *RemoveFromWithdrawBlacklistRequest, opts ...grpc.CallOption) (*RemoveFromWithdrawBlacklistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveFromWithdrawBlacklistResponse)
	err := c.cc.Invoke(ctx, SubaccountService_RemoveFromWithdrawBlacklist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subaccountServiceClient) AssignWalletTier(ctx context.Context, in *AssignWalletTierRequest, opts ...grpc.CallOption) (*AssignWalletTierResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssignWalletTierResponse)
	err := c.cc.Invoke(ctx, SubaccountService_AssignWalletTier_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subaccountServiceClient) UnbrickPendingWithdraw(ctx context.Context, in *UnbrickPendingWithdrawRequest, opts ...grpc.CallOption) (*UnbrickPendingWithdrawResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnbrickPendingWithdrawResponse)
	err := c.cc.Invoke(ctx, SubaccountService_UnbrickPendingWithdraw_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subaccountServiceClient) GetInsuranceSubscription(ctx context.Context, in *GetInsuranceSubscriptionRequest, opts ...grpc.CallOption) (*GetInsuranceSubscriptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInsuranceSubscriptionResponse)
	err := c.cc.Invoke(ctx, SubaccountService_GetInsuranceSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subaccountServiceClient) GetInsuranceProtection(ctx context.Context, in *GetInsuranceProtectionRequest, opts ...grpc.CallOption) (*GetInsuranceProtectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInsuranceProtectionResponse)
	err := c.cc.Invoke(ctx, SubaccountService_GetInsuranceProtection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subaccountServiceClient) CreateDefaultInsuranceSubscription(ctx context.Context, in *CreateDefaultInsuranceSubscriptionRequest, opts ...grpc.CallOption) (*CreateDefaultInsuranceSubscriptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateDefaultInsuranceSubscriptionResponse)
	err := c.cc.Invoke(ctx, SubaccountService_CreateDefaultInsuranceSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subaccountServiceClient) GetBalanceUpdates(ctx context.Context, in *GetBalanceUpdatesRequest, opts ...grpc.CallOption) (*GetBalanceUpdatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBalanceUpdatesResponse)
	err := c.cc.Invoke(ctx, SubaccountService_GetBalanceUpdates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subaccountServiceClient) TransferBetweenSubAccounts(ctx context.Context, in *TransferBetweenSubAccountsRequest, opts ...grpc.CallOption) (*TransferBetweenSubAccountsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferBetweenSubAccountsResponse)
	err := c.cc.Invoke(ctx, SubaccountService_TransferBetweenSubAccounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subaccountServiceClient) GetTransfers(ctx context.Context, in *GetTransfersRequest, opts ...grpc.CallOption) (*GetTransfersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTransfersResponse)
	err := c.cc.Invoke(ctx, SubaccountService_GetTransfers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subaccountServiceClient) GetTradesForPosition(ctx context.Context, in *GetTradesForPositionRequest, opts ...grpc.CallOption) (*GetTradesForPositionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTradesForPositionResponse)
	err := c.cc.Invoke(ctx, SubaccountService_GetTradesForPosition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subaccountServiceClient) GetSnaxpotNumberPreference(ctx context.Context, in *GetSnaxpotNumberPreferenceRequest, opts ...grpc.CallOption) (*GetSnaxpotNumberPreferenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSnaxpotNumberPreferenceResponse)
	err := c.cc.Invoke(ctx, SubaccountService_GetSnaxpotNumberPreference_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subaccountServiceClient) SetSnaxpotPreference(ctx context.Context, in *SetSnaxpotPreferenceRequest, opts ...grpc.CallOption) (*SetSnaxpotPreferenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetSnaxpotPreferenceResponse)
	err := c.cc.Invoke(ctx, SubaccountService_SetSnaxpotPreference_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subaccountServiceClient) ClearSnaxpotPreference(ctx context.Context, in *ClearSnaxpotPreferenceRequest, opts ...grpc.CallOption) (*ClearSnaxpotPreferenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClearSnaxpotPreferenceResponse)
	err := c.cc.Invoke(ctx, SubaccountService_ClearSnaxpotPreference_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subaccountServiceClient) SaveSnaxpotTickets(ctx context.Context, in *SaveSnaxpotTicketsRequest, opts ...grpc.CallOption) (*SaveSnaxpotTicketsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveSnaxpotTicketsResponse)
	err := c.cc.Invoke(ctx, SubaccountService_SaveSnaxpotTickets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subaccountServiceClient) GetSnaxpotTicketStatus(ctx context.Context, in *GetSnaxpotTicketStatusRequest, opts ...grpc.CallOption) (*GetSnaxpotTicketStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSnaxpotTicketStatusResponse)
	err := c.cc.Invoke(ctx, SubaccountService_GetSnaxpotTicketStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SubaccountServiceServer is the server API for SubaccountService service.
// All implementations must embed UnimplementedSubaccountServiceServer
// for forward compatibility.
//
// Provides gRPC API for subaccount management
type SubaccountServiceServer interface {
	// Creates a new subaccount
	CreateSubaccount(context.Context, *CreateSubaccountRequest) (*SubaccountResponse, error)
	// Updates an existing subaccount
	UpdateSubaccount(context.Context, *UpdateSubaccountRequest) (*SubaccountResponse, error)
	UpdateSubAccountMarketLeverage(context.Context, *UpdateSubAccountMarketLeverageRequest) (*UpdateSubAccountMarketLeverageResponse, error)
	// Lists subaccounts with filtering and pagination
	ListSubaccounts(context.Context, *ListSubaccountsRequest) (*ListSubaccountsResponse, error)
	// Fetches a single subaccount by ID
	GetSubaccount(context.Context, *GetSubaccountRequest) (*SubaccountInfo, error)
	// Retrieves order history for a subaccount
	GetOrderHistory(context.Context, *GetOrderHistoryRequest) (*GetOrderHistoryResponse, error)
	// Retrieves trade history for a subaccount
	GetTradeHistory(context.Context, *GetTradeHistoryRequest) (*GetTradeHistoryResponse, error)
	// Retrieves the most recent trades for a market (public data)
	GetLastTrades(context.Context, *GetLastTradesRequest) (*GetLastTradesResponse, error)
	// Retrieves closed position history for a subaccount
	GetPositionHistory(context.Context, *GetPositionHistoryRequest) (*GetPositionHistoryResponse, error)
	// Retrieves open positions for a subaccount
	GetPositions(context.Context, *GetPositionsRequest) (*GetPositionsResponse, error)
	// Retrieves open orders for a subaccount
	GetOpenOrders(context.Context, *GetOpenOrdersRequest) (*GetOpenOrdersResponse, error)
	// Retrieves all open limit orders for recovery purposes
	GetOpenLimitOrders(context.Context, *GetOpenLimitOrdersRequest) (*GetOpenLimitOrdersResponse, error)
	// Retrieves expired open orders for Trading's expiration sweeper.
	GetExpiredOpenOrders(context.Context, *GetExpiredOpenOrdersRequest) (*GetExpiredOpenOrdersResponse, error)
	// Retrieves all subaccounts with their basic information
	GetAllSubaccounts(context.Context, *GetAllSubaccountsRequest) (*GetAllSubaccountsResponse, error)
	// Retrieves SLP account mappings for markets and collaterals
	GetSLPMappings(context.Context, *GetSLPMappingsRequest) (*GetSLPMappingsResponse, error)
	// Updates leverages for multiple subaccounts in batch
	BatchUpdateLeverages(context.Context, *BatchUpdateLeveragesRequest) (*BatchUpdateLeveragesResponse, error)
	// Delegation management methods
	CreateDelegation(context.Context, *CreateDelegationRequest) (*CreateDelegationResponse, error)
	RemoveDelegation(context.Context, *RemoveDelegationRequest) (*RemoveDelegationResponse, error)
	RemoveAllDelegations(context.Context, *RemoveAllDelegationsRequest) (*RemoveAllDelegationsResponse, error)
	GetDelegations(context.Context, *GetDelegationsRequest) (*GetDelegationsResponse, error)
	GetDelegationsForDelegate(context.Context, *GetDelegationsForDelegateRequest) (*GetDelegationsForDelegateResponse, error)
	VerifySubaccountAuthorization(context.Context, *VerifySubaccountAuthorizationRequest) (*VerifySubaccountAuthorizationResponse, error)
	// Gets the latest funding rates for provided symbols (or all if none provided)
	GetLatestFundingRates(context.Context, *GetLatestFundingRatesRequest) (*GetLatestFundingRatesResponse, error)
	// Gets historical funding rates for a symbol
	GetFundingRateHistory(context.Context, *GetFundingRateHistoryRequest) (*GetFundingRateHistoryResponse, error)
	// Retrieves funding payment history for a subaccount with aggregation
	GetFundingPayments(context.Context, *GetFundingPaymentsRequest) (*GetFundingPaymentsResponse, error)
	// Retrieves open positions for a subaccount by symbol
	GetPositionsBySymbol(context.Context, *GetPositionsBySymbolRequest) (*GetPositionsBySymbolResponse, error)
	// Retrieves only the total OI quantities for a symbol (lightweight, for matching service)
	GetOITotalsBySymbol(context.Context, *GetOITotalsBySymbolRequest) (*GetOITotalsBySymbolResponse, error)
	// Retrieves OI totals for all symbols in a single query (for market prices endpoint)
	GetAllOITotals(context.Context, *GetAllOITotalsRequest) (*GetAllOITotalsResponse, error)
	// Retrieves historical performance metrics (account value, PnL, volume)
	GetPerformanceHistory(context.Context, *GetPerformanceHistoryRequest) (*GetPerformanceHistoryResponse, error)
	// Admin: Update subaccount status (freeze/unfreeze)
	UpdateSubaccountStatus(context.Context, *UpdateSubaccountStatusRequest) (*UpdateSubaccountStatusResponse, error)
	// Admin: Withdraw blacklist (relayer disputes withdrawals for these wallets)
	AddToWithdrawBlacklist(context.Context, *AddToWithdrawBlacklistRequest) (*AddToWithdrawBlacklistResponse, error)
	ListWithdrawBlacklist(context.Context, *ListWithdrawBlacklistRequest) (*ListWithdrawBlacklistResponse, error)
	RemoveFromWithdrawBlacklist(context.Context, *RemoveFromWithdrawBlacklistRequest) (*RemoveFromWithdrawBlacklistResponse, error)
	// Admin: Assign a wallet to a custom fee tier
	AssignWalletTier(context.Context, *AssignWalletTierRequest) (*AssignWalletTierResponse, error)
	// Admin: Unbrick subaccount with pending withdrawal
	UnbrickPendingWithdraw(context.Context, *UnbrickPendingWithdrawRequest) (*UnbrickPendingWithdrawResponse, error)
	// Insurance RPC
	GetInsuranceSubscription(context.Context, *GetInsuranceSubscriptionRequest) (*GetInsuranceSubscriptionResponse, error)
	GetInsuranceProtection(context.Context, *GetInsuranceProtectionRequest) (*GetInsuranceProtectionResponse, error)
	CreateDefaultInsuranceSubscription(context.Context, *CreateDefaultInsuranceSubscriptionRequest) (*CreateDefaultInsuranceSubscriptionResponse, error)
	// Retrieves deposit and withdrawal history for a subaccount
	GetBalanceUpdates(context.Context, *GetBalanceUpdatesRequest) (*GetBalanceUpdatesResponse, error)
	// Transfers collateral between two subaccounts owned by the same wallet
	TransferBetweenSubAccounts(context.Context, *TransferBetweenSubAccountsRequest) (*TransferBetweenSubAccountsResponse, error)
	// Retrieves transfer history for a subaccount (as sender or receiver)
	GetTransfers(context.Context, *GetTransfersRequest) (*GetTransfersResponse, error)
	// Retrieves trades that contributed to a specific position's lifecycle
	GetTradesForPosition(context.Context, *GetTradesForPositionRequest) (*GetTradesForPositionResponse, error)
	// Snaxpot: current number-selection preference for a subaccount wallet
	GetSnaxpotNumberPreference(context.Context, *GetSnaxpotNumberPreferenceRequest) (*GetSnaxpotNumberPreferenceResponse, error)
	// Snaxpot: opt into snax_only by saving a Snax-ball for the given scope
	SetSnaxpotPreference(context.Context, *SetSnaxpotPreferenceRequest) (*SetSnaxpotPreferenceResponse, error)
	// Snaxpot: clear the Snax-ball for the given scope; when no scoped
	// preference remains the wallet falls back to auto
	ClearSnaxpotPreference(context.Context, *ClearSnaxpotPreferenceRequest) (*ClearSnaxpotPreferenceResponse, error)
	// Snaxpot: overwrite already-issued ticket numbers for selected tickets
	SaveSnaxpotTickets(context.Context, *SaveSnaxpotTicketsRequest) (*SaveSnaxpotTicketsResponse, error)
	// Snaxpot: ticket status, issued tickets, and effective preferences
	GetSnaxpotTicketStatus(context.Context, *GetSnaxpotTicketStatusRequest) (*GetSnaxpotTicketStatusResponse, error)
	mustEmbedUnimplementedSubaccountServiceServer()
}

// UnimplementedSubaccountServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSubaccountServiceServer struct{}

func (UnimplementedSubaccountServiceServer) CreateSubaccount(context.Context, *CreateSubaccountRequest) (*SubaccountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSubaccount not implemented")
}
func (UnimplementedSubaccountServiceServer) UpdateSubaccount(context.Context, *UpdateSubaccountRequest) (*SubaccountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSubaccount not implemented")
}
func (UnimplementedSubaccountServiceServer) UpdateSubAccountMarketLeverage(context.Context, *UpdateSubAccountMarketLeverageRequest) (*UpdateSubAccountMarketLeverageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSubAccountMarketLeverage not implemented")
}
func (UnimplementedSubaccountServiceServer) ListSubaccounts(context.Context, *ListSubaccountsRequest) (*ListSubaccountsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSubaccounts not implemented")
}
func (UnimplementedSubaccountServiceServer) GetSubaccount(context.Context, *GetSubaccountRequest) (*SubaccountInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSubaccount not implemented")
}
func (UnimplementedSubaccountServiceServer) GetOrderHistory(context.Context, *GetOrderHistoryRequest) (*GetOrderHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOrderHistory not implemented")
}
func (UnimplementedSubaccountServiceServer) GetTradeHistory(context.Context, *GetTradeHistoryRequest) (*GetTradeHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTradeHistory not implemented")
}
func (UnimplementedSubaccountServiceServer) GetLastTrades(context.Context, *GetLastTradesRequest) (*GetLastTradesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLastTrades not implemented")
}
func (UnimplementedSubaccountServiceServer) GetPositionHistory(context.Context, *GetPositionHistoryRequest) (*GetPositionHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPositionHistory not implemented")
}
func (UnimplementedSubaccountServiceServer) GetPositions(context.Context, *GetPositionsRequest) (*GetPositionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPositions not implemented")
}
func (UnimplementedSubaccountServiceServer) GetOpenOrders(context.Context, *GetOpenOrdersRequest) (*GetOpenOrdersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOpenOrders not implemented")
}
func (UnimplementedSubaccountServiceServer) GetOpenLimitOrders(context.Context, *GetOpenLimitOrdersRequest) (*GetOpenLimitOrdersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOpenLimitOrders not implemented")
}
func (UnimplementedSubaccountServiceServer) GetExpiredOpenOrders(context.Context, *GetExpiredOpenOrdersRequest) (*GetExpiredOpenOrdersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetExpiredOpenOrders not implemented")
}
func (UnimplementedSubaccountServiceServer) GetAllSubaccounts(context.Context, *GetAllSubaccountsRequest) (*GetAllSubaccountsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllSubaccounts not implemented")
}
func (UnimplementedSubaccountServiceServer) GetSLPMappings(context.Context, *GetSLPMappingsRequest) (*GetSLPMappingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSLPMappings not implemented")
}
func (UnimplementedSubaccountServiceServer) BatchUpdateLeverages(context.Context, *BatchUpdateLeveragesRequest) (*BatchUpdateLeveragesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchUpdateLeverages not implemented")
}
func (UnimplementedSubaccountServiceServer) CreateDelegation(context.Context, *CreateDelegationRequest) (*CreateDelegationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDelegation not implemented")
}
func (UnimplementedSubaccountServiceServer) RemoveDelegation(context.Context, *RemoveDelegationRequest) (*RemoveDelegationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveDelegation not implemented")
}
func (UnimplementedSubaccountServiceServer) RemoveAllDelegations(context.Context, *RemoveAllDelegationsRequest) (*RemoveAllDelegationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveAllDelegations not implemented")
}
func (UnimplementedSubaccountServiceServer) GetDelegations(context.Context, *GetDelegationsRequest) (*GetDelegationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDelegations not implemented")
}
func (UnimplementedSubaccountServiceServer) GetDelegationsForDelegate(context.Context, *GetDelegationsForDelegateRequest) (*GetDelegationsForDelegateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDelegationsForDelegate not implemented")
}
func (UnimplementedSubaccountServiceServer) VerifySubaccountAuthorization(context.Context, *VerifySubaccountAuthorizationRequest) (*VerifySubaccountAuthorizationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifySubaccountAuthorization not implemented")
}
func (UnimplementedSubaccountServiceServer) GetLatestFundingRates(context.Context, *GetLatestFundingRatesRequest) (*GetLatestFundingRatesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLatestFundingRates not implemented")
}
func (UnimplementedSubaccountServiceServer) GetFundingRateHistory(context.Context, *GetFundingRateHistoryRequest) (*GetFundingRateHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFundingRateHistory not implemented")
}
func (UnimplementedSubaccountServiceServer) GetFundingPayments(context.Context, *GetFundingPaymentsRequest) (*GetFundingPaymentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFundingPayments not implemented")
}
func (UnimplementedSubaccountServiceServer) GetPositionsBySymbol(context.Context, *GetPositionsBySymbolRequest) (*GetPositionsBySymbolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPositionsBySymbol not implemented")
}
func (UnimplementedSubaccountServiceServer) GetOITotalsBySymbol(context.Context, *GetOITotalsBySymbolRequest) (*GetOITotalsBySymbolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOITotalsBySymbol not implemented")
}
func (UnimplementedSubaccountServiceServer) GetAllOITotals(context.Context, *GetAllOITotalsRequest) (*GetAllOITotalsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllOITotals not implemented")
}
func (UnimplementedSubaccountServiceServer) GetPerformanceHistory(context.Context, *GetPerformanceHistoryRequest) (*GetPerformanceHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPerformanceHistory not implemented")
}
func (UnimplementedSubaccountServiceServer) UpdateSubaccountStatus(context.Context, *UpdateSubaccountStatusRequest) (*UpdateSubaccountStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSubaccountStatus not implemented")
}
func (UnimplementedSubaccountServiceServer) AddToWithdrawBlacklist(context.Context, *AddToWithdrawBlacklistRequest) (*AddToWithdrawBlacklistResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddToWithdrawBlacklist not implemented")
}
func (UnimplementedSubaccountServiceServer) ListWithdrawBlacklist(context.Context, *ListWithdrawBlacklistRequest) (*ListWithdrawBlacklistResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWithdrawBlacklist not implemented")
}
func (UnimplementedSubaccountServiceServer) RemoveFromWithdrawBlacklist(context.Context, *RemoveFromWithdrawBlacklistRequest) (*RemoveFromWithdrawBlacklistResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveFromWithdrawBlacklist not implemented")
}
func (UnimplementedSubaccountServiceServer) AssignWalletTier(context.Context, *AssignWalletTierRequest) (*AssignWalletTierResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AssignWalletTier not implemented")
}
func (UnimplementedSubaccountServiceServer) UnbrickPendingWithdraw(context.Context, *UnbrickPendingWithdrawRequest) (*UnbrickPendingWithdrawResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnbrickPendingWithdraw not implemented")
}
func (UnimplementedSubaccountServiceServer) GetInsuranceSubscription(context.Context, *GetInsuranceSubscriptionRequest) (*GetInsuranceSubscriptionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInsuranceSubscription not implemented")
}
func (UnimplementedSubaccountServiceServer) GetInsuranceProtection(context.Context, *GetInsuranceProtectionRequest) (*GetInsuranceProtectionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInsuranceProtection not implemented")
}
func (UnimplementedSubaccountServiceServer) CreateDefaultInsuranceSubscription(context.Context, *CreateDefaultInsuranceSubscriptionRequest) (*CreateDefaultInsuranceSubscriptionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDefaultInsuranceSubscription not implemented")
}
func (UnimplementedSubaccountServiceServer) GetBalanceUpdates(context.Context, *GetBalanceUpdatesRequest) (*GetBalanceUpdatesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBalanceUpdates not implemented")
}
func (UnimplementedSubaccountServiceServer) TransferBetweenSubAccounts(context.Context, *TransferBetweenSubAccountsRequest) (*TransferBetweenSubAccountsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TransferBetweenSubAccounts not implemented")
}
func (UnimplementedSubaccountServiceServer) GetTransfers(context.Context, *GetTransfersRequest) (*GetTransfersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTransfers not implemented")
}
func (UnimplementedSubaccountServiceServer) GetTradesForPosition(context.Context, *GetTradesForPositionRequest) (*GetTradesForPositionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTradesForPosition not implemented")
}
func (UnimplementedSubaccountServiceServer) GetSnaxpotNumberPreference(context.Context, *GetSnaxpotNumberPreferenceRequest) (*GetSnaxpotNumberPreferenceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSnaxpotNumberPreference not implemented")
}
func (UnimplementedSubaccountServiceServer) SetSnaxpotPreference(context.Context, *SetSnaxpotPreferenceRequest) (*SetSnaxpotPreferenceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetSnaxpotPreference not implemented")
}
func (UnimplementedSubaccountServiceServer) ClearSnaxpotPreference(context.Context, *ClearSnaxpotPreferenceRequest) (*ClearSnaxpotPreferenceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClearSnaxpotPreference not implemented")
}
func (UnimplementedSubaccountServiceServer) SaveSnaxpotTickets(context.Context, *SaveSnaxpotTicketsRequest) (*SaveSnaxpotTicketsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveSnaxpotTickets not implemented")
}
func (UnimplementedSubaccountServiceServer) GetSnaxpotTicketStatus(context.Context, *GetSnaxpotTicketStatusRequest) (*GetSnaxpotTicketStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSnaxpotTicketStatus not implemented")
}
func (UnimplementedSubaccountServiceServer) mustEmbedUnimplementedSubaccountServiceServer() {}
func (UnimplementedSubaccountServiceServer) testEmbeddedByValue()                           {}

// UnsafeSubaccountServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SubaccountServiceServer will
// result in compilation errors.
type UnsafeSubaccountServiceServer interface {
	mustEmbedUnimplementedSubaccountServiceServer()
}

func RegisterSubaccountServiceServer(s grpc.ServiceRegistrar, srv SubaccountServiceServer) {
	// If the following call panics, it indicates UnimplementedSubaccountServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SubaccountService_ServiceDesc, srv)
}

func _SubaccountService_CreateSubaccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSubaccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubaccountServiceServer).CreateSubaccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubaccountService_CreateSubaccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubaccountServiceServer).CreateSubaccount(ctx, req.(*CreateSubaccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubaccountService_UpdateSubaccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSubaccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubaccountServiceServer).UpdateSubaccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubaccountService_UpdateSubaccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubaccountServiceServer).UpdateSubaccount(ctx, req.(*UpdateSubaccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubaccountService_UpdateSubAccountMarketLeverage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSubAccountMarketLeverageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubaccountServiceServer).UpdateSubAccountMarketLeverage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubaccountService_UpdateSubAccountMarketLeverage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubaccountServiceServer).UpdateSubAccountMarketLeverage(ctx, req.(*UpdateSubAccountMarketLeverageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubaccountService_ListSubaccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSubaccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubaccountServiceServer).ListSubaccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubaccountService_ListSubaccounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubaccountServiceServer).ListSubaccounts(ctx, req.(*ListSubaccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubaccountService_GetSubaccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSubaccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubaccountServiceServer).GetSubaccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubaccountService_GetSubaccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubaccountServiceServer).GetSubaccount(ctx, req.(*GetSubaccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubaccountService_GetOrderHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubaccountServiceServer).GetOrderHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubaccountService_GetOrderHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubaccountServiceServer).GetOrderHistory(ctx, req.(*GetOrderHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubaccountService_GetTradeHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTradeHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubaccountServiceServer).GetTradeHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubaccountService_GetTradeHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubaccountServiceServer).GetTradeHistory(ctx, req.(*GetTradeHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubaccountService_GetLastTrades_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLastTradesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubaccountServiceServer).GetLastTrades(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubaccountService_GetLastTrades_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubaccountServiceServer).GetLastTrades(ctx, req.(*GetLastTradesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubaccountService_GetPositionHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPositionHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubaccountServiceServer).GetPositionHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubaccountService_GetPositionHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubaccountServiceServer).GetPositionHistory(ctx, req.(*GetPositionHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubaccountService_GetPositions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPositionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubaccountServiceServer).GetPositions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubaccountService_GetPositions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubaccountServiceServer).GetPositions(ctx, req.(*GetPositionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubaccountService_GetOpenOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOpenOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubaccountServiceServer).GetOpenOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubaccountService_GetOpenOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubaccountServiceServer).GetOpenOrders(ctx, req.(*GetOpenOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubaccountService_GetOpenLimitOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOpenLimitOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubaccountServiceServer).GetOpenLimitOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubaccountService_GetOpenLimitOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubaccountServiceServer).GetOpenLimitOrders(ctx, req.(*GetOpenLimitOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubaccountService_GetExpiredOpenOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExpiredOpenOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubaccountServiceServer).GetExpiredOpenOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubaccountService_GetExpiredOpenOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubaccountServiceServer).GetExpiredOpenOrders(ctx, req.(*GetExpiredOpenOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubaccountService_GetAllSubaccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllSubaccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubaccountServiceServer).GetAllSubaccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubaccountService_GetAllSubaccounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubaccountServiceServer).GetAllSubaccounts(ctx, req.(*GetAllSubaccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubaccountService_GetSLPMappings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSLPMappingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubaccountServiceServer).GetSLPMappings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubaccountService_GetSLPMappings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubaccountServiceServer).GetSLPMappings(ctx, req.(*GetSLPMappingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubaccountService_BatchUpdateLeverages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchUpdateLeveragesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubaccountServiceServer).BatchUpdateLeverages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubaccountService_BatchUpdateLeverages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubaccountServiceServer).BatchUpdateLeverages(ctx, req.(*BatchUpdateLeveragesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubaccountService_CreateDelegation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDelegationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubaccountServiceServer).CreateDelegation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubaccountService_CreateDelegation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubaccountServiceServer).CreateDelegation(ctx, req.(*CreateDelegationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubaccountService_RemoveDelegation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveDelegationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubaccountServiceServer).RemoveDelegation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubaccountService_RemoveDelegation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubaccountServiceServer).RemoveDelegation(ctx, req.(*RemoveDelegationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubaccountService_RemoveAllDelegations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveAllDelegationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubaccountServiceServer).RemoveAllDelegations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubaccountService_RemoveAllDelegations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubaccountServiceServer).RemoveAllDelegations(ctx, req.(*RemoveAllDelegationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubaccountService_GetDelegations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDelegationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubaccountServiceServer).GetDelegations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubaccountService_GetDelegations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubaccountServiceServer).GetDelegations(ctx, req.(*GetDelegationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubaccountService_GetDelegationsForDelegate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDelegationsForDelegateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubaccountServiceServer).GetDelegationsForDelegate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubaccountService_GetDelegationsForDelegate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubaccountServiceServer).GetDelegationsForDelegate(ctx, req.(*GetDelegationsForDelegateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubaccountService_VerifySubaccountAuthorization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifySubaccountAuthorizationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubaccountServiceServer).VerifySubaccountAuthorization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubaccountService_VerifySubaccountAuthorization_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubaccountServiceServer).VerifySubaccountAuthorization(ctx, req.(*VerifySubaccountAuthorizationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubaccountService_GetLatestFundingRates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLatestFundingRatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubaccountServiceServer).GetLatestFundingRates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubaccountService_GetLatestFundingRates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubaccountServiceServer).GetLatestFundingRates(ctx, req.(*GetLatestFundingRatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubaccountService_GetFundingRateHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFundingRateHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubaccountServiceServer).GetFundingRateHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubaccountService_GetFundingRateHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubaccountServiceServer).GetFundingRateHistory(ctx, req.(*GetFundingRateHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubaccountService_GetFundingPayments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFundingPaymentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubaccountServiceServer).GetFundingPayments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubaccountService_GetFundingPayments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubaccountServiceServer).GetFundingPayments(ctx, req.(*GetFundingPaymentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubaccountService_GetPositionsBySymbol_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPositionsBySymbolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubaccountServiceServer).GetPositionsBySymbol(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubaccountService_GetPositionsBySymbol_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubaccountServiceServer).GetPositionsBySymbol(ctx, req.(*GetPositionsBySymbolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubaccountService_GetOITotalsBySymbol_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOITotalsBySymbolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubaccountServiceServer).GetOITotalsBySymbol(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubaccountService_GetOITotalsBySymbol_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubaccountServiceServer).GetOITotalsBySymbol(ctx, req.(*GetOITotalsBySymbolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubaccountService_GetAllOITotals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllOITotalsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubaccountServiceServer).GetAllOITotals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubaccountService_GetAllOITotals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubaccountServiceServer).GetAllOITotals(ctx, req.(*GetAllOITotalsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubaccountService_GetPerformanceHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPerformanceHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubaccountServiceServer).GetPerformanceHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubaccountService_GetPerformanceHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubaccountServiceServer).GetPerformanceHistory(ctx, req.(*GetPerformanceHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubaccountService_UpdateSubaccountStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSubaccountStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubaccountServiceServer).UpdateSubaccountStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubaccountService_UpdateSubaccountStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubaccountServiceServer).UpdateSubaccountStatus(ctx, req.(*UpdateSubaccountStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubaccountService_AddToWithdrawBlacklist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddToWithdrawBlacklistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubaccountServiceServer).AddToWithdrawBlacklist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubaccountService_AddToWithdrawBlacklist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubaccountServiceServer).AddToWithdrawBlacklist(ctx, req.(*AddToWithdrawBlacklistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubaccountService_ListWithdrawBlacklist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWithdrawBlacklistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubaccountServiceServer).ListWithdrawBlacklist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubaccountService_ListWithdrawBlacklist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubaccountServiceServer).ListWithdrawBlacklist(ctx, req.(*ListWithdrawBlacklistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubaccountService_RemoveFromWithdrawBlacklist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveFromWithdrawBlacklistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubaccountServiceServer).RemoveFromWithdrawBlacklist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubaccountService_RemoveFromWithdrawBlacklist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubaccountServiceServer).RemoveFromWithdrawBlacklist(ctx, req.(*RemoveFromWithdrawBlacklistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubaccountService_AssignWalletTier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignWalletTierRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubaccountServiceServer).AssignWalletTier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubaccountService_AssignWalletTier_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubaccountServiceServer).AssignWalletTier(ctx, req.(*AssignWalletTierRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubaccountService_UnbrickPendingWithdraw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnbrickPendingWithdrawRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubaccountServiceServer).UnbrickPendingWithdraw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubaccountService_UnbrickPendingWithdraw_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubaccountServiceServer).UnbrickPendingWithdraw(ctx, req.(*UnbrickPendingWithdrawRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubaccountService_GetInsuranceSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInsuranceSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubaccountServiceServer).GetInsuranceSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubaccountService_GetInsuranceSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubaccountServiceServer).GetInsuranceSubscription(ctx, req.(*GetInsuranceSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubaccountService_GetInsuranceProtection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInsuranceProtectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubaccountServiceServer).GetInsuranceProtection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubaccountService_GetInsuranceProtection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubaccountServiceServer).GetInsuranceProtection(ctx, req.(*GetInsuranceProtectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubaccountService_CreateDefaultInsuranceSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDefaultInsuranceSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubaccountServiceServer).CreateDefaultInsuranceSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubaccountService_CreateDefaultInsuranceSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubaccountServiceServer).CreateDefaultInsuranceSubscription(ctx, req.(*CreateDefaultInsuranceSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubaccountService_GetBalanceUpdates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBalanceUpdatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubaccountServiceServer).GetBalanceUpdates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubaccountService_GetBalanceUpdates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubaccountServiceServer).GetBalanceUpdates(ctx, req.(*GetBalanceUpdatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubaccountService_TransferBetweenSubAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferBetweenSubAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubaccountServiceServer).TransferBetweenSubAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubaccountService_TransferBetweenSubAccounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubaccountServiceServer).TransferBetweenSubAccounts(ctx, req.(*TransferBetweenSubAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubaccountService_GetTransfers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransfersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubaccountServiceServer).GetTransfers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubaccountService_GetTransfers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubaccountServiceServer).GetTransfers(ctx, req.(*GetTransfersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubaccountService_GetTradesForPosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTradesForPositionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubaccountServiceServer).GetTradesForPosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubaccountService_GetTradesForPosition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubaccountServiceServer).GetTradesForPosition(ctx, req.(*GetTradesForPositionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubaccountService_GetSnaxpotNumberPreference_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSnaxpotNumberPreferenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubaccountServiceServer).GetSnaxpotNumberPreference(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubaccountService_GetSnaxpotNumberPreference_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubaccountServiceServer).GetSnaxpotNumberPreference(ctx, req.(*GetSnaxpotNumberPreferenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubaccountService_SetSnaxpotPreference_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetSnaxpotPreferenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubaccountServiceServer).SetSnaxpotPreference(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubaccountService_SetSnaxpotPreference_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubaccountServiceServer).SetSnaxpotPreference(ctx, req.(*SetSnaxpotPreferenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubaccountService_ClearSnaxpotPreference_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearSnaxpotPreferenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubaccountServiceServer).ClearSnaxpotPreference(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubaccountService_ClearSnaxpotPreference_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubaccountServiceServer).ClearSnaxpotPreference(ctx, req.(*ClearSnaxpotPreferenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubaccountService_SaveSnaxpotTickets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveSnaxpotTicketsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubaccountServiceServer).SaveSnaxpotTickets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubaccountService_SaveSnaxpotTickets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubaccountServiceServer).SaveSnaxpotTickets(ctx, req.(*SaveSnaxpotTicketsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubaccountService_GetSnaxpotTicketStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSnaxpotTicketStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubaccountServiceServer).GetSnaxpotTicketStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubaccountService_GetSnaxpotTicketStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubaccountServiceServer).GetSnaxpotTicketStatus(ctx, req.(*GetSnaxpotTicketStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SubaccountService_ServiceDesc is the grpc.ServiceDesc for SubaccountService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SubaccountService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "synthetix.v4_offchain.subaccount.SubaccountService",
	HandlerType: (*SubaccountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSubaccount",
			Handler:    _SubaccountService_CreateSubaccount_Handler,
		},
		{
			MethodName: "UpdateSubaccount",
			Handler:    _SubaccountService_UpdateSubaccount_Handler,
		},
		{
			MethodName: "UpdateSubAccountMarketLeverage",
			Handler:    _SubaccountService_UpdateSubAccountMarketLeverage_Handler,
		},
		{
			MethodName: "ListSubaccounts",
			Handler:    _SubaccountService_ListSubaccounts_Handler,
		},
		{
			MethodName: "GetSubaccount",
			Handler:    _SubaccountService_GetSubaccount_Handler,
		},
		{
			MethodName: "GetOrderHistory",
			Handler:    _SubaccountService_GetOrderHistory_Handler,
		},
		{
			MethodName: "GetTradeHistory",
			Handler:    _SubaccountService_GetTradeHistory_Handler,
		},
		{
			MethodName: "GetLastTrades",
			Handler:    _SubaccountService_GetLastTrades_Handler,
		},
		{
			MethodName: "GetPositionHistory",
			Handler:    _SubaccountService_GetPositionHistory_Handler,
		},
		{
			MethodName: "GetPositions",
			Handler:    _SubaccountService_GetPositions_Handler,
		},
		{
			MethodName: "GetOpenOrders",
			Handler:    _SubaccountService_GetOpenOrders_Handler,
		},
		{
			MethodName: "GetOpenLimitOrders",
			Handler:    _SubaccountService_GetOpenLimitOrders_Handler,
		},
		{
			MethodName: "GetExpiredOpenOrders",
			Handler:    _SubaccountService_GetExpiredOpenOrders_Handler,
		},
		{
			MethodName: "GetAllSubaccounts",
			Handler:    _SubaccountService_GetAllSubaccounts_Handler,
		},
		{
			MethodName: "GetSLPMappings",
			Handler:    _SubaccountService_GetSLPMappings_Handler,
		},
		{
			MethodName: "BatchUpdateLeverages",
			Handler:    _SubaccountService_BatchUpdateLeverages_Handler,
		},
		{
			MethodName: "CreateDelegation",
			Handler:    _SubaccountService_CreateDelegation_Handler,
		},
		{
			MethodName: "RemoveDelegation",
			Handler:    _SubaccountService_RemoveDelegation_Handler,
		},
		{
			MethodName: "RemoveAllDelegations",
			Handler:    _SubaccountService_RemoveAllDelegations_Handler,
		},
		{
			MethodName: "GetDelegations",
			Handler:    _SubaccountService_GetDelegations_Handler,
		},
		{
			MethodName: "GetDelegationsForDelegate",
			Handler:    _SubaccountService_GetDelegationsForDelegate_Handler,
		},
		{
			MethodName: "VerifySubaccountAuthorization",
			Handler:    _SubaccountService_VerifySubaccountAuthorization_Handler,
		},
		{
			MethodName: "GetLatestFundingRates",
			Handler:    _SubaccountService_GetLatestFundingRates_Handler,
		},
		{
			MethodName: "GetFundingRateHistory",
			Handler:    _SubaccountService_GetFundingRateHistory_Handler,
		},
		{
			MethodName: "GetFundingPayments",
			Handler:    _SubaccountService_GetFundingPayments_Handler,
		},
		{
			MethodName: "GetPositionsBySymbol",
			Handler:    _SubaccountService_GetPositionsBySymbol_Handler,
		},
		{
			MethodName: "GetOITotalsBySymbol",
			Handler:    _SubaccountService_GetOITotalsBySymbol_Handler,
		},
		{
			MethodName: "GetAllOITotals",
			Handler:    _SubaccountService_GetAllOITotals_Handler,
		},
		{
			MethodName: "GetPerformanceHistory",
			Handler:    _SubaccountService_GetPerformanceHistory_Handler,
		},
		{
			MethodName: "UpdateSubaccountStatus",
			Handler:    _SubaccountService_UpdateSubaccountStatus_Handler,
		},
		{
			MethodName: "AddToWithdrawBlacklist",
			Handler:    _SubaccountService_AddToWithdrawBlacklist_Handler,
		},
		{
			MethodName: "ListWithdrawBlacklist",
			Handler:    _SubaccountService_ListWithdrawBlacklist_Handler,
		},
		{
			MethodName: "RemoveFromWithdrawBlacklist",
			Handler:    _SubaccountService_RemoveFromWithdrawBlacklist_Handler,
		},
		{
			MethodName: "AssignWalletTier",
			Handler:    _SubaccountService_AssignWalletTier_Handler,
		},
		{
			MethodName: "UnbrickPendingWithdraw",
			Handler:    _SubaccountService_UnbrickPendingWithdraw_Handler,
		},
		{
			MethodName: "GetInsuranceSubscription",
			Handler:    _SubaccountService_GetInsuranceSubscription_Handler,
		},
		{
			MethodName: "GetInsuranceProtection",
			Handler:    _SubaccountService_GetInsuranceProtection_Handler,
		},
		{
			MethodName: "CreateDefaultInsuranceSubscription",
			Handler:    _SubaccountService_CreateDefaultInsuranceSubscription_Handler,
		},
		{
			MethodName: "GetBalanceUpdates",
			Handler:    _SubaccountService_GetBalanceUpdates_Handler,
		},
		{
			MethodName: "TransferBetweenSubAccounts",
			Handler:    _SubaccountService_TransferBetweenSubAccounts_Handler,
		},
		{
			MethodName: "GetTransfers",
			Handler:    _SubaccountService_GetTransfers_Handler,
		},
		{
			MethodName: "GetTradesForPosition",
			Handler:    _SubaccountService_GetTradesForPosition_Handler,
		},
		{
			MethodName: "GetSnaxpotNumberPreference",
			Handler:    _SubaccountService_GetSnaxpotNumberPreference_Handler,
		},
		{
			MethodName: "SetSnaxpotPreference",
			Handler:    _SubaccountService_SetSnaxpotPreference_Handler,
		},
		{
			MethodName: "ClearSnaxpotPreference",
			Handler:    _SubaccountService_ClearSnaxpotPreference_Handler,
		},
		{
			MethodName: "SaveSnaxpotTickets",
			Handler:    _SubaccountService_SaveSnaxpotTickets_Handler,
		},
		{
			MethodName: "GetSnaxpotTicketStatus",
			Handler:    _SubaccountService_GetSnaxpotTicketStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "subaccount.proto",
}
