// Proto definition for Synthetix V4-Offchain Trading Service
// To compile:
// protoc --go_out=. --go-grpc_out=. trading.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: trading.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TradingService_CancelAllOrders_FullMethodName        = "/synthetix.v4_offchain.trading.TradingService/CancelAllOrders"
	TradingService_CancelOrder_FullMethodName            = "/synthetix.v4_offchain.trading.TradingService/CancelOrder"
	TradingService_CancelOrderByCloid_FullMethodName     = "/synthetix.v4_offchain.trading.TradingService/CancelOrderByCloid"
	TradingService_ModifyOrder_FullMethodName            = "/synthetix.v4_offchain.trading.TradingService/ModifyOrder"
	TradingService_ModifyOrderByCloid_FullMethodName     = "/synthetix.v4_offchain.trading.TradingService/ModifyOrderByCloid"
	TradingService_PlaceBatchOrder_FullMethodName        = "/synthetix.v4_offchain.trading.TradingService/PlaceBatchOrder"
	TradingService_PlaceCompoundOrder_FullMethodName     = "/synthetix.v4_offchain.trading.TradingService/PlaceCompoundOrder"
	TradingService_PlacePositionTPAndSl_FullMethodName   = "/synthetix.v4_offchain.trading.TradingService/PlacePositionTPAndSl"
	TradingService_PlaceTWAPOrder_FullMethodName         = "/synthetix.v4_offchain.trading.TradingService/PlaceTWAPOrder"
	TradingService_ScheduleCancel_FullMethodName         = "/synthetix.v4_offchain.trading.TradingService/ScheduleCancel"
	TradingService_WithdrawCollateral_FullMethodName     = "/synthetix.v4_offchain.trading.TradingService/WithdrawCollateral"
	TradingService_VoluntaryAutoExchange_FullMethodName  = "/synthetix.v4_offchain.trading.TradingService/VoluntaryAutoExchange"
	TradingService_GetWithdrawableAmounts_FullMethodName = "/synthetix.v4_offchain.trading.TradingService/GetWithdrawableAmounts"
)

// TradingServiceClient is the client API for TradingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Provides an interface for interacting with offchain trading endpoints
type TradingServiceClient interface {
	CancelAllOrders(ctx context.Context, in *CancelAllOrdersRequest, opts ...grpc.CallOption) (*CancelAllOrdersResponse, error)
	CancelOrder(ctx context.Context, in *CancelOrderRequest, opts ...grpc.CallOption) (*CancelOrderResponse, error)
	CancelOrderByCloid(ctx context.Context, in *CancelOrderByCloidRequest, opts ...grpc.CallOption) (*CancelOrderResponse, error)
	ModifyOrder(ctx context.Context, in *ModifyOrderRequest, opts ...grpc.CallOption) (*ModifyOrderResponse, error)
	ModifyOrderByCloid(ctx context.Context, in *ModifyOrderByCloidRequest, opts ...grpc.CallOption) (*ModifyOrderResponse, error)
	PlaceBatchOrder(ctx context.Context, in *PlaceOrderRequest, opts ...grpc.CallOption) (*PlaceOrderResponse, error)
	PlaceCompoundOrder(ctx context.Context, in *PlaceOrderRequest, opts ...grpc.CallOption) (*PlaceOrderResponse, error)
	PlacePositionTPAndSl(ctx context.Context, in *PlaceOrderRequest, opts ...grpc.CallOption) (*PlaceOrderResponse, error)
	PlaceTWAPOrder(ctx context.Context, in *PlaceOrderRequest, opts ...grpc.CallOption) (*PlaceOrderResponse, error)
	ScheduleCancel(ctx context.Context, in *ScheduleCancelRequest, opts ...grpc.CallOption) (*ScheduleCancelResponse, error)
	WithdrawCollateral(ctx context.Context, in *WithdrawCollateralRequest, opts ...grpc.CallOption) (*WithdrawCollateralResponse, error)
	VoluntaryAutoExchange(ctx context.Context, in *VoluntaryAutoExchangeRequest, opts ...grpc.CallOption) (*VoluntaryAutoExchangeResponse, error)
	GetWithdrawableAmounts(ctx context.Context, in *GetWithdrawableAmountsRequest, opts ...grpc.CallOption) (*GetWithdrawableAmountsResponse, error)
}

type tradingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTradingServiceClient(cc grpc.ClientConnInterface) TradingServiceClient {
	return &tradingServiceClient{cc}
}

func (c *tradingServiceClient) CancelAllOrders(ctx context.Context, in *CancelAllOrdersRequest, opts ...grpc.CallOption) (*CancelAllOrdersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelAllOrdersResponse)
	err := c.cc.Invoke(ctx, TradingService_CancelAllOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradingServiceClient) CancelOrder(ctx context.Context, in *CancelOrderRequest, opts ...grpc.CallOption) (*CancelOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelOrderResponse)
	err := c.cc.Invoke(ctx, TradingService_CancelOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradingServiceClient) CancelOrderByCloid(ctx context.Context, in *CancelOrderByCloidRequest, opts ...grpc.CallOption) (*CancelOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelOrderResponse)
	err := c.cc.Invoke(ctx, TradingService_CancelOrderByCloid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradingServiceClient) ModifyOrder(ctx context.Context, in *ModifyOrderRequest, opts ...grpc.CallOption) (*ModifyOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModifyOrderResponse)
	err := c.cc.Invoke(ctx, TradingService_ModifyOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradingServiceClient) ModifyOrderByCloid(ctx context.Context, in *ModifyOrderByCloidRequest, opts ...grpc.CallOption) (*ModifyOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModifyOrderResponse)
	err := c.cc.Invoke(ctx, TradingService_ModifyOrderByCloid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradingServiceClient) PlaceBatchOrder(ctx context.Context, in *PlaceOrderRequest, opts ...grpc.CallOption) (*PlaceOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlaceOrderResponse)
	err := c.cc.Invoke(ctx, TradingService_PlaceBatchOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradingServiceClient) PlaceCompoundOrder(ctx context.Context, in *PlaceOrderRequest, opts ...grpc.CallOption) (*PlaceOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlaceOrderResponse)
	err := c.cc.Invoke(ctx, TradingService_PlaceCompoundOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradingServiceClient) PlacePositionTPAndSl(ctx context.Context, in *PlaceOrderRequest, opts ...grpc.CallOption) (*PlaceOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlaceOrderResponse)
	err := c.cc.Invoke(ctx, TradingService_PlacePositionTPAndSl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradingServiceClient) PlaceTWAPOrder(ctx context.Context, in *PlaceOrderRequest, opts ...grpc.CallOption) (*PlaceOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlaceOrderResponse)
	err := c.cc.Invoke(ctx, TradingService_PlaceTWAPOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradingServiceClient) ScheduleCancel(ctx context.Context, in *ScheduleCancelRequest, opts ...grpc.CallOption) (*ScheduleCancelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScheduleCancelResponse)
	err := c.cc.Invoke(ctx, TradingService_ScheduleCancel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradingServiceClient) WithdrawCollateral(ctx context.Context, in *WithdrawCollateralRequest, opts ...grpc.CallOption) (*WithdrawCollateralResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WithdrawCollateralResponse)
	err := c.cc.Invoke(ctx, TradingService_WithdrawCollateral_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradingServiceClient) VoluntaryAutoExchange(ctx context.Context, in *VoluntaryAutoExchangeRequest, opts ...grpc.CallOption) (*VoluntaryAutoExchangeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VoluntaryAutoExchangeResponse)
	err := c.cc.Invoke(ctx, TradingService_VoluntaryAutoExchange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradingServiceClient) GetWithdrawableAmounts(ctx context.Context, in *GetWithdrawableAmountsRequest, opts ...grpc.CallOption) (*GetWithdrawableAmountsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWithdrawableAmountsResponse)
	err := c.cc.Invoke(ctx, TradingService_GetWithdrawableAmounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TradingServiceServer is the server API for TradingService service.
// All implementations must embed UnimplementedTradingServiceServer
// for forward compatibility.
//
// Provides an interface for interacting with offchain trading endpoints
type TradingServiceServer interface {
	CancelAllOrders(context.Context, *CancelAllOrdersRequest) (*CancelAllOrdersResponse, error)
	CancelOrder(context.Context, *CancelOrderRequest) (*CancelOrderResponse, error)
	CancelOrderByCloid(context.Context, *CancelOrderByCloidRequest) (*CancelOrderResponse, error)
	ModifyOrder(context.Context, *ModifyOrderRequest) (*ModifyOrderResponse, error)
	ModifyOrderByCloid(context.Context, *ModifyOrderByCloidRequest) (*ModifyOrderResponse, error)
	PlaceBatchOrder(context.Context, *PlaceOrderRequest) (*PlaceOrderResponse, error)
	PlaceCompoundOrder(context.Context, *PlaceOrderRequest) (*PlaceOrderResponse, error)
	PlacePositionTPAndSl(context.Context, *PlaceOrderRequest) (*PlaceOrderResponse, error)
	PlaceTWAPOrder(context.Context, *PlaceOrderRequest) (*PlaceOrderResponse, error)
	ScheduleCancel(context.Context, *ScheduleCancelRequest) (*ScheduleCancelResponse, error)
	WithdrawCollateral(context.Context, *WithdrawCollateralRequest) (*WithdrawCollateralResponse, error)
	VoluntaryAutoExchange(context.Context, *VoluntaryAutoExchangeRequest) (*VoluntaryAutoExchangeResponse, error)
	GetWithdrawableAmounts(context.Context, *GetWithdrawableAmountsRequest) (*GetWithdrawableAmountsResponse, error)
	mustEmbedUnimplementedTradingServiceServer()
}

// UnimplementedTradingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTradingServiceServer struct{}

func (UnimplementedTradingServiceServer) CancelAllOrders(context.Context, *CancelAllOrdersRequest) (*CancelAllOrdersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelAllOrders not implemented")
}
func (UnimplementedTradingServiceServer) CancelOrder(context.Context, *CancelOrderRequest) (*CancelOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelOrder not implemented")
}
func (UnimplementedTradingServiceServer) CancelOrderByCloid(context.Context, *CancelOrderByCloidRequest) (*CancelOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelOrderByCloid not implemented")
}
func (UnimplementedTradingServiceServer) ModifyOrder(context.Context, *ModifyOrderRequest) (*ModifyOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ModifyOrder not implemented")
}
func (UnimplementedTradingServiceServer) ModifyOrderByCloid(context.Context, *ModifyOrderByCloidRequest) (*ModifyOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ModifyOrderByCloid not implemented")
}
func (UnimplementedTradingServiceServer) PlaceBatchOrder(context.Context, *PlaceOrderRequest) (*PlaceOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PlaceBatchOrder not implemented")
}
func (UnimplementedTradingServiceServer) PlaceCompoundOrder(context.Context, *PlaceOrderRequest) (*PlaceOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PlaceCompoundOrder not implemented")
}
func (UnimplementedTradingServiceServer) PlacePositionTPAndSl(context.Context, *PlaceOrderRequest) (*PlaceOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PlacePositionTPAndSl not implemented")
}
func (UnimplementedTradingServiceServer) PlaceTWAPOrder(context.Context, *PlaceOrderRequest) (*PlaceOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PlaceTWAPOrder not implemented")
}
func (UnimplementedTradingServiceServer) ScheduleCancel(context.Context, *ScheduleCancelRequest) (*ScheduleCancelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ScheduleCancel not implemented")
}
func (UnimplementedTradingServiceServer) WithdrawCollateral(context.Context, *WithdrawCollateralRequest) (*WithdrawCollateralResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WithdrawCollateral not implemented")
}
func (UnimplementedTradingServiceServer) VoluntaryAutoExchange(context.Context, *VoluntaryAutoExchangeRequest) (*VoluntaryAutoExchangeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VoluntaryAutoExchange not implemented")
}
func (UnimplementedTradingServiceServer) GetWithdrawableAmounts(context.Context, *GetWithdrawableAmountsRequest) (*GetWithdrawableAmountsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWithdrawableAmounts not implemented")
}
func (UnimplementedTradingServiceServer) mustEmbedUnimplementedTradingServiceServer() {}
func (UnimplementedTradingServiceServer) testEmbeddedByValue()                        {}

// UnsafeTradingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TradingServiceServer will
// result in compilation errors.
type UnsafeTradingServiceServer interface {
	mustEmbedUnimplementedTradingServiceServer()
}

func RegisterTradingServiceServer(s grpc.ServiceRegistrar, srv TradingServiceServer) {
	// If the following call panics, it indicates UnimplementedTradingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TradingService_ServiceDesc, srv)
}

func _TradingService_CancelAllOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelAllOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradingServiceServer).CancelAllOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradingService_CancelAllOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradingServiceServer).CancelAllOrders(ctx, req.(*CancelAllOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradingService_CancelOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradingServiceServer).CancelOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradingService_CancelOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradingServiceServer).CancelOrder(ctx, req.(*CancelOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradingService_CancelOrderByCloid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelOrderByCloidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradingServiceServer).CancelOrderByCloid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradingService_CancelOrderByCloid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradingServiceServer).CancelOrderByCloid(ctx, req.(*CancelOrderByCloidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradingService_ModifyOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifyOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradingServiceServer).ModifyOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradingService_ModifyOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradingServiceServer).ModifyOrder(ctx, req.(*ModifyOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradingService_ModifyOrderByCloid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifyOrderByCloidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradingServiceServer).ModifyOrderByCloid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradingService_ModifyOrderByCloid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradingServiceServer).ModifyOrderByCloid(ctx, req.(*ModifyOrderByCloidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradingService_PlaceBatchOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlaceOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradingServiceServer).PlaceBatchOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradingService_PlaceBatchOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradingServiceServer).PlaceBatchOrder(ctx, req.(*PlaceOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradingService_PlaceCompoundOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlaceOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradingServiceServer).PlaceCompoundOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradingService_PlaceCompoundOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradingServiceServer).PlaceCompoundOrder(ctx, req.(*PlaceOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradingService_PlacePositionTPAndSl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlaceOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradingServiceServer).PlacePositionTPAndSl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradingService_PlacePositionTPAndSl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradingServiceServer).PlacePositionTPAndSl(ctx, req.(*PlaceOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradingService_PlaceTWAPOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlaceOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradingServiceServer).PlaceTWAPOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradingService_PlaceTWAPOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradingServiceServer).PlaceTWAPOrder(ctx, req.(*PlaceOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradingService_ScheduleCancel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScheduleCancelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradingServiceServer).ScheduleCancel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradingService_ScheduleCancel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradingServiceServer).ScheduleCancel(ctx, req.(*ScheduleCancelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradingService_WithdrawCollateral_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithdrawCollateralRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradingServiceServer).WithdrawCollateral(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradingService_WithdrawCollateral_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradingServiceServer).WithdrawCollateral(ctx, req.(*WithdrawCollateralRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradingService_VoluntaryAutoExchange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoluntaryAutoExchangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradingServiceServer).VoluntaryAutoExchange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradingService_VoluntaryAutoExchange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradingServiceServer).VoluntaryAutoExchange(ctx, req.(*VoluntaryAutoExchangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradingService_GetWithdrawableAmounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWithdrawableAmountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradingServiceServer).GetWithdrawableAmounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradingService_GetWithdrawableAmounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradingServiceServer).GetWithdrawableAmounts(ctx, req.(*GetWithdrawableAmountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TradingService_ServiceDesc is the grpc.ServiceDesc for TradingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TradingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "synthetix.v4_offchain.trading.TradingService",
	HandlerType: (*TradingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CancelAllOrders",
			Handler:    _TradingService_CancelAllOrders_Handler,
		},
		{
			MethodName: "CancelOrder",
			Handler:    _TradingService_CancelOrder_Handler,
		},
		{
			MethodName: "CancelOrderByCloid",
			Handler:    _TradingService_CancelOrderByCloid_Handler,
		},
		{
			MethodName: "ModifyOrder",
			Handler:    _TradingService_ModifyOrder_Handler,
		},
		{
			MethodName: "ModifyOrderByCloid",
			Handler:    _TradingService_ModifyOrderByCloid_Handler,
		},
		{
			MethodName: "PlaceBatchOrder",
			Handler:    _TradingService_PlaceBatchOrder_Handler,
		},
		{
			MethodName: "PlaceCompoundOrder",
			Handler:    _TradingService_PlaceCompoundOrder_Handler,
		},
		{
			MethodName: "PlacePositionTPAndSl",
			Handler:    _TradingService_PlacePositionTPAndSl_Handler,
		},
		{
			MethodName: "PlaceTWAPOrder",
			Handler:    _TradingService_PlaceTWAPOrder_Handler,
		},
		{
			MethodName: "ScheduleCancel",
			Handler:    _TradingService_ScheduleCancel_Handler,
		},
		{
			MethodName: "WithdrawCollateral",
			Handler:    _TradingService_WithdrawCollateral_Handler,
		},
		{
			MethodName: "VoluntaryAutoExchange",
			Handler:    _TradingService_VoluntaryAutoExchange_Handler,
		},
		{
			MethodName: "GetWithdrawableAmounts",
			Handler:    _TradingService_GetWithdrawableAmounts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "trading.proto",
}
