// Proto definition for Synthetix V4-Offchain Trading Service
// To compile:
// protoc --go_out=. --go-grpc_out=. trading.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: trading.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Requests placement of one or more orders for a subaccount
type PlaceOrderRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	TmRequestedAt *timestamppb.Timestamp   `protobuf:"bytes,103,opt,name=tm_requested_at,json=tmRequestedAt,proto3" json:"tm_requested_at,omitempty"`
	SubAccountId  int64                    `protobuf:"varint,1,opt,name=sub_account_id,json=subAccountId,proto3" json:"sub_account_id,omitempty"`
	RequestId     string                   `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Orders        []*PlaceOrderRequestItem `protobuf:"bytes,3,rep,name=orders,proto3" json:"orders,omitempty"`
	Source        string                   `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceOrderRequest) Reset() {
	*x = PlaceOrderRequest{}
	mi := &file_trading_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceOrderRequest) ProtoMessage() {}

func (x *PlaceOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trading_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceOrderRequest.ProtoReflect.Descriptor instead.
func (*PlaceOrderRequest) Descriptor() ([]byte, []int) {
	return file_trading_proto_rawDescGZIP(), []int{0}
}

func (x *PlaceOrderRequest) GetTmRequestedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TmRequestedAt
	}
	return nil
}

func (x *PlaceOrderRequest) GetSubAccountId() int64 {
	if x != nil {
		return x.SubAccountId
	}
	return 0
}

func (x *PlaceOrderRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *PlaceOrderRequest) GetOrders() []*PlaceOrderRequestItem {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *PlaceOrderRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

// Represents a single order within a place order request
type PlaceOrderRequestItem struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Symbol           string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Side             Side                   `protobuf:"varint,2,opt,name=side,proto3,enum=synthetix.v4_offchain.common.Side" json:"side,omitempty"`
	Type             OrderType              `protobuf:"varint,3,opt,name=type,proto3,enum=synthetix.v4_offchain.common.OrderType" json:"type,omitempty"`
	TimeInForce      *TimeInForce           `protobuf:"varint,4,opt,name=time_in_force,json=timeInForce,proto3,enum=synthetix.v4_offchain.common.TimeInForce,oneof" json:"time_in_force,omitempty"`
	Quantity         string                 `protobuf:"bytes,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	ReduceOnly       bool                   `protobuf:"varint,6,opt,name=reduce_only,json=reduceOnly,proto3" json:"reduce_only,omitempty"`
	Price            *string                `protobuf:"bytes,7,opt,name=price,proto3,oneof" json:"price,omitempty"`
	NewClientOrderId *string                `protobuf:"bytes,8,opt,name=new_client_order_id,json=newClientOrderId,proto3,oneof" json:"new_client_order_id,omitempty"`
	TriggerPrice     *string                `protobuf:"bytes,9,opt,name=trigger_price,json=triggerPrice,proto3,oneof" json:"trigger_price,omitempty"`
	PostOnly         bool                   `protobuf:"varint,10,opt,name=post_only,json=postOnly,proto3" json:"post_only,omitempty"`
	ClosePosition    bool                   `protobuf:"varint,11,opt,name=close_position,json=closePosition,proto3" json:"close_position,omitempty"`
	TriggerPriceType string                 `protobuf:"bytes,12,opt,name=trigger_price_type,json=triggerPriceType,proto3" json:"trigger_price_type,omitempty"`
	TwapParams       *TWAPOrderRequest      `protobuf:"bytes,13,opt,name=twap_params,json=twapParams,proto3,oneof" json:"twap_params,omitempty"`
	ExpiresAt        *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=expires_at,json=expiresAt,proto3,oneof" json:"expires_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PlaceOrderRequestItem) Reset() {
	*x = PlaceOrderRequestItem{}
	mi := &file_trading_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceOrderRequestItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceOrderRequestItem) ProtoMessage() {}

func (x *PlaceOrderRequestItem) ProtoReflect() protoreflect.Message {
	mi := &file_trading_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceOrderRequestItem.ProtoReflect.Descriptor instead.
func (*PlaceOrderRequestItem) Descriptor() ([]byte, []int) {
	return file_trading_proto_rawDescGZIP(), []int{1}
}

func (x *PlaceOrderRequestItem) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *PlaceOrderRequestItem) GetSide() Side {
	if x != nil {
		return x.Side
	}
	return Side_BUY
}

func (x *PlaceOrderRequestItem) GetType() OrderType {
	if x != nil {
		return x.Type
	}
	return OrderType_LIMIT
}

func (x *PlaceOrderRequestItem) GetTimeInForce() TimeInForce {
	if x != nil && x.TimeInForce != nil {
		return *x.TimeInForce
	}
	return TimeInForce_GTC
}

func (x *PlaceOrderRequestItem) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

func (x *PlaceOrderRequestItem) GetReduceOnly() bool {
	if x != nil {
		return x.ReduceOnly
	}
	return false
}

func (x *PlaceOrderRequestItem) GetPrice() string {
	if x != nil && x.Price != nil {
		return *x.Price
	}
	return ""
}

func (x *PlaceOrderRequestItem) GetNewClientOrderId() string {
	if x != nil && x.NewClientOrderId != nil {
		return *x.NewClientOrderId
	}
	return ""
}

func (x *PlaceOrderRequestItem) GetTriggerPrice() string {
	if x != nil && x.TriggerPrice != nil {
		return *x.TriggerPrice
	}
	return ""
}

func (x *PlaceOrderRequestItem) GetPostOnly() bool {
	if x != nil {
		return x.PostOnly
	}
	return false
}

func (x *PlaceOrderRequestItem) GetClosePosition() bool {
	if x != nil {
		return x.ClosePosition
	}
	return false
}

func (x *PlaceOrderRequestItem) GetTriggerPriceType() string {
	if x != nil {
		return x.TriggerPriceType
	}
	return ""
}

func (x *PlaceOrderRequestItem) GetTwapParams() *TWAPOrderRequest {
	if x != nil {
		return x.TwapParams
	}
	return nil
}

func (x *PlaceOrderRequestItem) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

// TWAP order parameters
type TWAPOrderRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DurationSeconds int64                  `protobuf:"varint,1,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	IntervalSeconds int64                  `protobuf:"varint,2,opt,name=interval_seconds,json=intervalSeconds,proto3" json:"interval_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TWAPOrderRequest) Reset() {
	*x = TWAPOrderRequest{}
	mi := &file_trading_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TWAPOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TWAPOrderRequest) ProtoMessage() {}

func (x *TWAPOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trading_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TWAPOrderRequest.ProtoReflect.Descriptor instead.
func (*TWAPOrderRequest) Descriptor() ([]byte, []int) {
	return file_trading_proto_rawDescGZIP(), []int{2}
}

func (x *TWAPOrderRequest) GetDurationSeconds() int64 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *TWAPOrderRequest) GetIntervalSeconds() int64 {
	if x != nil {
		return x.IntervalSeconds
	}
	return 0
}

// Returns the results of a place order request
type PlaceOrderResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	TmRespondedAt *timestamppb.Timestamp    `protobuf:"bytes,104,opt,name=tm_responded_at,json=tmRespondedAt,proto3" json:"tm_responded_at,omitempty"`
	RequestId     string                    `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Orders        []*PlaceOrderResponseItem `protobuf:"bytes,2,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceOrderResponse) Reset() {
	*x = PlaceOrderResponse{}
	mi := &file_trading_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceOrderResponse) ProtoMessage() {}

func (x *PlaceOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trading_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceOrderResponse.ProtoReflect.Descriptor instead.
func (*PlaceOrderResponse) Descriptor() ([]byte, []int) {
	return file_trading_proto_rawDescGZIP(), []int{3}
}

func (x *PlaceOrderResponse) GetTmRespondedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TmRespondedAt
	}
	return nil
}

func (x *PlaceOrderResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *PlaceOrderResponse) GetOrders() []*PlaceOrderResponseItem {
	if x != nil {
		return x.Orders
	}
	return nil
}

// Represents a single order result within a place order response
type PlaceOrderResponseItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       *OrderId               `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	CumQty        string                 `protobuf:"bytes,2,opt,name=cum_qty,json=cumQty,proto3" json:"cum_qty,omitempty"`
	AvgPrice      string                 `protobuf:"bytes,3,opt,name=avg_price,json=avgPrice,proto3" json:"avg_price,omitempty"`
	OrigQty       string                 `protobuf:"bytes,4,opt,name=orig_qty,json=origQty,proto3" json:"orig_qty,omitempty"`
	Status        OrderStatus            `protobuf:"varint,5,opt,name=status,proto3,enum=synthetix.v4_offchain.common.OrderStatus" json:"status,omitempty"`
	Symbol        string                 `protobuf:"bytes,6,opt,name=symbol,proto3" json:"symbol,omitempty"`
	IsSuccess     bool                   `protobuf:"varint,7,opt,name=is_success,json=isSuccess,proto3" json:"is_success,omitempty"`
	Message       string                 `protobuf:"bytes,8,opt,name=message,proto3" json:"message,omitempty"`
	ErrorCode     *string                `protobuf:"bytes,9,opt,name=error_code,json=errorCode,proto3,oneof" json:"error_code,omitempty"` // Machine-readable error code for programmatic handling
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=expires_at,json=expiresAt,proto3,oneof" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceOrderResponseItem) Reset() {
	*x = PlaceOrderResponseItem{}
	mi := &file_trading_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceOrderResponseItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceOrderResponseItem) ProtoMessage() {}

func (x *PlaceOrderResponseItem) ProtoReflect() protoreflect.Message {
	mi := &file_trading_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceOrderResponseItem.ProtoReflect.Descriptor instead.
func (*PlaceOrderResponseItem) Descriptor() ([]byte, []int) {
	return file_trading_proto_rawDescGZIP(), []int{4}
}

func (x *PlaceOrderResponseItem) GetOrderId() *OrderId {
	if x != nil {
		return x.OrderId
	}
	return nil
}

func (x *PlaceOrderResponseItem) GetCumQty() string {
	if x != nil {
		return x.CumQty
	}
	return ""
}

func (x *PlaceOrderResponseItem) GetAvgPrice() string {
	if x != nil {
		return x.AvgPrice
	}
	return ""
}

func (x *PlaceOrderResponseItem) GetOrigQty() string {
	if x != nil {
		return x.OrigQty
	}
	return ""
}

func (x *PlaceOrderResponseItem) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_UNKNOWN
}

func (x *PlaceOrderResponseItem) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *PlaceOrderResponseItem) GetIsSuccess() bool {
	if x != nil {
		return x.IsSuccess
	}
	return false
}

func (x *PlaceOrderResponseItem) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PlaceOrderResponseItem) GetErrorCode() string {
	if x != nil && x.ErrorCode != nil {
		return *x.ErrorCode
	}
	return ""
}

func (x *PlaceOrderResponseItem) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

// Requests cancellation of one or more orders by venue order ID
type CancelOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TmRequestedAt *timestamppb.Timestamp `protobuf:"bytes,103,opt,name=tm_requested_at,json=tmRequestedAt,proto3" json:"tm_requested_at,omitempty"`
	SubAccountId  int64                  `protobuf:"varint,1,opt,name=sub_account_id,json=subAccountId,proto3" json:"sub_account_id,omitempty"`
	VenueOrderIds []uint64               `protobuf:"varint,2,rep,packed,name=venue_order_ids,json=venueOrderIds,proto3" json:"venue_order_ids,omitempty"`
	RequestId     string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderRequest) Reset() {
	*x = CancelOrderRequest{}
	mi := &file_trading_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderRequest) ProtoMessage() {}

func (x *CancelOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trading_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderRequest.ProtoReflect.Descriptor instead.
func (*CancelOrderRequest) Descriptor() ([]byte, []int) {
	return file_trading_proto_rawDescGZIP(), []int{5}
}

func (x *CancelOrderRequest) GetTmRequestedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TmRequestedAt
	}
	return nil
}

func (x *CancelOrderRequest) GetSubAccountId() int64 {
	if x != nil {
		return x.SubAccountId
	}
	return 0
}

func (x *CancelOrderRequest) GetVenueOrderIds() []uint64 {
	if x != nil {
		return x.VenueOrderIds
	}
	return nil
}

func (x *CancelOrderRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// Returns the results of a cancel order request
type CancelOrderResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	TmRespondedAt *timestamppb.Timestamp     `protobuf:"bytes,104,opt,name=tm_responded_at,json=tmRespondedAt,proto3" json:"tm_responded_at,omitempty"`
	RequestId     string                     `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Orders        []*CancelOrderResponseItem `protobuf:"bytes,2,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderResponse) Reset() {
	*x = CancelOrderResponse{}
	mi := &file_trading_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderResponse) ProtoMessage() {}

func (x *CancelOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trading_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderResponse.ProtoReflect.Descriptor instead.
func (*CancelOrderResponse) Descriptor() ([]byte, []int) {
	return file_trading_proto_rawDescGZIP(), []int{6}
}

func (x *CancelOrderResponse) GetTmRespondedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TmRespondedAt
	}
	return nil
}

func (x *CancelOrderResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CancelOrderResponse) GetOrders() []*CancelOrderResponseItem {
	if x != nil {
		return x.Orders
	}
	return nil
}

// Represents the result of a single order cancellation
type CancelOrderResponseItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       *OrderId               `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Symbol        string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	ErrorCode     *string                `protobuf:"bytes,4,opt,name=error_code,json=errorCode,proto3,oneof" json:"error_code,omitempty"` // Machine-readable error code for programmatic handling
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderResponseItem) Reset() {
	*x = CancelOrderResponseItem{}
	mi := &file_trading_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderResponseItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderResponseItem) ProtoMessage() {}

func (x *CancelOrderResponseItem) ProtoReflect() protoreflect.Message {
	mi := &file_trading_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderResponseItem.ProtoReflect.Descriptor instead.
func (*CancelOrderResponseItem) Descriptor() ([]byte, []int) {
	return file_trading_proto_rawDescGZIP(), []int{7}
}

func (x *CancelOrderResponseItem) GetOrderId() *OrderId {
	if x != nil {
		return x.OrderId
	}
	return nil
}

func (x *CancelOrderResponseItem) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *CancelOrderResponseItem) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *CancelOrderResponseItem) GetErrorCode() string {
	if x != nil && x.ErrorCode != nil {
		return *x.ErrorCode
	}
	return ""
}

// Requests cancellation of all orders, optionally filtered by symbols
type CancelAllOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TmRequestedAt *timestamppb.Timestamp `protobuf:"bytes,103,opt,name=tm_requested_at,json=tmRequestedAt,proto3" json:"tm_requested_at,omitempty"`
	SubAccountId  int64                  `protobuf:"varint,1,opt,name=sub_account_id,json=subAccountId,proto3" json:"sub_account_id,omitempty"`
	Symbols       []string               `protobuf:"bytes,2,rep,name=symbols,proto3" json:"symbols,omitempty"`
	RequestId     string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelAllOrdersRequest) Reset() {
	*x = CancelAllOrdersRequest{}
	mi := &file_trading_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelAllOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelAllOrdersRequest) ProtoMessage() {}

func (x *CancelAllOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trading_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelAllOrdersRequest.ProtoReflect.Descriptor instead.
func (*CancelAllOrdersRequest) Descriptor() ([]byte, []int) {
	return file_trading_proto_rawDescGZIP(), []int{8}
}

func (x *CancelAllOrdersRequest) GetTmRequestedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TmRequestedAt
	}
	return nil
}

func (x *CancelAllOrdersRequest) GetSubAccountId() int64 {
	if x != nil {
		return x.SubAccountId
	}
	return 0
}

func (x *CancelAllOrdersRequest) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

func (x *CancelAllOrdersRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// Returns the results of a cancel-all-orders request
type CancelAllOrdersResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	TmRespondedAt *timestamppb.Timestamp     `protobuf:"bytes,104,opt,name=tm_responded_at,json=tmRespondedAt,proto3" json:"tm_responded_at,omitempty"`
	RequestId     string                     `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Orders        []*CancelOrderResponseItem `protobuf:"bytes,2,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelAllOrdersResponse) Reset() {
	*x = CancelAllOrdersResponse{}
	mi := &file_trading_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelAllOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelAllOrdersResponse) ProtoMessage() {}

func (x *CancelAllOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trading_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelAllOrdersResponse.ProtoReflect.Descriptor instead.
func (*CancelAllOrdersResponse) Descriptor() ([]byte, []int) {
	return file_trading_proto_rawDescGZIP(), []int{9}
}

func (x *CancelAllOrdersResponse) GetTmRespondedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TmRespondedAt
	}
	return nil
}

func (x *CancelAllOrdersResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CancelAllOrdersResponse) GetOrders() []*CancelOrderResponseItem {
	if x != nil {
		return x.Orders
	}
	return nil
}

// Sets or clears a dead-man-switch cancellation deadline for a subaccount.
type ScheduleCancelRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TmRequestedAt  *timestamppb.Timestamp `protobuf:"bytes,103,opt,name=tm_requested_at,json=tmRequestedAt,proto3" json:"tm_requested_at,omitempty"`
	SubAccountId   int64                  `protobuf:"varint,1,opt,name=sub_account_id,json=subAccountId,proto3" json:"sub_account_id,omitempty"`
	RequestId      string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	TimeoutSeconds int64                  `protobuf:"varint,3,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ScheduleCancelRequest) Reset() {
	*x = ScheduleCancelRequest{}
	mi := &file_trading_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleCancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleCancelRequest) ProtoMessage() {}

func (x *ScheduleCancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trading_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleCancelRequest.ProtoReflect.Descriptor instead.
func (*ScheduleCancelRequest) Descriptor() ([]byte, []int) {
	return file_trading_proto_rawDescGZIP(), []int{10}
}

func (x *ScheduleCancelRequest) GetTmRequestedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TmRequestedAt
	}
	return nil
}

func (x *ScheduleCancelRequest) GetSubAccountId() int64 {
	if x != nil {
		return x.SubAccountId
	}
	return 0
}

func (x *ScheduleCancelRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ScheduleCancelRequest) GetTimeoutSeconds() int64 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

// Returns the active dead-man-switch cancellation deadline for a subaccount.
type ScheduleCancelResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TmRespondedAt  *timestamppb.Timestamp `protobuf:"bytes,104,opt,name=tm_responded_at,json=tmRespondedAt,proto3" json:"tm_responded_at,omitempty"`
	RequestId      string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	IsActive       bool                   `protobuf:"varint,2,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	TimeoutSeconds int64                  `protobuf:"varint,3,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	TriggerTime    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=trigger_time,json=triggerTime,proto3" json:"trigger_time,omitempty"`
	Message        string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ScheduleCancelResponse) Reset() {
	*x = ScheduleCancelResponse{}
	mi := &file_trading_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleCancelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleCancelResponse) ProtoMessage() {}

func (x *ScheduleCancelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trading_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleCancelResponse.ProtoReflect.Descriptor instead.
func (*ScheduleCancelResponse) Descriptor() ([]byte, []int) {
	return file_trading_proto_rawDescGZIP(), []int{11}
}

func (x *ScheduleCancelResponse) GetTmRespondedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TmRespondedAt
	}
	return nil
}

func (x *ScheduleCancelResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ScheduleCancelResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *ScheduleCancelResponse) GetTimeoutSeconds() int64 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *ScheduleCancelResponse) GetTriggerTime() *timestamppb.Timestamp {
	if x != nil {
		return x.TriggerTime
	}
	return nil
}

func (x *ScheduleCancelResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Requests cancellation of one or more orders by client order ID
type CancelOrderByCloidRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TmRequestedAt  *timestamppb.Timestamp `protobuf:"bytes,103,opt,name=tm_requested_at,json=tmRequestedAt,proto3" json:"tm_requested_at,omitempty"`
	SubAccountId   int64                  `protobuf:"varint,1,opt,name=sub_account_id,json=subAccountId,proto3" json:"sub_account_id,omitempty"`
	ClientOrderIds []string               `protobuf:"bytes,2,rep,name=client_order_ids,json=clientOrderIds,proto3" json:"client_order_ids,omitempty"`
	RequestId      string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CancelOrderByCloidRequest) Reset() {
	*x = CancelOrderByCloidRequest{}
	mi := &file_trading_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderByCloidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderByCloidRequest) ProtoMessage() {}

func (x *CancelOrderByCloidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trading_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderByCloidRequest.ProtoReflect.Descriptor instead.
func (*CancelOrderByCloidRequest) Descriptor() ([]byte, []int) {
	return file_trading_proto_rawDescGZIP(), []int{12}
}

func (x *CancelOrderByCloidRequest) GetTmRequestedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TmRequestedAt
	}
	return nil
}

func (x *CancelOrderByCloidRequest) GetSubAccountId() int64 {
	if x != nil {
		return x.SubAccountId
	}
	return 0
}

func (x *CancelOrderByCloidRequest) GetClientOrderIds() []string {
	if x != nil {
		return x.ClientOrderIds
	}
	return nil
}

func (x *CancelOrderByCloidRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// Requests modification of an existing order's quantity, price, or trigger price
type ModifyOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TmRequestedAt *timestamppb.Timestamp `protobuf:"bytes,103,opt,name=tm_requested_at,json=tmRequestedAt,proto3" json:"tm_requested_at,omitempty"`
	SubAccountId  int64                  `protobuf:"varint,1,opt,name=sub_account_id,json=subAccountId,proto3" json:"sub_account_id,omitempty"`
	VenueOrderId  uint64                 `protobuf:"varint,2,opt,name=venue_order_id,json=venueOrderId,proto3" json:"venue_order_id,omitempty"`
	Quantity      *string                `protobuf:"bytes,3,opt,name=quantity,proto3,oneof" json:"quantity,omitempty"`
	Price         *string                `protobuf:"bytes,4,opt,name=price,proto3,oneof" json:"price,omitempty"`
	RequestId     string                 `protobuf:"bytes,5,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	TriggerPrice  *string                `protobuf:"bytes,6,opt,name=trigger_price,json=triggerPrice,proto3,oneof" json:"trigger_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModifyOrderRequest) Reset() {
	*x = ModifyOrderRequest{}
	mi := &file_trading_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModifyOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyOrderRequest) ProtoMessage() {}

func (x *ModifyOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trading_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyOrderRequest.ProtoReflect.Descriptor instead.
func (*ModifyOrderRequest) Descriptor() ([]byte, []int) {
	return file_trading_proto_rawDescGZIP(), []int{13}
}

func (x *ModifyOrderRequest) GetTmRequestedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TmRequestedAt
	}
	return nil
}

func (x *ModifyOrderRequest) GetSubAccountId() int64 {
	if x != nil {
		return x.SubAccountId
	}
	return 0
}

func (x *ModifyOrderRequest) GetVenueOrderId() uint64 {
	if x != nil {
		return x.VenueOrderId
	}
	return 0
}

func (x *ModifyOrderRequest) GetQuantity() string {
	if x != nil && x.Quantity != nil {
		return *x.Quantity
	}
	return ""
}

func (x *ModifyOrderRequest) GetPrice() string {
	if x != nil && x.Price != nil {
		return *x.Price
	}
	return ""
}

func (x *ModifyOrderRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ModifyOrderRequest) GetTriggerPrice() string {
	if x != nil && x.TriggerPrice != nil {
		return *x.TriggerPrice
	}
	return ""
}

// Returns the result of an order modification request
type ModifyOrderResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TmRespondedAt     *timestamppb.Timestamp `protobuf:"bytes,104,opt,name=tm_responded_at,json=tmRespondedAt,proto3" json:"tm_responded_at,omitempty"`
	OrderId           *OrderId               `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	RequestId         string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Quantity          *string                `protobuf:"bytes,3,opt,name=quantity,proto3,oneof" json:"quantity,omitempty"`
	Price             *string                `protobuf:"bytes,4,opt,name=price,proto3,oneof" json:"price,omitempty"`
	TriggerPrice      *string                `protobuf:"bytes,5,opt,name=trigger_price,json=triggerPrice,proto3,oneof" json:"trigger_price,omitempty"`
	Status            OrderStatus            `protobuf:"varint,6,opt,name=status,proto3,enum=synthetix.v4_offchain.common.OrderStatus" json:"status,omitempty"`
	CumulativeFillQty *string                `protobuf:"bytes,7,opt,name=cumulative_fill_qty,json=cumulativeFillQty,proto3,oneof" json:"cumulative_fill_qty,omitempty"`
	AveragePrice      *string                `protobuf:"bytes,8,opt,name=average_price,json=averagePrice,proto3,oneof" json:"average_price,omitempty"`
	ErrorCode         *string                `protobuf:"bytes,9,opt,name=error_code,json=errorCode,proto3,oneof" json:"error_code,omitempty"`           // Machine-readable error code for programmatic handling
	ErrorMessage      *string                `protobuf:"bytes,10,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"` // Human-readable error message
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ModifyOrderResponse) Reset() {
	*x = ModifyOrderResponse{}
	mi := &file_trading_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModifyOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyOrderResponse) ProtoMessage() {}

func (x *ModifyOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trading_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyOrderResponse.ProtoReflect.Descriptor instead.
func (*ModifyOrderResponse) Descriptor() ([]byte, []int) {
	return file_trading_proto_rawDescGZIP(), []int{14}
}

func (x *ModifyOrderResponse) GetTmRespondedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TmRespondedAt
	}
	return nil
}

func (x *ModifyOrderResponse) GetOrderId() *OrderId {
	if x != nil {
		return x.OrderId
	}
	return nil
}

func (x *ModifyOrderResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ModifyOrderResponse) GetQuantity() string {
	if x != nil && x.Quantity != nil {
		return *x.Quantity
	}
	return ""
}

func (x *ModifyOrderResponse) GetPrice() string {
	if x != nil && x.Price != nil {
		return *x.Price
	}
	return ""
}

func (x *ModifyOrderResponse) GetTriggerPrice() string {
	if x != nil && x.TriggerPrice != nil {
		return *x.TriggerPrice
	}
	return ""
}

func (x *ModifyOrderResponse) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_UNKNOWN
}

func (x *ModifyOrderResponse) GetCumulativeFillQty() string {
	if x != nil && x.CumulativeFillQty != nil {
		return *x.CumulativeFillQty
	}
	return ""
}

func (x *ModifyOrderResponse) GetAveragePrice() string {
	if x != nil && x.AveragePrice != nil {
		return *x.AveragePrice
	}
	return ""
}

func (x *ModifyOrderResponse) GetErrorCode() string {
	if x != nil && x.ErrorCode != nil {
		return *x.ErrorCode
	}
	return ""
}

func (x *ModifyOrderResponse) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

// Requests modification of an existing order by client order ID
type ModifyOrderByCloidRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TmRequestedAt *timestamppb.Timestamp `protobuf:"bytes,103,opt,name=tm_requested_at,json=tmRequestedAt,proto3" json:"tm_requested_at,omitempty"`
	SubAccountId  int64                  `protobuf:"varint,1,opt,name=sub_account_id,json=subAccountId,proto3" json:"sub_account_id,omitempty"`
	ClientOrderId string                 `protobuf:"bytes,2,opt,name=client_order_id,json=clientOrderId,proto3" json:"client_order_id,omitempty"`
	Quantity      *string                `protobuf:"bytes,3,opt,name=quantity,proto3,oneof" json:"quantity,omitempty"`
	Price         *string                `protobuf:"bytes,4,opt,name=price,proto3,oneof" json:"price,omitempty"`
	RequestId     string                 `protobuf:"bytes,5,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	TriggerPrice  *string                `protobuf:"bytes,6,opt,name=trigger_price,json=triggerPrice,proto3,oneof" json:"trigger_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModifyOrderByCloidRequest) Reset() {
	*x = ModifyOrderByCloidRequest{}
	mi := &file_trading_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModifyOrderByCloidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyOrderByCloidRequest) ProtoMessage() {}

func (x *ModifyOrderByCloidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trading_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyOrderByCloidRequest.ProtoReflect.Descriptor instead.
func (*ModifyOrderByCloidRequest) Descriptor() ([]byte, []int) {
	return file_trading_proto_rawDescGZIP(), []int{15}
}

func (x *ModifyOrderByCloidRequest) GetTmRequestedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TmRequestedAt
	}
	return nil
}

func (x *ModifyOrderByCloidRequest) GetSubAccountId() int64 {
	if x != nil {
		return x.SubAccountId
	}
	return 0
}

func (x *ModifyOrderByCloidRequest) GetClientOrderId() string {
	if x != nil {
		return x.ClientOrderId
	}
	return ""
}

func (x *ModifyOrderByCloidRequest) GetQuantity() string {
	if x != nil && x.Quantity != nil {
		return *x.Quantity
	}
	return ""
}

func (x *ModifyOrderByCloidRequest) GetPrice() string {
	if x != nil && x.Price != nil {
		return *x.Price
	}
	return ""
}

func (x *ModifyOrderByCloidRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ModifyOrderByCloidRequest) GetTriggerPrice() string {
	if x != nil && x.TriggerPrice != nil {
		return *x.TriggerPrice
	}
	return ""
}

// Requests a collateral withdrawal to a destination wallet
type WithdrawCollateralRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TmRequestedAt *timestamppb.Timestamp `protobuf:"bytes,103,opt,name=tm_requested_at,json=tmRequestedAt,proto3" json:"tm_requested_at,omitempty"`
	SubAccountId  int64                  `protobuf:"varint,1,opt,name=sub_account_id,json=subAccountId,proto3" json:"sub_account_id,omitempty"` // Required: subaccount ID
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`                                    // Required: token symbol (e.g., "USDT", "WETH")
	Amount        string                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`                                    // Required: amount to withdraw
	Destination   string                 `protobuf:"bytes,4,opt,name=destination,proto3" json:"destination,omitempty"`                          // Required: destination wallet address
	RequestId     string                 `protobuf:"bytes,5,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`             // Required: request ID from API for correlation
	WalletAddress string                 `protobuf:"bytes,6,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"` // Required: authenticated user's wallet address
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithdrawCollateralRequest) Reset() {
	*x = WithdrawCollateralRequest{}
	mi := &file_trading_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawCollateralRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawCollateralRequest) ProtoMessage() {}

func (x *WithdrawCollateralRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trading_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawCollateralRequest.ProtoReflect.Descriptor instead.
func (*WithdrawCollateralRequest) Descriptor() ([]byte, []int) {
	return file_trading_proto_rawDescGZIP(), []int{16}
}

func (x *WithdrawCollateralRequest) GetTmRequestedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TmRequestedAt
	}
	return nil
}

func (x *WithdrawCollateralRequest) GetSubAccountId() int64 {
	if x != nil {
		return x.SubAccountId
	}
	return 0
}

func (x *WithdrawCollateralRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *WithdrawCollateralRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *WithdrawCollateralRequest) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *WithdrawCollateralRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *WithdrawCollateralRequest) GetWalletAddress() string {
	if x != nil {
		return x.WalletAddress
	}
	return ""
}

// Returns the result of a collateral withdrawal request
type WithdrawCollateralResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TmRespondedAt *timestamppb.Timestamp `protobuf:"bytes,104,opt,name=tm_responded_at,json=tmRespondedAt,proto3" json:"tm_responded_at,omitempty"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // Unique withdrawal request ID
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`                        // Token symbol
	Amount        string                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`                        // Amount withdrawn
	Destination   string                 `protobuf:"bytes,4,opt,name=destination,proto3" json:"destination,omitempty"`              // Destination address
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithdrawCollateralResponse) Reset() {
	*x = WithdrawCollateralResponse{}
	mi := &file_trading_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawCollateralResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawCollateralResponse) ProtoMessage() {}

func (x *WithdrawCollateralResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trading_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawCollateralResponse.ProtoReflect.Descriptor instead.
func (*WithdrawCollateralResponse) Descriptor() ([]byte, []int) {
	return file_trading_proto_rawDescGZIP(), []int{17}
}

func (x *WithdrawCollateralResponse) GetTmRespondedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TmRespondedAt
	}
	return nil
}

func (x *WithdrawCollateralResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *WithdrawCollateralResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *WithdrawCollateralResponse) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *WithdrawCollateralResponse) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

// Requests a voluntary exchange of collateral to USDT
type VoluntaryAutoExchangeRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TmRequestedAt    *timestamppb.Timestamp `protobuf:"bytes,103,opt,name=tm_requested_at,json=tmRequestedAt,proto3" json:"tm_requested_at,omitempty"`
	SubAccountId     int64                  `protobuf:"varint,1,opt,name=sub_account_id,json=subAccountId,proto3" json:"sub_account_id,omitempty"`            // Required: subaccount ID
	TargetUsdtAmount string                 `protobuf:"bytes,2,opt,name=target_usdt_amount,json=targetUsdtAmount,proto3" json:"target_usdt_amount,omitempty"` // Required: target USDT amount to reach
	SourceAsset      string                 `protobuf:"bytes,3,opt,name=source_asset,json=sourceAsset,proto3" json:"source_asset,omitempty"`                  // Required: source asset to convert (e.g., "WETH")
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *VoluntaryAutoExchangeRequest) Reset() {
	*x = VoluntaryAutoExchangeRequest{}
	mi := &file_trading_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoluntaryAutoExchangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoluntaryAutoExchangeRequest) ProtoMessage() {}

func (x *VoluntaryAutoExchangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trading_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoluntaryAutoExchangeRequest.ProtoReflect.Descriptor instead.
func (*VoluntaryAutoExchangeRequest) Descriptor() ([]byte, []int) {
	return file_trading_proto_rawDescGZIP(), []int{18}
}

func (x *VoluntaryAutoExchangeRequest) GetTmRequestedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TmRequestedAt
	}
	return nil
}

func (x *VoluntaryAutoExchangeRequest) GetSubAccountId() int64 {
	if x != nil {
		return x.SubAccountId
	}
	return 0
}

func (x *VoluntaryAutoExchangeRequest) GetTargetUsdtAmount() string {
	if x != nil {
		return x.TargetUsdtAmount
	}
	return ""
}

func (x *VoluntaryAutoExchangeRequest) GetSourceAsset() string {
	if x != nil {
		return x.SourceAsset
	}
	return ""
}

// Represents a single collateral symbol and quantity
type CollateralItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`     // Collateral symbol (e.g., "WETH", "USDT")
	Quantity      string                 `protobuf:"bytes,2,opt,name=quantity,proto3" json:"quantity,omitempty"` // Quantity of the collateral
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollateralItem) Reset() {
	*x = CollateralItem{}
	mi := &file_trading_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollateralItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollateralItem) ProtoMessage() {}

func (x *CollateralItem) ProtoReflect() protoreflect.Message {
	mi := &file_trading_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollateralItem.ProtoReflect.Descriptor instead.
func (*CollateralItem) Descriptor() ([]byte, []int) {
	return file_trading_proto_rawDescGZIP(), []int{19}
}

func (x *CollateralItem) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *CollateralItem) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

// Returns the result of a voluntary auto-exchange
type VoluntaryAutoExchangeResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TmRespondedAt     *timestamppb.Timestamp `protobuf:"bytes,104,opt,name=tm_responded_at,json=tmRespondedAt,proto3" json:"tm_responded_at,omitempty"`
	SubAccountId      int64                  `protobuf:"varint,1,opt,name=sub_account_id,json=subAccountId,proto3" json:"sub_account_id,omitempty"`               // Subaccount ID
	SourceAsset       string                 `protobuf:"bytes,2,opt,name=source_asset,json=sourceAsset,proto3" json:"source_asset,omitempty"`                     // Source asset that was converted
	SourceAmountTaken string                 `protobuf:"bytes,3,opt,name=source_amount_taken,json=sourceAmountTaken,proto3" json:"source_amount_taken,omitempty"` // Amount of source asset taken
	TargetAsset       string                 `protobuf:"bytes,4,opt,name=target_asset,json=targetAsset,proto3" json:"target_asset,omitempty"`                     // Target asset (always "USDT")
	TargetAmount      string                 `protobuf:"bytes,5,opt,name=target_amount,json=targetAmount,proto3" json:"target_amount,omitempty"`                  // Target USDT amount received
	IndexPrice        string                 `protobuf:"bytes,6,opt,name=index_price,json=indexPrice,proto3" json:"index_price,omitempty"`                        // Index price used for conversion
	EffectiveHaircut  string                 `protobuf:"bytes,7,opt,name=effective_haircut,json=effectiveHaircut,proto3" json:"effective_haircut,omitempty"`      // Effective haircut/fee applied
	Collateral        []*CollateralItem      `protobuf:"bytes,8,rep,name=collateral,proto3" json:"collateral,omitempty"`                                          // Updated collateral balances
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *VoluntaryAutoExchangeResponse) Reset() {
	*x = VoluntaryAutoExchangeResponse{}
	mi := &file_trading_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoluntaryAutoExchangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoluntaryAutoExchangeResponse) ProtoMessage() {}

func (x *VoluntaryAutoExchangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trading_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoluntaryAutoExchangeResponse.ProtoReflect.Descriptor instead.
func (*VoluntaryAutoExchangeResponse) Descriptor() ([]byte, []int) {
	return file_trading_proto_rawDescGZIP(), []int{20}
}

func (x *VoluntaryAutoExchangeResponse) GetTmRespondedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TmRespondedAt
	}
	return nil
}

func (x *VoluntaryAutoExchangeResponse) GetSubAccountId() int64 {
	if x != nil {
		return x.SubAccountId
	}
	return 0
}

func (x *VoluntaryAutoExchangeResponse) GetSourceAsset() string {
	if x != nil {
		return x.SourceAsset
	}
	return ""
}

func (x *VoluntaryAutoExchangeResponse) GetSourceAmountTaken() string {
	if x != nil {
		return x.SourceAmountTaken
	}
	return ""
}

func (x *VoluntaryAutoExchangeResponse) GetTargetAsset() string {
	if x != nil {
		return x.TargetAsset
	}
	return ""
}

func (x *VoluntaryAutoExchangeResponse) GetTargetAmount() string {
	if x != nil {
		return x.TargetAmount
	}
	return ""
}

func (x *VoluntaryAutoExchangeResponse) GetIndexPrice() string {
	if x != nil {
		return x.IndexPrice
	}
	return ""
}

func (x *VoluntaryAutoExchangeResponse) GetEffectiveHaircut() string {
	if x != nil {
		return x.EffectiveHaircut
	}
	return ""
}

func (x *VoluntaryAutoExchangeResponse) GetCollateral() []*CollateralItem {
	if x != nil {
		return x.Collateral
	}
	return nil
}

// Queries per-asset withdrawable amounts for a subaccount.
// Read-only query — no state mutations occur.
// Unknown symbols silently return zero values.
type GetWithdrawableAmountsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TmRequestedAt *timestamppb.Timestamp `protobuf:"bytes,103,opt,name=tm_requested_at,json=tmRequestedAt,proto3" json:"tm_requested_at,omitempty"`
	SubAccountId  int64                  `protobuf:"varint,1,opt,name=sub_account_id,json=subAccountId,proto3" json:"sub_account_id,omitempty"` // Required: subaccount ID
	Symbols       []string               `protobuf:"bytes,2,rep,name=symbols,proto3" json:"symbols,omitempty"`                                  // Required: collateral symbols to query (e.g., ["USDT", "WETH"])
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWithdrawableAmountsRequest) Reset() {
	*x = GetWithdrawableAmountsRequest{}
	mi := &file_trading_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWithdrawableAmountsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWithdrawableAmountsRequest) ProtoMessage() {}

func (x *GetWithdrawableAmountsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trading_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWithdrawableAmountsRequest.ProtoReflect.Descriptor instead.
func (*GetWithdrawableAmountsRequest) Descriptor() ([]byte, []int) {
	return file_trading_proto_rawDescGZIP(), []int{21}
}

func (x *GetWithdrawableAmountsRequest) GetTmRequestedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TmRequestedAt
	}
	return nil
}

func (x *GetWithdrawableAmountsRequest) GetSubAccountId() int64 {
	if x != nil {
		return x.SubAccountId
	}
	return 0
}

func (x *GetWithdrawableAmountsRequest) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

// Per-asset withdrawable amount information
type WithdrawableAmountItem struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Symbol             string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`                                                   // Collateral symbol
	WithdrawableAmount string                 `protobuf:"bytes,2,opt,name=withdrawable_amount,json=withdrawableAmount,proto3" json:"withdrawable_amount,omitempty"` // Max withdrawable in asset terms (for USDT: may exceed quantity, creating debt)
	Quantity           string                 `protobuf:"bytes,3,opt,name=quantity,proto3" json:"quantity,omitempty"`                                               // Current held balance (compare with withdrawable_amount to detect debt creation)
	PendingWithdraw    string                 `protobuf:"bytes,4,opt,name=pending_withdraw,json=pendingWithdraw,proto3" json:"pending_withdraw,omitempty"`          // Amount currently pending withdrawal
	WithdrawFee        string                 `protobuf:"bytes,5,opt,name=withdraw_fee,json=withdrawFee,proto3" json:"withdraw_fee,omitempty"`                      // Withdrawal fee for this asset
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *WithdrawableAmountItem) Reset() {
	*x = WithdrawableAmountItem{}
	mi := &file_trading_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawableAmountItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawableAmountItem) ProtoMessage() {}

func (x *WithdrawableAmountItem) ProtoReflect() protoreflect.Message {
	mi := &file_trading_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawableAmountItem.ProtoReflect.Descriptor instead.
func (*WithdrawableAmountItem) Descriptor() ([]byte, []int) {
	return file_trading_proto_rawDescGZIP(), []int{22}
}

func (x *WithdrawableAmountItem) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *WithdrawableAmountItem) GetWithdrawableAmount() string {
	if x != nil {
		return x.WithdrawableAmount
	}
	return ""
}

func (x *WithdrawableAmountItem) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

func (x *WithdrawableAmountItem) GetPendingWithdraw() string {
	if x != nil {
		return x.PendingWithdraw
	}
	return ""
}

func (x *WithdrawableAmountItem) GetWithdrawFee() string {
	if x != nil {
		return x.WithdrawFee
	}
	return ""
}

// Returns per-asset withdrawable amounts.
// Each item's withdrawable_amount is computed independently — they are NOT simultaneously
// achievable. Withdrawing the max of one asset will reduce the budget available for others.
type GetWithdrawableAmountsResponse struct {
	state                 protoimpl.MessageState    `protogen:"open.v1"`
	TmRespondedAt         *timestamppb.Timestamp    `protobuf:"bytes,104,opt,name=tm_responded_at,json=tmRespondedAt,proto3" json:"tm_responded_at,omitempty"`
	Items                 []*WithdrawableAmountItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	TotalWithdrawableUsdt string                    `protobuf:"bytes,2,opt,name=total_withdrawable_usdt,json=totalWithdrawableUsdt,proto3" json:"total_withdrawable_usdt,omitempty"` // USDT-denominated withdrawable budget from MarginSnapshot
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetWithdrawableAmountsResponse) Reset() {
	*x = GetWithdrawableAmountsResponse{}
	mi := &file_trading_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWithdrawableAmountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWithdrawableAmountsResponse) ProtoMessage() {}

func (x *GetWithdrawableAmountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trading_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWithdrawableAmountsResponse.ProtoReflect.Descriptor instead.
func (*GetWithdrawableAmountsResponse) Descriptor() ([]byte, []int) {
	return file_trading_proto_rawDescGZIP(), []int{23}
}

func (x *GetWithdrawableAmountsResponse) GetTmRespondedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TmRespondedAt
	}
	return nil
}

func (x *GetWithdrawableAmountsResponse) GetItems() []*WithdrawableAmountItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetWithdrawableAmountsResponse) GetTotalWithdrawableUsdt() string {
	if x != nil {
		return x.TotalWithdrawableUsdt
	}
	return ""
}

var File_trading_proto protoreflect.FileDescriptor

const file_trading_proto_rawDesc = "" +
	"\n" +
	"\rtrading.proto\x12\x1dsynthetix.v4_offchain.trading\x1a\fcommon.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x94\x02\n" +
	"\x11PlaceOrderRequest\x12B\n" +
	"\x0ftm_requested_at\x18g \x01(\v2\x1a.google.protobuf.TimestampR\rtmRequestedAt\x12$\n" +
	"\x0esub_account_id\x18\x01 \x01(\x03R\fsubAccountId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12L\n" +
	"\x06orders\x18\x03 \x03(\v24.synthetix.v4_offchain.trading.PlaceOrderRequestItemR\x06orders\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06sourceJ\x04\be\x10fJ\x04\bf\x10gJ\x04\bh\x10i\"\x9c\x06\n" +
	"\x15PlaceOrderRequestItem\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x126\n" +
	"\x04side\x18\x02 \x01(\x0e2\".synthetix.v4_offchain.common.SideR\x04side\x12;\n" +
	"\x04type\x18\x03 \x01(\x0e2'.synthetix.v4_offchain.common.OrderTypeR\x04type\x12R\n" +
	"\rtime_in_force\x18\x04 \x01(\x0e2).synthetix.v4_offchain.common.TimeInForceH\x00R\vtimeInForce\x88\x01\x01\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\tR\bquantity\x12\x1f\n" +
	"\vreduce_only\x18\x06 \x01(\bR\n" +
	"reduceOnly\x12\x19\n" +
	"\x05price\x18\a \x01(\tH\x01R\x05price\x88\x01\x01\x122\n" +
	"\x13new_client_order_id\x18\b \x01(\tH\x02R\x10newClientOrderId\x88\x01\x01\x12(\n" +
	"\rtrigger_price\x18\t \x01(\tH\x03R\ftriggerPrice\x88\x01\x01\x12\x1b\n" +
	"\tpost_only\x18\n" +
	" \x01(\bR\bpostOnly\x12%\n" +
	"\x0eclose_position\x18\v \x01(\bR\rclosePosition\x12,\n" +
	"\x12trigger_price_type\x18\f \x01(\tR\x10triggerPriceType\x12U\n" +
	"\vtwap_params\x18\r \x01(\v2/.synthetix.v4_offchain.trading.TWAPOrderRequestH\x04R\n" +
	"twapParams\x88\x01\x01\x12>\n" +
	"\n" +
	"expires_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampH\x05R\texpiresAt\x88\x01\x01B\x10\n" +
	"\x0e_time_in_forceB\b\n" +
	"\x06_priceB\x16\n" +
	"\x14_new_client_order_idB\x10\n" +
	"\x0e_trigger_priceB\x0e\n" +
	"\f_twap_paramsB\r\n" +
	"\v_expires_at\"h\n" +
	"\x10TWAPOrderRequest\x12)\n" +
	"\x10duration_seconds\x18\x01 \x01(\x03R\x0fdurationSeconds\x12)\n" +
	"\x10interval_seconds\x18\x02 \x01(\x03R\x0fintervalSeconds\"\xd8\x01\n" +
	"\x12PlaceOrderResponse\x12B\n" +
	"\x0ftm_responded_at\x18h \x01(\v2\x1a.google.protobuf.TimestampR\rtmRespondedAt\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12M\n" +
	"\x06orders\x18\x02 \x03(\v25.synthetix.v4_offchain.trading.PlaceOrderResponseItemR\x06ordersJ\x04\be\x10fJ\x04\bf\x10gJ\x04\bg\x10h\"\xc1\x03\n" +
	"\x16PlaceOrderResponseItem\x12@\n" +
	"\border_id\x18\x01 \x01(\v2%.synthetix.v4_offchain.common.OrderIdR\aorderId\x12\x17\n" +
	"\acum_qty\x18\x02 \x01(\tR\x06cumQty\x12\x1b\n" +
	"\tavg_price\x18\x03 \x01(\tR\bavgPrice\x12\x19\n" +
	"\borig_qty\x18\x04 \x01(\tR\aorigQty\x12A\n" +
	"\x06status\x18\x05 \x01(\x0e2).synthetix.v4_offchain.common.OrderStatusR\x06status\x12\x16\n" +
	"\x06symbol\x18\x06 \x01(\tR\x06symbol\x12\x1d\n" +
	"\n" +
	"is_success\x18\a \x01(\bR\tisSuccess\x12\x18\n" +
	"\amessage\x18\b \x01(\tR\amessage\x12\"\n" +
	"\n" +
	"error_code\x18\t \x01(\tH\x00R\terrorCode\x88\x01\x01\x12>\n" +
	"\n" +
	"expires_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampH\x01R\texpiresAt\x88\x01\x01B\r\n" +
	"\v_error_codeB\r\n" +
	"\v_expires_at\"\xd7\x01\n" +
	"\x12CancelOrderRequest\x12B\n" +
	"\x0ftm_requested_at\x18g \x01(\v2\x1a.google.protobuf.TimestampR\rtmRequestedAt\x12$\n" +
	"\x0esub_account_id\x18\x01 \x01(\x03R\fsubAccountId\x12&\n" +
	"\x0fvenue_order_ids\x18\x02 \x03(\x04R\rvenueOrderIds\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestIdJ\x04\be\x10fJ\x04\bf\x10gJ\x04\bh\x10i\"\xda\x01\n" +
	"\x13CancelOrderResponse\x12B\n" +
	"\x0ftm_responded_at\x18h \x01(\v2\x1a.google.protobuf.TimestampR\rtmRespondedAt\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12N\n" +
	"\x06orders\x18\x02 \x03(\v26.synthetix.v4_offchain.trading.CancelOrderResponseItemR\x06ordersJ\x04\be\x10fJ\x04\bf\x10gJ\x04\bg\x10h\"\xcb\x01\n" +
	"\x17CancelOrderResponseItem\x12@\n" +
	"\border_id\x18\x01 \x01(\v2%.synthetix.v4_offchain.common.OrderIdR\aorderId\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x12\"\n" +
	"\n" +
	"error_code\x18\x04 \x01(\tH\x00R\terrorCode\x88\x01\x01B\r\n" +
	"\v_error_code\"\xcd\x01\n" +
	"\x16CancelAllOrdersRequest\x12B\n" +
	"\x0ftm_requested_at\x18g \x01(\v2\x1a.google.protobuf.TimestampR\rtmRequestedAt\x12$\n" +
	"\x0esub_account_id\x18\x01 \x01(\x03R\fsubAccountId\x12\x18\n" +
	"\asymbols\x18\x02 \x03(\tR\asymbols\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestIdJ\x04\be\x10fJ\x04\bf\x10gJ\x04\bh\x10i\"\xde\x01\n" +
	"\x17CancelAllOrdersResponse\x12B\n" +
	"\x0ftm_responded_at\x18h \x01(\v2\x1a.google.protobuf.TimestampR\rtmRespondedAt\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12N\n" +
	"\x06orders\x18\x02 \x03(\v26.synthetix.v4_offchain.trading.CancelOrderResponseItemR\x06ordersJ\x04\be\x10fJ\x04\bf\x10gJ\x04\bg\x10h\"\xdb\x01\n" +
	"\x15ScheduleCancelRequest\x12B\n" +
	"\x0ftm_requested_at\x18g \x01(\v2\x1a.google.protobuf.TimestampR\rtmRequestedAt\x12$\n" +
	"\x0esub_account_id\x18\x01 \x01(\x03R\fsubAccountId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12'\n" +
	"\x0ftimeout_seconds\x18\x03 \x01(\x03R\x0etimeoutSecondsJ\x04\be\x10fJ\x04\bf\x10gJ\x04\bh\x10i\"\xac\x02\n" +
	"\x16ScheduleCancelResponse\x12B\n" +
	"\x0ftm_responded_at\x18h \x01(\v2\x1a.google.protobuf.TimestampR\rtmRespondedAt\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1b\n" +
	"\tis_active\x18\x02 \x01(\bR\bisActive\x12'\n" +
	"\x0ftimeout_seconds\x18\x03 \x01(\x03R\x0etimeoutSeconds\x12=\n" +
	"\ftrigger_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vtriggerTime\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessageJ\x04\be\x10fJ\x04\bf\x10gJ\x04\bg\x10h\"\xe0\x01\n" +
	"\x19CancelOrderByCloidRequest\x12B\n" +
	"\x0ftm_requested_at\x18g \x01(\v2\x1a.google.protobuf.TimestampR\rtmRequestedAt\x12$\n" +
	"\x0esub_account_id\x18\x01 \x01(\x03R\fsubAccountId\x12(\n" +
	"\x10client_order_ids\x18\x02 \x03(\tR\x0eclientOrderIds\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestIdJ\x04\be\x10fJ\x04\bf\x10gJ\x04\bh\x10i\"\xe4\x02\n" +
	"\x12ModifyOrderRequest\x12B\n" +
	"\x0ftm_requested_at\x18g \x01(\v2\x1a.google.protobuf.TimestampR\rtmRequestedAt\x12$\n" +
	"\x0esub_account_id\x18\x01 \x01(\x03R\fsubAccountId\x12$\n" +
	"\x0evenue_order_id\x18\x02 \x01(\x04R\fvenueOrderId\x12\x1f\n" +
	"\bquantity\x18\x03 \x01(\tH\x00R\bquantity\x88\x01\x01\x12\x19\n" +
	"\x05price\x18\x04 \x01(\tH\x01R\x05price\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"request_id\x18\x05 \x01(\tR\trequestId\x12(\n" +
	"\rtrigger_price\x18\x06 \x01(\tH\x02R\ftriggerPrice\x88\x01\x01B\v\n" +
	"\t_quantityB\b\n" +
	"\x06_priceB\x10\n" +
	"\x0e_trigger_priceJ\x04\be\x10fJ\x04\bf\x10gJ\x04\bh\x10i\"\x96\x05\n" +
	"\x13ModifyOrderResponse\x12B\n" +
	"\x0ftm_responded_at\x18h \x01(\v2\x1a.google.protobuf.TimestampR\rtmRespondedAt\x12@\n" +
	"\border_id\x18\x01 \x01(\v2%.synthetix.v4_offchain.common.OrderIdR\aorderId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x1f\n" +
	"\bquantity\x18\x03 \x01(\tH\x00R\bquantity\x88\x01\x01\x12\x19\n" +
	"\x05price\x18\x04 \x01(\tH\x01R\x05price\x88\x01\x01\x12(\n" +
	"\rtrigger_price\x18\x05 \x01(\tH\x02R\ftriggerPrice\x88\x01\x01\x12A\n" +
	"\x06status\x18\x06 \x01(\x0e2).synthetix.v4_offchain.common.OrderStatusR\x06status\x123\n" +
	"\x13cumulative_fill_qty\x18\a \x01(\tH\x03R\x11cumulativeFillQty\x88\x01\x01\x12(\n" +
	"\raverage_price\x18\b \x01(\tH\x04R\faveragePrice\x88\x01\x01\x12\"\n" +
	"\n" +
	"error_code\x18\t \x01(\tH\x05R\terrorCode\x88\x01\x01\x12(\n" +
	"\rerror_message\x18\n" +
	" \x01(\tH\x06R\ferrorMessage\x88\x01\x01B\v\n" +
	"\t_quantityB\b\n" +
	"\x06_priceB\x10\n" +
	"\x0e_trigger_priceB\x16\n" +
	"\x14_cumulative_fill_qtyB\x10\n" +
	"\x0e_average_priceB\r\n" +
	"\v_error_codeB\x10\n" +
	"\x0e_error_messageJ\x04\be\x10fJ\x04\bf\x10gJ\x04\bg\x10h\"\xed\x02\n" +
	"\x19ModifyOrderByCloidRequest\x12B\n" +
	"\x0ftm_requested_at\x18g \x01(\v2\x1a.google.protobuf.TimestampR\rtmRequestedAt\x12$\n" +
	"\x0esub_account_id\x18\x01 \x01(\x03R\fsubAccountId\x12&\n" +
	"\x0fclient_order_id\x18\x02 \x01(\tR\rclientOrderId\x12\x1f\n" +
	"\bquantity\x18\x03 \x01(\tH\x00R\bquantity\x88\x01\x01\x12\x19\n" +
	"\x05price\x18\x04 \x01(\tH\x01R\x05price\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"request_id\x18\x05 \x01(\tR\trequestId\x12(\n" +
	"\rtrigger_price\x18\x06 \x01(\tH\x02R\ftriggerPrice\x88\x01\x01B\v\n" +
	"\t_quantityB\b\n" +
	"\x06_priceB\x10\n" +
	"\x0e_trigger_priceJ\x04\be\x10fJ\x04\bf\x10gJ\x04\bh\x10i\"\xaf\x02\n" +
	"\x19WithdrawCollateralRequest\x12B\n" +
	"\x0ftm_requested_at\x18g \x01(\v2\x1a.google.protobuf.TimestampR\rtmRequestedAt\x12$\n" +
	"\x0esub_account_id\x18\x01 \x01(\x03R\fsubAccountId\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\tR\x06amount\x12 \n" +
	"\vdestination\x18\x04 \x01(\tR\vdestination\x12\x1d\n" +
	"\n" +
	"request_id\x18\x05 \x01(\tR\trequestId\x12%\n" +
	"\x0ewallet_address\x18\x06 \x01(\tR\rwalletAddressJ\x04\be\x10fJ\x04\bf\x10gJ\x04\bh\x10i\"\xe3\x01\n" +
	"\x1aWithdrawCollateralResponse\x12B\n" +
	"\x0ftm_responded_at\x18h \x01(\v2\x1a.google.protobuf.TimestampR\rtmRespondedAt\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\tR\x06amount\x12 \n" +
	"\vdestination\x18\x04 \x01(\tR\vdestinationJ\x04\be\x10fJ\x04\bf\x10gJ\x04\bg\x10h\"\xeb\x01\n" +
	"\x1cVoluntaryAutoExchangeRequest\x12B\n" +
	"\x0ftm_requested_at\x18g \x01(\v2\x1a.google.protobuf.TimestampR\rtmRequestedAt\x12$\n" +
	"\x0esub_account_id\x18\x01 \x01(\x03R\fsubAccountId\x12,\n" +
	"\x12target_usdt_amount\x18\x02 \x01(\tR\x10targetUsdtAmount\x12!\n" +
	"\fsource_asset\x18\x03 \x01(\tR\vsourceAssetJ\x04\be\x10fJ\x04\bf\x10gJ\x04\bh\x10i\"D\n" +
	"\x0eCollateralItem\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\tR\bquantity\"\xd3\x03\n" +
	"\x1dVoluntaryAutoExchangeResponse\x12B\n" +
	"\x0ftm_responded_at\x18h \x01(\v2\x1a.google.protobuf.TimestampR\rtmRespondedAt\x12$\n" +
	"\x0esub_account_id\x18\x01 \x01(\x03R\fsubAccountId\x12!\n" +
	"\fsource_asset\x18\x02 \x01(\tR\vsourceAsset\x12.\n" +
	"\x13source_amount_taken\x18\x03 \x01(\tR\x11sourceAmountTaken\x12!\n" +
	"\ftarget_asset\x18\x04 \x01(\tR\vtargetAsset\x12#\n" +
	"\rtarget_amount\x18\x05 \x01(\tR\ftargetAmount\x12\x1f\n" +
	"\vindex_price\x18\x06 \x01(\tR\n" +
	"indexPrice\x12+\n" +
	"\x11effective_haircut\x18\a \x01(\tR\x10effectiveHaircut\x12M\n" +
	"\n" +
	"collateral\x18\b \x03(\v2-.synthetix.v4_offchain.trading.CollateralItemR\n" +
	"collateralJ\x04\be\x10fJ\x04\bf\x10gJ\x04\bg\x10h\"\xb5\x01\n" +
	"\x1dGetWithdrawableAmountsRequest\x12B\n" +
	"\x0ftm_requested_at\x18g \x01(\v2\x1a.google.protobuf.TimestampR\rtmRequestedAt\x12$\n" +
	"\x0esub_account_id\x18\x01 \x01(\x03R\fsubAccountId\x12\x18\n" +
	"\asymbols\x18\x02 \x03(\tR\asymbolsJ\x04\be\x10fJ\x04\bf\x10gJ\x04\bh\x10i\"\xcb\x01\n" +
	"\x16WithdrawableAmountItem\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12/\n" +
	"\x13withdrawable_amount\x18\x02 \x01(\tR\x12withdrawableAmount\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\tR\bquantity\x12)\n" +
	"\x10pending_withdraw\x18\x04 \x01(\tR\x0fpendingWithdraw\x12!\n" +
	"\fwithdraw_fee\x18\x05 \x01(\tR\vwithdrawFee\"\xfb\x01\n" +
	"\x1eGetWithdrawableAmountsResponse\x12B\n" +
	"\x0ftm_responded_at\x18h \x01(\v2\x1a.google.protobuf.TimestampR\rtmRespondedAt\x12K\n" +
	"\x05items\x18\x01 \x03(\v25.synthetix.v4_offchain.trading.WithdrawableAmountItemR\x05items\x126\n" +
	"\x17total_withdrawable_usdt\x18\x02 \x01(\tR\x15totalWithdrawableUsdtJ\x04\be\x10fJ\x04\bf\x10gJ\x04\bg\x10h2\xa8\r\n" +
	"\x0eTradingService\x12\x80\x01\n" +
	"\x0fCancelAllOrders\x125.synthetix.v4_offchain.trading.CancelAllOrdersRequest\x1a6.synthetix.v4_offchain.trading.CancelAllOrdersResponse\x12t\n" +
	"\vCancelOrder\x121.synthetix.v4_offchain.trading.CancelOrderRequest\x1a2.synthetix.v4_offchain.trading.CancelOrderResponse\x12\x82\x01\n" +
	"\x12CancelOrderByCloid\x128.synthetix.v4_offchain.trading.CancelOrderByCloidRequest\x1a2.synthetix.v4_offchain.trading.CancelOrderResponse\x12t\n" +
	"\vModifyOrder\x121.synthetix.v4_offchain.trading.ModifyOrderRequest\x1a2.synthetix.v4_offchain.trading.ModifyOrderResponse\x12\x82\x01\n" +
	"\x12ModifyOrderByCloid\x128.synthetix.v4_offchain.trading.ModifyOrderByCloidRequest\x1a2.synthetix.v4_offchain.trading.ModifyOrderResponse\x12v\n" +
	"\x0fPlaceBatchOrder\x120.synthetix.v4_offchain.trading.PlaceOrderRequest\x1a1.synthetix.v4_offchain.trading.PlaceOrderResponse\x12y\n" +
	"\x12PlaceCompoundOrder\x120.synthetix.v4_offchain.trading.PlaceOrderRequest\x1a1.synthetix.v4_offchain.trading.PlaceOrderResponse\x12{\n" +
	"\x14PlacePositionTPAndSl\x120.synthetix.v4_offchain.trading.PlaceOrderRequest\x1a1.synthetix.v4_offchain.trading.PlaceOrderResponse\x12u\n" +
	"\x0ePlaceTWAPOrder\x120.synthetix.v4_offchain.trading.PlaceOrderRequest\x1a1.synthetix.v4_offchain.trading.PlaceOrderResponse\x12}\n" +
	"\x0eScheduleCancel\x124.synthetix.v4_offchain.trading.ScheduleCancelRequest\x1a5.synthetix.v4_offchain.trading.ScheduleCancelResponse\x12\x89\x01\n" +
	"\x12WithdrawCollateral\x128.synthetix.v4_offchain.trading.WithdrawCollateralRequest\x1a9.synthetix.v4_offchain.trading.WithdrawCollateralResponse\x12\x92\x01\n" +
	"\x15VoluntaryAutoExchange\x12;.synthetix.v4_offchain.trading.VoluntaryAutoExchangeRequest\x1a<.synthetix.v4_offchain.trading.VoluntaryAutoExchangeResponse\x12\x95\x01\n" +
	"\x16GetWithdrawableAmounts\x12<.synthetix.v4_offchain.trading.GetWithdrawableAmountsRequest\x1a=.synthetix.v4_offchain.trading.GetWithdrawableAmountsResponseB5Z3github.com/Synthetixio/v4-offchain/lib/message/grpcb\x06proto3"

var (
	file_trading_proto_rawDescOnce sync.Once
	file_trading_proto_rawDescData []byte
)

func file_trading_proto_rawDescGZIP() []byte {
	file_trading_proto_rawDescOnce.Do(func() {
		file_trading_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_trading_proto_rawDesc), len(file_trading_proto_rawDesc)))
	})
	return file_trading_proto_rawDescData
}

var file_trading_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_trading_proto_goTypes = []any{
	(*PlaceOrderRequest)(nil),              // 0: synthetix.v4_offchain.trading.PlaceOrderRequest
	(*PlaceOrderRequestItem)(nil),          // 1: synthetix.v4_offchain.trading.PlaceOrderRequestItem
	(*TWAPOrderRequest)(nil),               // 2: synthetix.v4_offchain.trading.TWAPOrderRequest
	(*PlaceOrderResponse)(nil),             // 3: synthetix.v4_offchain.trading.PlaceOrderResponse
	(*PlaceOrderResponseItem)(nil),         // 4: synthetix.v4_offchain.trading.PlaceOrderResponseItem
	(*CancelOrderRequest)(nil),             // 5: synthetix.v4_offchain.trading.CancelOrderRequest
	(*CancelOrderResponse)(nil),            // 6: synthetix.v4_offchain.trading.CancelOrderResponse
	(*CancelOrderResponseItem)(nil),        // 7: synthetix.v4_offchain.trading.CancelOrderResponseItem
	(*CancelAllOrdersRequest)(nil),         // 8: synthetix.v4_offchain.trading.CancelAllOrdersRequest
	(*CancelAllOrdersResponse)(nil),        // 9: synthetix.v4_offchain.trading.CancelAllOrdersResponse
	(*ScheduleCancelRequest)(nil),          // 10: synthetix.v4_offchain.trading.ScheduleCancelRequest
	(*ScheduleCancelResponse)(nil),         // 11: synthetix.v4_offchain.trading.ScheduleCancelResponse
	(*CancelOrderByCloidRequest)(nil),      // 12: synthetix.v4_offchain.trading.CancelOrderByCloidRequest
	(*ModifyOrderRequest)(nil),             // 13: synthetix.v4_offchain.trading.ModifyOrderRequest
	(*ModifyOrderResponse)(nil),            // 14: synthetix.v4_offchain.trading.ModifyOrderResponse
	(*ModifyOrderByCloidRequest)(nil),      // 15: synthetix.v4_offchain.trading.ModifyOrderByCloidRequest
	(*WithdrawCollateralRequest)(nil),      // 16: synthetix.v4_offchain.trading.WithdrawCollateralRequest
	(*WithdrawCollateralResponse)(nil),     // 17: synthetix.v4_offchain.trading.WithdrawCollateralResponse
	(*VoluntaryAutoExchangeRequest)(nil),   // 18: synthetix.v4_offchain.trading.VoluntaryAutoExchangeRequest
	(*CollateralItem)(nil),                 // 19: synthetix.v4_offchain.trading.CollateralItem
	(*VoluntaryAutoExchangeResponse)(nil),  // 20: synthetix.v4_offchain.trading.VoluntaryAutoExchangeResponse
	(*GetWithdrawableAmountsRequest)(nil),  // 21: synthetix.v4_offchain.trading.GetWithdrawableAmountsRequest
	(*WithdrawableAmountItem)(nil),         // 22: synthetix.v4_offchain.trading.WithdrawableAmountItem
	(*GetWithdrawableAmountsResponse)(nil), // 23: synthetix.v4_offchain.trading.GetWithdrawableAmountsResponse
	(*timestamppb.Timestamp)(nil),          // 24: google.protobuf.Timestamp
	(Side)(0),                              // 25: synthetix.v4_offchain.common.Side
	(OrderType)(0),                         // 26: synthetix.v4_offchain.common.OrderType
	(TimeInForce)(0),                       // 27: synthetix.v4_offchain.common.TimeInForce
	(*OrderId)(nil),                        // 28: synthetix.v4_offchain.common.OrderId
	(OrderStatus)(0),                       // 29: synthetix.v4_offchain.common.OrderStatus
}
var file_trading_proto_depIdxs = []int32{
	24, // 0: synthetix.v4_offchain.trading.PlaceOrderRequest.tm_requested_at:type_name -> google.protobuf.Timestamp
	1,  // 1: synthetix.v4_offchain.trading.PlaceOrderRequest.orders:type_name -> synthetix.v4_offchain.trading.PlaceOrderRequestItem
	25, // 2: synthetix.v4_offchain.trading.PlaceOrderRequestItem.side:type_name -> synthetix.v4_offchain.common.Side
	26, // 3: synthetix.v4_offchain.trading.PlaceOrderRequestItem.type:type_name -> synthetix.v4_offchain.common.OrderType
	27, // 4: synthetix.v4_offchain.trading.PlaceOrderRequestItem.time_in_force:type_name -> synthetix.v4_offchain.common.TimeInForce
	2,  // 5: synthetix.v4_offchain.trading.PlaceOrderRequestItem.twap_params:type_name -> synthetix.v4_offchain.trading.TWAPOrderRequest
	24, // 6: synthetix.v4_offchain.trading.PlaceOrderRequestItem.expires_at:type_name -> google.protobuf.Timestamp
	24, // 7: synthetix.v4_offchain.trading.PlaceOrderResponse.tm_responded_at:type_name -> google.protobuf.Timestamp
	4,  // 8: synthetix.v4_offchain.trading.PlaceOrderResponse.orders:type_name -> synthetix.v4_offchain.trading.PlaceOrderResponseItem
	28, // 9: synthetix.v4_offchain.trading.PlaceOrderResponseItem.order_id:type_name -> synthetix.v4_offchain.common.OrderId
	29, // 10: synthetix.v4_offchain.trading.PlaceOrderResponseItem.status:type_name -> synthetix.v4_offchain.common.OrderStatus
	24, // 11: synthetix.v4_offchain.trading.PlaceOrderResponseItem.expires_at:type_name -> google.protobuf.Timestamp
	24, // 12: synthetix.v4_offchain.trading.CancelOrderRequest.tm_requested_at:type_name -> google.protobuf.Timestamp
	24, // 13: synthetix.v4_offchain.trading.CancelOrderResponse.tm_responded_at:type_name -> google.protobuf.Timestamp
	7,  // 14: synthetix.v4_offchain.trading.CancelOrderResponse.orders:type_name -> synthetix.v4_offchain.trading.CancelOrderResponseItem
	28, // 15: synthetix.v4_offchain.trading.CancelOrderResponseItem.order_id:type_name -> synthetix.v4_offchain.common.OrderId
	24, // 16: synthetix.v4_offchain.trading.CancelAllOrdersRequest.tm_requested_at:type_name -> google.protobuf.Timestamp
	24, // 17: synthetix.v4_offchain.trading.CancelAllOrdersResponse.tm_responded_at:type_name -> google.protobuf.Timestamp
	7,  // 18: synthetix.v4_offchain.trading.CancelAllOrdersResponse.orders:type_name -> synthetix.v4_offchain.trading.CancelOrderResponseItem
	24, // 19: synthetix.v4_offchain.trading.ScheduleCancelRequest.tm_requested_at:type_name -> google.protobuf.Timestamp
	24, // 20: synthetix.v4_offchain.trading.ScheduleCancelResponse.tm_responded_at:type_name -> google.protobuf.Timestamp
	24, // 21: synthetix.v4_offchain.trading.ScheduleCancelResponse.trigger_time:type_name -> google.protobuf.Timestamp
	24, // 22: synthetix.v4_offchain.trading.CancelOrderByCloidRequest.tm_requested_at:type_name -> google.protobuf.Timestamp
	24, // 23: synthetix.v4_offchain.trading.ModifyOrderRequest.tm_requested_at:type_name -> google.protobuf.Timestamp
	24, // 24: synthetix.v4_offchain.trading.ModifyOrderResponse.tm_responded_at:type_name -> google.protobuf.Timestamp
	28, // 25: synthetix.v4_offchain.trading.ModifyOrderResponse.order_id:type_name -> synthetix.v4_offchain.common.OrderId
	29, // 26: synthetix.v4_offchain.trading.ModifyOrderResponse.status:type_name -> synthetix.v4_offchain.common.OrderStatus
	24, // 27: synthetix.v4_offchain.trading.ModifyOrderByCloidRequest.tm_requested_at:type_name -> google.protobuf.Timestamp
	24, // 28: synthetix.v4_offchain.trading.WithdrawCollateralRequest.tm_requested_at:type_name -> google.protobuf.Timestamp
	24, // 29: synthetix.v4_offchain.trading.WithdrawCollateralResponse.tm_responded_at:type_name -> google.protobuf.Timestamp
	24, // 30: synthetix.v4_offchain.trading.VoluntaryAutoExchangeRequest.tm_requested_at:type_name -> google.protobuf.Timestamp
	24, // 31: synthetix.v4_offchain.trading.VoluntaryAutoExchangeResponse.tm_responded_at:type_name -> google.protobuf.Timestamp
	19, // 32: synthetix.v4_offchain.trading.VoluntaryAutoExchangeResponse.collateral:type_name -> synthetix.v4_offchain.trading.CollateralItem
	24, // 33: synthetix.v4_offchain.trading.GetWithdrawableAmountsRequest.tm_requested_at:type_name -> google.protobuf.Timestamp
	24, // 34: synthetix.v4_offchain.trading.GetWithdrawableAmountsResponse.tm_responded_at:type_name -> google.protobuf.Timestamp
	22, // 35: synthetix.v4_offchain.trading.GetWithdrawableAmountsResponse.items:type_name -> synthetix.v4_offchain.trading.WithdrawableAmountItem
	8,  // 36: synthetix.v4_offchain.trading.TradingService.CancelAllOrders:input_type -> synthetix.v4_offchain.trading.CancelAllOrdersRequest
	5,  // 37: synthetix.v4_offchain.trading.TradingService.CancelOrder:input_type -> synthetix.v4_offchain.trading.CancelOrderRequest
	12, // 38: synthetix.v4_offchain.trading.TradingService.CancelOrderByCloid:input_type -> synthetix.v4_offchain.trading.CancelOrderByCloidRequest
	13, // 39: synthetix.v4_offchain.trading.TradingService.ModifyOrder:input_type -> synthetix.v4_offchain.trading.ModifyOrderRequest
	15, // 40: synthetix.v4_offchain.trading.TradingService.ModifyOrderByCloid:input_type -> synthetix.v4_offchain.trading.ModifyOrderByCloidRequest
	0,  // 41: synthetix.v4_offchain.trading.TradingService.PlaceBatchOrder:input_type -> synthetix.v4_offchain.trading.PlaceOrderRequest
	0,  // 42: synthetix.v4_offchain.trading.TradingService.PlaceCompoundOrder:input_type -> synthetix.v4_offchain.trading.PlaceOrderRequest
	0,  // 43: synthetix.v4_offchain.trading.TradingService.PlacePositionTPAndSl:input_type -> synthetix.v4_offchain.trading.PlaceOrderRequest
	0,  // 44: synthetix.v4_offchain.trading.TradingService.PlaceTWAPOrder:input_type -> synthetix.v4_offchain.trading.PlaceOrderRequest
	10, // 45: synthetix.v4_offchain.trading.TradingService.ScheduleCancel:input_type -> synthetix.v4_offchain.trading.ScheduleCancelRequest
	16, // 46: synthetix.v4_offchain.trading.TradingService.WithdrawCollateral:input_type -> synthetix.v4_offchain.trading.WithdrawCollateralRequest
	18, // 47: synthetix.v4_offchain.trading.TradingService.VoluntaryAutoExchange:input_type -> synthetix.v4_offchain.trading.VoluntaryAutoExchangeRequest
	21, // 48: synthetix.v4_offchain.trading.TradingService.GetWithdrawableAmounts:input_type -> synthetix.v4_offchain.trading.GetWithdrawableAmountsRequest
	9,  // 49: synthetix.v4_offchain.trading.TradingService.CancelAllOrders:output_type -> synthetix.v4_offchain.trading.CancelAllOrdersResponse
	6,  // 50: synthetix.v4_offchain.trading.TradingService.CancelOrder:output_type -> synthetix.v4_offchain.trading.CancelOrderResponse
	6,  // 51: synthetix.v4_offchain.trading.TradingService.CancelOrderByCloid:output_type -> synthetix.v4_offchain.trading.CancelOrderResponse
	14, // 52: synthetix.v4_offchain.trading.TradingService.ModifyOrder:output_type -> synthetix.v4_offchain.trading.ModifyOrderResponse
	14, // 53: synthetix.v4_offchain.trading.TradingService.ModifyOrderByCloid:output_type -> synthetix.v4_offchain.trading.ModifyOrderResponse
	3,  // 54: synthetix.v4_offchain.trading.TradingService.PlaceBatchOrder:output_type -> synthetix.v4_offchain.trading.PlaceOrderResponse
	3,  // 55: synthetix.v4_offchain.trading.TradingService.PlaceCompoundOrder:output_type -> synthetix.v4_offchain.trading.PlaceOrderResponse
	3,  // 56: synthetix.v4_offchain.trading.TradingService.PlacePositionTPAndSl:output_type -> synthetix.v4_offchain.trading.PlaceOrderResponse
	3,  // 57: synthetix.v4_offchain.trading.TradingService.PlaceTWAPOrder:output_type -> synthetix.v4_offchain.trading.PlaceOrderResponse
	11, // 58: synthetix.v4_offchain.trading.TradingService.ScheduleCancel:output_type -> synthetix.v4_offchain.trading.ScheduleCancelResponse
	17, // 59: synthetix.v4_offchain.trading.TradingService.WithdrawCollateral:output_type -> synthetix.v4_offchain.trading.WithdrawCollateralResponse
	20, // 60: synthetix.v4_offchain.trading.TradingService.VoluntaryAutoExchange:output_type -> synthetix.v4_offchain.trading.VoluntaryAutoExchangeResponse
	23, // 61: synthetix.v4_offchain.trading.TradingService.GetWithdrawableAmounts:output_type -> synthetix.v4_offchain.trading.GetWithdrawableAmountsResponse
	49, // [49:62] is the sub-list for method output_type
	36, // [36:49] is the sub-list for method input_type
	36, // [36:36] is the sub-list for extension type_name
	36, // [36:36] is the sub-list for extension extendee
	0,  // [0:36] is the sub-list for field type_name
}

func init() { file_trading_proto_init() }
func file_trading_proto_init() {
	if File_trading_proto != nil {
		return
	}
	file_common_proto_init()
	file_trading_proto_msgTypes[1].OneofWrappers = []any{}
	file_trading_proto_msgTypes[4].OneofWrappers = []any{}
	file_trading_proto_msgTypes[7].OneofWrappers = []any{}
	file_trading_proto_msgTypes[13].OneofWrappers = []any{}
	file_trading_proto_msgTypes[14].OneofWrappers = []any{}
	file_trading_proto_msgTypes[15].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_trading_proto_rawDesc), len(file_trading_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_trading_proto_goTypes,
		DependencyIndexes: file_trading_proto_depIdxs,
		MessageInfos:      file_trading_proto_msgTypes,
	}.Build()
	File_trading_proto = out.File
	file_trading_proto_goTypes = nil
	file_trading_proto_depIdxs = nil
}
