// Proto definition for Synthetix V4-Offchain WebSocket Service
// To compile:
// protoc --go_out=. --go-grpc_out=. websocket.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: websocket.proto

package grpc

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

// WebSocketNotificationServiceClient is the client API for WebSocketNotificationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WebSocketNotificationService provides an interface for sending real-time updates to WebSocket clients
type WebSocketNotificationServiceClient interface {
}

type webSocketNotificationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWebSocketNotificationServiceClient(cc grpc.ClientConnInterface) WebSocketNotificationServiceClient {
	return &webSocketNotificationServiceClient{cc}
}

// WebSocketNotificationServiceServer is the server API for WebSocketNotificationService service.
// All implementations must embed UnimplementedWebSocketNotificationServiceServer
// for forward compatibility.
//
// WebSocketNotificationService provides an interface for sending real-time updates to WebSocket clients
type WebSocketNotificationServiceServer interface {
	mustEmbedUnimplementedWebSocketNotificationServiceServer()
}

// UnimplementedWebSocketNotificationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWebSocketNotificationServiceServer struct{}

func (UnimplementedWebSocketNotificationServiceServer) mustEmbedUnimplementedWebSocketNotificationServiceServer() {
}
func (UnimplementedWebSocketNotificationServiceServer) testEmbeddedByValue() {}

// UnsafeWebSocketNotificationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WebSocketNotificationServiceServer will
// result in compilation errors.
type UnsafeWebSocketNotificationServiceServer interface {
	mustEmbedUnimplementedWebSocketNotificationServiceServer()
}

func RegisterWebSocketNotificationServiceServer(s grpc.ServiceRegistrar, srv WebSocketNotificationServiceServer) {
	// If the following call pancis, it indicates UnimplementedWebSocketNotificationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WebSocketNotificationService_ServiceDesc, srv)
}

// WebSocketNotificationService_ServiceDesc is the grpc.ServiceDesc for WebSocketNotificationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WebSocketNotificationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "synthetix.v4_offchain.websocket.WebSocketNotificationService",
	HandlerType: (*WebSocketNotificationServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "websocket.proto",
}
